package com.example.itemmanagement.ui.components

import kotlin.LazyThreadSafetyMode

internal val materialSymbols_social_chunk1: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "18_up_rating", codePoint = 63741, tags = listOf("18 plus", "18+", "access restriction", "adult content", "age limit", "age rating", "age restriction", "age verification")),
        MaterialSymbolInfo(name = "6_ft_apart", codePoint = 61982, tags = listOf("6", "6 feet", "apart", "body", "caution", "covid", "covid-19", "distance")),
        MaterialSymbolInfo(name = "add_moderator", codePoint = 59773, tags = listOf("+", "add", "add administrator", "add member", "add moderator", "add person", "add profile", "add user")),
        MaterialSymbolInfo(name = "add_reaction", codePoint = 57811, tags = listOf("+", "add", "add emotion", "add feeling", "add reaction", "append", "button", "chat")),
        MaterialSymbolInfo(name = "architecture", codePoint = 59963, tags = listOf("architecture", "art", "blueprint", "building", "city", "city building", "cityscape", "compass")),
        MaterialSymbolInfo(name = "assist_walker", codePoint = 63701, tags = listOf("accessibility", "accessible", "aid", "assist", "assistance", "assisted living", "assistive device", "body")),
        MaterialSymbolInfo(name = "back_hand", codePoint = 59236, tags = listOf("anatomy", "appendage", "back", "back of hand", "backhand", "body part", "fingers", "five")),
        MaterialSymbolInfo(name = "blind", codePoint = 63702, tags = listOf("abstract", "accessibility", "accessible", "assist", "blind", "blinds", "blinds down", "block")),
        MaterialSymbolInfo(name = "boy", codePoint = 60263, tags = listOf("account", "avatar", "body", "boy", "bust", "character", "child", "gender")),
        MaterialSymbolInfo(name = "cake", codePoint = 59369, tags = listOf("add", "anniversary", "baked", "baked goods", "bakery", "birthday", "cake", "candle")),
        MaterialSymbolInfo(name = "catching_pokemon", codePoint = 58632, tags = listOf("catching", "go", "pokemon", "pokestop", "travel")),
        MaterialSymbolInfo(name = "clean_hands", codePoint = 61983, tags = listOf("bacteria", "body", "bubbles", "care", "clean", "cleanse", "disinfect", "germ")),
        MaterialSymbolInfo(name = "co2", codePoint = 59312, tags = listOf("air", "atom", "carbon", "carbon dioxide", "chemical", "chemical compound", "chemical formula", "chemistry")),
        MaterialSymbolInfo(name = "compost", codePoint = 59233, tags = listOf("bin", "bio", "biomass", "compost", "compostable", "composting", "container", "decomposable")),
        MaterialSymbolInfo(name = "connect_without_contact", codePoint = 61987, tags = listOf("broadcast", "communicating", "communication", "connect", "connection", "connectivity", "contact", "contactless")),
        MaterialSymbolInfo(name = "construction", codePoint = 59964, tags = listOf("build", "builder", "building", "carpenter", "construction", "developing", "development", "engineer")),
        MaterialSymbolInfo(name = "cookie", codePoint = 60076, tags = listOf("alert", "baked goods", "biscuit", "chocolate chip cookie", "circle", "circle with dots", "circular", "compliance")),
        MaterialSymbolInfo(name = "coronavirus", codePoint = 61985, tags = listOf("19", "bacteria", "biohazard", "biology", "cell", "circle", "contagious", "coronavirus")),
        MaterialSymbolInfo(name = "cruelty_free", codePoint = 59289, tags = listOf("animal", "animal friendly", "animal testing", "animal welfare", "beauty", "bunny", "care", "cosmetics")),
        MaterialSymbolInfo(name = "cyclone", codePoint = 60373, tags = listOf("air", "airflow", "alert", "atmosphere", "chaos", "circular motion", "climate", "crisis")),
        MaterialSymbolInfo(name = "deck", codePoint = 59970, tags = listOf("aligned", "angled", "bridge", "cards", "cards deck", "chairs", "collection", "deck")),
        MaterialSymbolInfo(name = "diversity_1", codePoint = 63703, tags = listOf("account", "avatar", "characters", "circle", "collaboration", "collective", "committee", "community")),
        MaterialSymbolInfo(name = "diversity_2", codePoint = 63704, tags = listOf("avatars", "collaboration", "committee", "community", "diverse", "diversity", "equal", "equality")),
        MaterialSymbolInfo(name = "diversity_3", codePoint = 63705, tags = listOf("committee", "community", "community icon", "crowd", "culture", "different", "different people", "diverse")),
        MaterialSymbolInfo(name = "domain", codePoint = 59374, tags = listOf("address", "apartment", "architecture", "building", "business", "circle", "communication", "concept")),
        MaterialSymbolInfo(name = "domain_add", codePoint = 60258, tags = listOf("+", "add", "add domain", "add site", "add website", "apartment", "append", "architecture")),
        MaterialSymbolInfo(name = "downhill_skiing", codePoint = 58633, tags = listOf("abstract", "activity", "athlete", "athletic", "body", "downhill", "entertainment", "exercise")),
        MaterialSymbolInfo(name = "edit_notifications", codePoint = 58661, tags = listOf("active", "adjust", "alarm", "alert", "bell", "bell with pencil", "change", "chime")),
        MaterialSymbolInfo(name = "elderly", codePoint = 61978, tags = listOf("account", "account icon", "account representation", "age", "avatar", "body", "cane", "community")),
        MaterialSymbolInfo(name = "elderly_woman", codePoint = 60265, tags = listOf("aged", "avatar", "body", "cane", "circle", "elderly", "female", "figure")),
        MaterialSymbolInfo(name = "emoji_emotions", codePoint = 59938, tags = listOf("+", "add", "character", "chat", "cheerful", "circle", "communication", "emoji")),
        MaterialSymbolInfo(name = "emoji_events", codePoint = 59939, tags = listOf("accomplishment", "achievement", "achievement award", "award", "award icon", "celebration", "chalice", "challenge")),
        MaterialSymbolInfo(name = "emoji_food_beverage", codePoint = 59931, tags = listOf("beverage", "break", "cafe", "caffeine", "ceramic", "coffee", "cup", "curve")),
        MaterialSymbolInfo(name = "emoji_nature", codePoint = 59932, tags = listOf("animal", "bee", "botany", "branch", "bug", "daisy", "earth", "ecology")),
        MaterialSymbolInfo(name = "emoji_objects", codePoint = 59940, tags = listOf("avatar", "bulb", "cartoon", "character", "chat", "cheerful", "circle", "communication")),
        MaterialSymbolInfo(name = "emoji_people", codePoint = 59933, tags = listOf("accounts", "arm", "assembly", "audience", "avatars", "body", "community", "contacts")),
        MaterialSymbolInfo(name = "emoji_symbols", codePoint = 59934, tags = listOf("add emoji", "ampersand", "character", "chat", "communication", "emoji", "emoji picker", "emoticon")),
        MaterialSymbolInfo(name = "emoji_transportation", codePoint = 59935, tags = listOf("architecture", "arrow", "automobile", "building", "car", "carriage", "cars", "commute")),
        MaterialSymbolInfo(name = "engineering", codePoint = 59965, tags = listOf("adjustment", "automation", "body", "building", "cog", "cogs", "cogwheel", "configuration")),
        MaterialSymbolInfo(name = "face_2", codePoint = 63706, tags = listOf("account", "amiable", "avatar", "character", "cheerful", "contentment", "delightful", "emoji")),
        MaterialSymbolInfo(name = "face_3", codePoint = 63707, tags = listOf("account", "avatar", "avatar 3", "avatar icon", "emoji", "eyes", "face", "features")),
        MaterialSymbolInfo(name = "face_4", codePoint = 63708, tags = listOf("account", "avatar", "bland", "character", "circle", "emoji", "emotion", "expression")),
        MaterialSymbolInfo(name = "face_5", codePoint = 63709, tags = listOf("account", "avatar", "avatar icon", "character", "communication", "emoji", "emotion", "expression")),
        MaterialSymbolInfo(name = "face_6", codePoint = 63710, tags = listOf("account", "avatar", "cheerful", "contented", "delighted", "emoji", "emotion", "expression")),
        MaterialSymbolInfo(name = "female", codePoint = 58768, tags = listOf("account", "addition", "avatar", "basic", "biological", "biological sex", "character", "circle")),
        MaterialSymbolInfo(name = "fireplace", codePoint = 59971, tags = listOf("barbecue", "burning", "camping", "chimney", "comfort", "cooking", "cozy", "ember")),
        MaterialSymbolInfo(name = "fitbit", codePoint = 59435, tags = listOf("abstract", "activity", "app", "application", "athlete", "athletic", "brand", "brand identity")),
        MaterialSymbolInfo(name = "flood", codePoint = 60390, tags = listOf("abstract waves", "alert", "climate", "climate change", "crisis", "danger", "deluge", "disaster")),
        MaterialSymbolInfo(name = "follow_the_signs", codePoint = 61986, tags = listOf("arrow", "body", "crossroads", "destination", "direction", "directional", "follow", "forward")),
        MaterialSymbolInfo(name = "front_hand", codePoint = 59241, tags = listOf("accessibility", "alert", "anatomy", "body part", "communication", "control", "cursor", "fingers")),
        MaterialSymbolInfo(name = "girl", codePoint = 60264, tags = listOf("account", "avatar", "body", "character", "female", "feminine", "figure", "gender")),
        MaterialSymbolInfo(name = "group", codePoint = 59375, tags = listOf("accounts", "administration", "audience", "basic", "committee", "community", "contacts", "crowd")),
        MaterialSymbolInfo(name = "group_add", codePoint = 59376, tags = listOf("accounts", "add", "add friend", "add member", "add user", "avatar", "circle", "collaborate")),
        MaterialSymbolInfo(name = "group_off", codePoint = 59207, tags = listOf("association off", "body", "cancel group", "club", "cluster off", "collaboration", "collection off", "community off")),
        MaterialSymbolInfo(name = "group_remove", codePoint = 59309, tags = listOf("account remove", "accounts", "action", "application", "button", "collaboration", "committee", "community")),
        MaterialSymbolInfo(name = "groups", codePoint = 62003, tags = listOf("audience", "avatars", "body", "club", "collaboration", "collective", "community", "connected")),
        MaterialSymbolInfo(name = "groups_2", codePoint = 63711, tags = listOf("assembly", "avatars", "body", "circle", "club", "collaboration", "community", "community icon")),
        MaterialSymbolInfo(name = "groups_3", codePoint = 63712, tags = listOf("abstract", "account", "assembly", "audience", "avatars", "body", "circle", "club")),
        MaterialSymbolInfo(name = "handshake", codePoint = 60363, tags = listOf("accord", "agreement", "alliance", "business", "collaboration", "connection", "contract", "cooperation")),
        MaterialSymbolInfo(name = "health_and_safety", codePoint = 57813, tags = listOf("+", "add", "aid", "and", "care", "certified", "cross", "cross symbol"))
    )
}

internal val materialSymbols_social_chunk2: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "heart_broken", codePoint = 60098, tags = listOf("bad review", "break", "broken", "broken heart", "core", "crush", "delete", "dislike")),
        MaterialSymbolInfo(name = "hiking", codePoint = 58634, tags = listOf("activity", "adventure", "backpacking", "bag", "climbing", "duffle", "exercise", "exploration")),
        MaterialSymbolInfo(name = "history_edu", codePoint = 59966, tags = listOf("academic", "archive", "book", "clock", "college", "degree", "diploma", "document")),
        MaterialSymbolInfo(name = "hive", codePoint = 60070, tags = listOf("abstract", "apiary", "bee", "beehive", "cluster", "collection", "colony", "community")),
        MaterialSymbolInfo(name = "ice_skating", codePoint = 58635, tags = listOf("activity", "athlete", "athletic", "blade", "boot", "cold", "entertainment", "equipment")),
        MaterialSymbolInfo(name = "interests", codePoint = 59336, tags = listOf("best", "bookmark", "chosen", "circle", "collection", "distinction", "favorite", "featured")),
        MaterialSymbolInfo(name = "ios_share", codePoint = 59064, tags = listOf("action", "app", "apple", "arrow", "box", "button", "communication", "connect")),
        MaterialSymbolInfo(name = "kayaking", codePoint = 58636, tags = listOf("activity", "adventure", "athlete", "athletic", "boat", "body", "canoe", "entertainment")),
        MaterialSymbolInfo(name = "king_bed", codePoint = 59973, tags = listOf("accommodation", "apartment", "bed", "bedroom", "building", "comfort", "domestic", "double")),
        MaterialSymbolInfo(name = "kitesurfing", codePoint = 58637, tags = listOf("action", "activity", "adventure", "athlete", "athletic", "beach", "board", "body")),
        MaterialSymbolInfo(name = "landslide", codePoint = 60375, tags = listOf("accident", "alert", "caution", "collapse", "crisis", "danger", "disaster", "earth")),
        MaterialSymbolInfo(name = "location_city", codePoint = 59377, tags = listOf("apartments", "architecture", "area", "building", "buildings", "business", "city", "community")),
        MaterialSymbolInfo(name = "luggage", codePoint = 62005, tags = listOf("airport", "bag", "baggage", "belongings", "box", "carry", "carry-on", "essentials")),
        MaterialSymbolInfo(name = "male", codePoint = 58766, tags = listOf("account", "avatar", "avatar icon", "body", "body icon", "boy", "circle", "figure")),
        MaterialSymbolInfo(name = "man", codePoint = 58603, tags = listOf("account", "avatar", "body", "boy", "character", "figure", "gender", "graphic")),
        MaterialSymbolInfo(name = "man_2", codePoint = 63713, tags = listOf("account", "avatar", "biography", "boy", "bust", "contact", "contact information", "gender")),
        MaterialSymbolInfo(name = "man_3", codePoint = 63714, tags = listOf("abstract", "account", "avatar", "boy", "circle", "contact", "figure", "gender")),
        MaterialSymbolInfo(name = "man_4", codePoint = 63715, tags = listOf("abstract", "account", "account icon", "account management", "avatar", "boy", "community", "contact")),
        MaterialSymbolInfo(name = "masks", codePoint = 61976, tags = listOf("air", "breath", "contagion", "cover", "covid", "disease", "face", "face covering")),
        MaterialSymbolInfo(name = "military_tech", codePoint = 59967, tags = listOf("accomplishment", "achievement", "air force", "army", "award", "badge", "decoration", "defense")),
        MaterialSymbolInfo(name = "mood", codePoint = 59378, tags = listOf("add", "character", "chat", "cheerful", "circle", "communication", "emoji", "emoticon")),
        MaterialSymbolInfo(name = "mood_bad", codePoint = 59379, tags = listOf("avatar", "bad", "circle", "circular", "disappointment", "dislike", "distress", "emoji")),
        MaterialSymbolInfo(name = "nights_stay", codePoint = 59974, tags = listOf("astronomy", "atmosphere", "bedroom", "climate", "cloud", "cloudy", "crescent", "dark")),
        MaterialSymbolInfo(name = "no_adult_content", codePoint = 63742, tags = listOf("access control", "age rating", "age restriction", "block", "censored", "content restriction", "disallowed", "explicit content")),
        MaterialSymbolInfo(name = "no_luggage", codePoint = 62011, tags = listOf("access denied", "airport", "alert", "bag", "baggage", "baggage check", "ban", "box")),
        MaterialSymbolInfo(name = "nordic_walking", codePoint = 58638, tags = listOf("active", "activity", "athlete", "athletic", "body", "entertainment", "equipment", "exercise")),
        MaterialSymbolInfo(name = "notification_add", codePoint = 58265, tags = listOf("+", "active", "add", "addition", "alarm", "alert", "bell", "button")),
        MaterialSymbolInfo(name = "notifications", codePoint = 59380, tags = listOf("active", "alarm", "alert", "announcement", "app", "bell", "chime", "communication")),
        MaterialSymbolInfo(name = "notifications_active", codePoint = 59383, tags = listOf("active", "alarm", "alert", "attention", "bell", "broadcast", "chime", "communication")),
        MaterialSymbolInfo(name = "notifications_none", codePoint = 59381, tags = listOf("alarm", "alert", "announcement", "app", "bell", "communication", "control", "ding")),
        MaterialSymbolInfo(name = "notifications_off", codePoint = 59382, tags = listOf("active", "alarm", "alarm off", "alert", "alert off", "bell", "bell off", "blocked")),
        MaterialSymbolInfo(name = "notifications_paused", codePoint = 59384, tags = listOf("active", "alarm", "alert", "attention", "bell", "caution", "chime", "cross")),
        MaterialSymbolInfo(name = "outdoor_grill", codePoint = 59975, tags = listOf("appliance", "backyard", "barbecue", "barbeque", "bbq", "charcoal", "chimney", "cook")),
        MaterialSymbolInfo(name = "pages", codePoint = 59385, tags = listOf("archive", "article", "bundle", "collection", "content", "copy", "data", "documents")),
        MaterialSymbolInfo(name = "paragliding", codePoint = 58639, tags = listOf("activity", "adventure", "aerial", "air", "altitude", "athlete", "athletic", "body")),
        MaterialSymbolInfo(name = "party_mode", codePoint = 59386, tags = listOf("bright", "camera", "camera mode", "celebration", "celebration mode", "cheerful", "energetic", "enjoy")),
        MaterialSymbolInfo(name = "people", codePoint = 59387, tags = listOf("accounts", "administration", "audience", "basic", "committee", "community", "contacts", "crowd")),
        MaterialSymbolInfo(name = "people_alt", codePoint = 59937, tags = listOf("accounts", "administration", "audience", "basic", "committee", "community", "contacts", "crowd")),
        MaterialSymbolInfo(name = "people_outline", codePoint = 59388, tags = listOf("accounts", "administration", "audience", "basic", "committee", "community", "contacts", "crowd")),
        MaterialSymbolInfo(name = "person", codePoint = 59389, tags = listOf("account", "avatar", "avatar filled", "avatar outline", "body", "circle", "contact", "face")),
        MaterialSymbolInfo(name = "person_2", codePoint = 63716, tags = listOf("abstract", "account", "avatar", "basic", "body", "circle", "default", "face")),
        MaterialSymbolInfo(name = "person_3", codePoint = 63717, tags = listOf("account", "association", "audience", "avatar", "collaboration", "collective", "community", "company")),
        MaterialSymbolInfo(name = "person_4", codePoint = 63718, tags = listOf("account", "account settings", "anonymous", "avatar", "contact", "default", "face", "figure")),
        MaterialSymbolInfo(name = "person_add", codePoint = 59390, tags = listOf("+", "account", "account outline", "add", "add contact", "add friend", "add person", "add user")),
        MaterialSymbolInfo(name = "person_add_alt", codePoint = 59981, tags = listOf("+", "account", "account outline", "add", "add contact", "add friend", "add person", "add user")),
        MaterialSymbolInfo(name = "person_add_alt_1", codePoint = 61285, tags = listOf()),
        MaterialSymbolInfo(name = "person_off", codePoint = 58640, tags = listOf("access denied", "account", "avatar", "block", "circle", "deactivate", "disable", "disabled")),
        MaterialSymbolInfo(name = "person_outline", codePoint = 59391, tags = listOf("account", "avatar", "avatar filled", "avatar outline", "body", "circle", "contact", "face")),
        MaterialSymbolInfo(name = "person_remove", codePoint = 61286, tags = listOf("account", "avatar", "ban", "blacklist", "block", "cancellation", "circle", "contact")),
        MaterialSymbolInfo(name = "person_remove_alt_1", codePoint = 61287, tags = listOf()),
        MaterialSymbolInfo(name = "personal_injury", codePoint = 59098, tags = listOf("accident", "accident claim", "aid", "anatomy", "arm", "bandage", "body", "bone")),
        MaterialSymbolInfo(name = "piano", codePoint = 58657, tags = listOf("art", "audio", "band", "black keys", "classical music", "concert", "entertainment", "harmony")),
        MaterialSymbolInfo(name = "piano_off", codePoint = 58656, tags = listOf("audio", "audio settings", "control", "crossed out", "deactivated", "diagonal line", "disabled", "enabled")),
        MaterialSymbolInfo(name = "pix", codePoint = 60067, tags = listOf("bill", "brazil", "card", "cash", "commerce", "credit", "currency", "finance")),
        MaterialSymbolInfo(name = "plus_one", codePoint = 59392, tags = listOf("1", "add", "adjustment", "arithmetic", "button", "camera setting", "count", "counter")),
        MaterialSymbolInfo(name = "poll", codePoint = 59393, tags = listOf("add", "analysis", "analytics", "assessment", "bar", "bar chart", "bars", "business")),
        MaterialSymbolInfo(name = "precision_manufacturing", codePoint = 61513, tags = listOf("accurate", "advanced", "arm", "assembly", "assembly line", "automated", "automatic", "automation")),
        MaterialSymbolInfo(name = "psychology", codePoint = 59978, tags = listOf("awareness", "behavior", "body", "brain", "brainstorm", "clever", "cognitive", "concept")),
        MaterialSymbolInfo(name = "psychology_alt", codePoint = 63722, tags = listOf("?", "abstract", "alternate", "analysis", "assistance", "awareness", "behavior", "body")),
        MaterialSymbolInfo(name = "public", codePoint = 59403, tags = listOf("access", "accessibility", "circle", "community", "connection", "country", "earth", "everybody"))
    )
}

internal val materialSymbols_social_chunk3: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "public_off", codePoint = 61898, tags = listOf("access", "circle", "connection", "continents", "disabled", "earth", "enabled", "geography")),
        MaterialSymbolInfo(name = "real_estate_agent", codePoint = 59194, tags = listOf("advice", "agent", "agreement", "architecture", "associate", "broker", "building", "business")),
        MaterialSymbolInfo(name = "recommend", codePoint = 59858, tags = listOf("affirm", "agree", "agreement", "approval", "approved", "assess", "choice", "circle")),
        MaterialSymbolInfo(name = "recycling", codePoint = 59232, tags = listOf("arrows", "arrows in a loop", "bio", "circle", "conservation", "cycle", "eco", "ecological")),
        MaterialSymbolInfo(name = "reduce_capacity", codePoint = 61980, tags = listOf("arrow", "body", "capacity", "capacity reduction", "compact", "compress", "constrain", "contract")),
        MaterialSymbolInfo(name = "remove_moderator", codePoint = 59860, tags = listOf("access", "account", "admin", "administrator", "ban", "block", "cancel", "certified")),
        MaterialSymbolInfo(name = "roller_skating", codePoint = 60365, tags = listOf("active", "activity", "athlete", "athletic", "blade", "boot", "entertainment", "exercise")),
        MaterialSymbolInfo(name = "safety_divider", codePoint = 57804, tags = listOf("apart", "barrier", "border", "boundary", "delineate", "demarcation", "distance", "divide")),
        MaterialSymbolInfo(name = "sanitizer", codePoint = 61981, tags = listOf("anti-bacterial", "bacteria", "bathroom", "bottle", "clean", "clean hands", "cleaning", "covid")),
        MaterialSymbolInfo(name = "scale", codePoint = 60255, tags = listOf("balance", "balance scale", "compare", "compare measure", "compare weight", "comparing", "comparison", "courtroom")),
        MaterialSymbolInfo(name = "school", codePoint = 59404, tags = listOf("academic", "academics", "academy", "achievement", "architecture", "building", "building facade", "campus")),
        MaterialSymbolInfo(name = "science", codePoint = 59979, tags = listOf("analysis", "beaker", "beaker icon", "chemical", "chemistry", "chemistry icon", "container", "discovery")),
        MaterialSymbolInfo(name = "scoreboard", codePoint = 60368, tags = listOf("board", "competition", "data", "display", "game", "information", "leader", "lines")),
        MaterialSymbolInfo(name = "scuba_diving", codePoint = 60366, tags = listOf("activity", "adventure", "aquatic", "deep sea", "discovery", "diver", "diving", "entertainment")),
        MaterialSymbolInfo(name = "self_improvement", codePoint = 60024, tags = listOf("balance", "body", "brain", "calm", "care", "chi", "coaching", "counseling")),
        MaterialSymbolInfo(name = "sentiment_dissatisfied", codePoint = 59409, tags = listOf("angry", "avatar", "bad", "circle", "disappointed", "dislike", "dissatisfied", "emoticon")),
        MaterialSymbolInfo(name = "sentiment_neutral", codePoint = 59410, tags = listOf("attitude", "avatar", "average", "emoji", "emotion", "emotionless", "emotions", "expression")),
        MaterialSymbolInfo(name = "sentiment_satisfied", codePoint = 59411, tags = listOf("cheerful", "circle", "emoji", "emoticon", "emotion", "emotions", "expression", "expressions")),
        MaterialSymbolInfo(name = "sentiment_very_dissatisfied", codePoint = 59412, tags = listOf("angry", "avatar", "character", "circle", "disappointed", "disapproval", "dislike", "dissatisfied")),
        MaterialSymbolInfo(name = "sentiment_very_satisfied", codePoint = 59413, tags = listOf("approval", "avatar", "character", "cheerful", "circle", "delight", "emoticon", "emotion")),
        MaterialSymbolInfo(name = "severe_cold", codePoint = 60371, tags = listOf("!", "alert", "atmosphere", "attention", "blizzard", "caution", "chill", "climate")),
        MaterialSymbolInfo(name = "share", codePoint = 59405, tags = listOf("DISABLE_IOS", "activity", "andriod share", "android", "arrow", "communication", "communication icon", "connect")),
        MaterialSymbolInfo(name = "sick", codePoint = 61984, tags = listOf("ailment", "covid", "discomfort", "emoji", "emoticon", "emotion", "emotions", "expression")),
        MaterialSymbolInfo(name = "sign_language", codePoint = 60389, tags = listOf("accessibility", "audio", "caption", "communication", "deaf", "disability", "figure", "fingers")),
        MaterialSymbolInfo(name = "single_bed", codePoint = 59976, tags = listOf("accommodations", "apartment", "bed", "bed silhouette", "bedroom", "bedtime", "comfort", "double")),
        MaterialSymbolInfo(name = "skateboarding", codePoint = 58641, tags = listOf("action", "active", "activity", "athlete", "athletic", "board", "body", "entertainment")),
        MaterialSymbolInfo(name = "sledding", codePoint = 58642, tags = listOf("activity", "athlete", "athletic", "body", "child", "christmas", "cold", "downhill")),
        MaterialSymbolInfo(name = "snowboarding", codePoint = 58643, tags = listOf("action", "activity", "athlete", "athletic", "board", "body", "carve", "cold")),
        MaterialSymbolInfo(name = "snowshoeing", codePoint = 58644, tags = listOf("activity", "adventure", "body", "boots", "cold", "equipment", "explore", "footwear")),
        MaterialSymbolInfo(name = "social_distance", codePoint = 57803, tags = listOf("6", "alert", "apart", "body", "caution", "concept", "covid-19", "distance")),
        MaterialSymbolInfo(name = "south_america", codePoint = 59364, tags = listOf("area", "boundary", "cartography", "continent", "continent map", "continent outline", "country", "domain")),
        MaterialSymbolInfo(name = "sports", codePoint = 59952, tags = listOf("action", "activity", "athlete", "athletic", "blowing", "coach", "competition", "dynamic")),
        MaterialSymbolInfo(name = "sports_baseball", codePoint = 59985, tags = listOf("activity", "american sport", "athlete", "athletic", "ball", "baseball", "catch", "circle")),
        MaterialSymbolInfo(name = "sports_basketball", codePoint = 59942, tags = listOf("activity", "arena", "athlete", "athletic", "ball", "basketball", "circle", "competition")),
        MaterialSymbolInfo(name = "sports_cricket", codePoint = 59943, tags = listOf("activity", "athlete", "athletic", "athletics", "ball", "bat", "circle", "competition")),
        MaterialSymbolInfo(name = "sports_esports", codePoint = 59944, tags = listOf("asset", "competitive gaming", "computer games", "console", "console controller", "console games", "control", "controller")),
        MaterialSymbolInfo(name = "sports_football", codePoint = 59945, tags = listOf("activity", "athlete", "athletic", "ball", "championship", "competition", "entertainment", "equipment")),
        MaterialSymbolInfo(name = "sports_golf", codePoint = 59946, tags = listOf("activity", "athlete", "athletic", "ball", "club", "course", "driver", "entertainment")),
        MaterialSymbolInfo(name = "sports_gymnastics", codePoint = 60356, tags = listOf("active", "activity", "agility", "athlete", "athletic", "balance", "body", "competition")),
        MaterialSymbolInfo(name = "sports_handball", codePoint = 59955, tags = listOf("activity", "athlete", "athletic", "athletic event", "athletics", "ball", "body", "circle")),
        MaterialSymbolInfo(name = "sports_hockey", codePoint = 59947, tags = listOf("activity", "athlete", "athletic", "athletic activity", "athletic game", "athletic sports", "championship", "club")),
        MaterialSymbolInfo(name = "sports_kabaddi", codePoint = 59956, tags = listOf("action", "active", "agility", "asian", "athlete", "athletic", "athletics", "body")),
        MaterialSymbolInfo(name = "sports_martial_arts", codePoint = 60137, tags = listOf("action", "activity", "agility", "arts", "athlete", "athletic", "combat", "competition")),
        MaterialSymbolInfo(name = "sports_mma", codePoint = 59948, tags = listOf("action", "activity", "aggression", "arena", "arts", "athlete", "athletic", "boxing")),
        MaterialSymbolInfo(name = "sports_motorsports", codePoint = 59949, tags = listOf("activity", "athlete", "athletic", "automobile", "automotive", "automotive industry", "bike", "car")),
        MaterialSymbolInfo(name = "sports_rugby", codePoint = 59950, tags = listOf("activity", "athlete", "athletic", "athletic gear", "ball", "competition", "entertainment", "equipment")),
        MaterialSymbolInfo(name = "sports_soccer", codePoint = 59951, tags = listOf("activity", "athlete", "athletic", "ball", "championship", "circle", "competition", "dribble")),
        MaterialSymbolInfo(name = "sports_tennis", codePoint = 59954, tags = listOf("active", "activity", "athlete", "athletic", "ball", "bat", "competition", "court")),
        MaterialSymbolInfo(name = "sports_volleyball", codePoint = 59953, tags = listOf("activity", "athlete", "athletic", "ball", "block", "competition", "court", "dig")),
        MaterialSymbolInfo(name = "surfing", codePoint = 58645, tags = listOf("action", "activity", "athlete", "athletic", "beach", "board", "body", "entertainment")),
        MaterialSymbolInfo(name = "switch_account", codePoint = 59885, tags = listOf("access", "access control", "account", "account management", "accounts", "arrows", "bidirectional", "change profile")),
        MaterialSymbolInfo(name = "thumb_down_alt", codePoint = 59414, tags = listOf("bad", "cancel", "decline", "disagree", "disapproval", "disapprove", "dislike", "down")),
        MaterialSymbolInfo(name = "thumb_up_alt", codePoint = 59415, tags = listOf("acknowledgement", "agree", "agreed", "approve", "approved", "button", "choice", "confirm")),
        MaterialSymbolInfo(name = "thunderstorm", codePoint = 60379, tags = listOf("alert", "atmosphere", "bad weather", "bolt", "climate", "cloud", "cloudy", "danger")),
        MaterialSymbolInfo(name = "tornado", codePoint = 57753, tags = listOf("alert", "atmospheric", "climate", "cone", "crisis", "danger", "destructive", "disaster")),
        MaterialSymbolInfo(name = "transgender", codePoint = 58765, tags = listOf("arrow", "biological sex", "circle", "community", "cross", "diversity", "equality", "female")),
        MaterialSymbolInfo(name = "travel_explore", codePoint = 58075, tags = listOf("adventure", "browser", "circle", "destination", "discover", "discovery", "earth", "explore")),
        MaterialSymbolInfo(name = "tsunami", codePoint = 60376, tags = listOf("alert", "breaking wave", "climate", "coastal", "cresting wave", "crisis", "danger", "disaster")),
        MaterialSymbolInfo(name = "vaccines", codePoint = 57656, tags = listOf("aid", "care", "circle", "clinic", "covid", "cross", "disease", "doctor")),
        MaterialSymbolInfo(name = "volcano", codePoint = 60378, tags = listOf("alert", "ash", "cone", "crisis", "danger", "disaster", "earth", "emergency"))
    )
}

internal val materialSymbols_social_chunk4: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "wallet", codePoint = 63743, tags = listOf("account", "banking", "budget", "business", "cash", "commerce", "credit", "currency")),
        MaterialSymbolInfo(name = "water_drop", codePoint = 59288, tags = listOf("adjustments", "aqua", "blob", "concentration", "conservation", "density", "drink", "drip")),
        MaterialSymbolInfo(name = "waving_hand", codePoint = 59238, tags = listOf("acknowledgement", "activity", "availability", "avatar", "body part", "bye", "chat", "communication")),
        MaterialSymbolInfo(name = "whatshot", codePoint = 59406, tags = listOf("alert", "alerts", "arrow", "blaze", "burning", "circle", "dangerous", "direction")),
        MaterialSymbolInfo(name = "woman", codePoint = 57662, tags = listOf("account", "avatar", "character", "circle", "contact", "female", "female avatar", "female identity")),
        MaterialSymbolInfo(name = "woman_2", codePoint = 63719, tags = listOf("abstract", "account", "avatar", "bust", "female", "figure", "gender", "girl")),
        MaterialSymbolInfo(name = "workspace_premium", codePoint = 59311, tags = listOf("achievement", "approval", "authentic", "authority", "award", "badge", "certification", "circle"))
    )
}

internal val materialSymbols_social_category: MaterialSymbolCategory by lazy(LazyThreadSafetyMode.NONE) {
    MaterialSymbolCategory(
        key = "social",
        icons = buildList {
            addAll(materialSymbols_social_chunk1)
            addAll(materialSymbols_social_chunk2)
            addAll(materialSymbols_social_chunk3)
            addAll(materialSymbols_social_chunk4)
        }
    )
}
