package com.example.itemmanagement.ui.components

import kotlin.LazyThreadSafetyMode

internal val materialSymbols_image_chunk1: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "10mp", codePoint = 59730, tags = listOf("10", "10mp", "camera", "camera specifications", "capture", "detail", "digital", "digits")),
        MaterialSymbolInfo(name = "11mp", codePoint = 59731, tags = listOf("11", "camera", "detail", "digital", "digits", "display", "eleven", "font")),
        MaterialSymbolInfo(name = "12mp", codePoint = 59732, tags = listOf("12", "12 megapixels", "12mp", "camera", "camera icon", "camera quality", "definition", "digit")),
        MaterialSymbolInfo(name = "13mp", codePoint = 59733, tags = listOf("13", "13 megapixel", "camera", "camera information", "camera resolution", "camera settings", "digital image", "digits")),
        MaterialSymbolInfo(name = "14mp", codePoint = 59734, tags = listOf("14", "14mp", "camera", "camera settings", "clarity", "detail", "digital", "digits")),
        MaterialSymbolInfo(name = "15mp", codePoint = 59735, tags = listOf("15", "15mp", "attributes", "camera", "data", "details", "digital", "digits")),
        MaterialSymbolInfo(name = "16mp", codePoint = 59736, tags = listOf("16", "16 megapixels", "camera", "camera mode", "camera resolution", "camera settings", "camera specs", "digital image")),
        MaterialSymbolInfo(name = "17mp", codePoint = 59737, tags = listOf("17", "camera", "counting", "designation", "digits", "double digit", "font", "identifier")),
        MaterialSymbolInfo(name = "18mp", codePoint = 59738, tags = listOf("18", "18mp", "alphanumeric.", "camera", "camera information", "camera sensor", "camera settings", "detail")),
        MaterialSymbolInfo(name = "19mp", codePoint = 59739, tags = listOf("19", "19mp", "camera", "data", "detail", "digital", "digits", "feature")),
        MaterialSymbolInfo(name = "20mp", codePoint = 59742, tags = listOf("20", "camera", "detail", "digital", "digits", "display", "font", "image")),
        MaterialSymbolInfo(name = "21mp", codePoint = 59743, tags = listOf("21", "21mp", "camera", "camera setting", "clarity", "detail", "detailed", "digits")),
        MaterialSymbolInfo(name = "22mp", codePoint = 59744, tags = listOf("22", "camera", "center", "circle", "compass", "connection", "coordinates", "crosshair")),
        MaterialSymbolInfo(name = "23mp", codePoint = 59745, tags = listOf("23", "23mp", "camera", "clarity", "detail", "digital", "digits", "font")),
        MaterialSymbolInfo(name = "24mp", codePoint = 59746, tags = listOf("24", "camera", "data", "detail", "digital", "digits", "display", "file")),
        MaterialSymbolInfo(name = "2mp", codePoint = 59749, tags = listOf("2", "2mp", "camera", "camera sensor", "detail", "digit", "digital", "font")),
        MaterialSymbolInfo(name = "30fps_select", codePoint = 61391, tags = listOf("30", "30fps", "camera", "capture", "choose", "digital video", "digits", "fps")),
        MaterialSymbolInfo(name = "3mp", codePoint = 59752, tags = listOf("3", "3mp", "camera", "clarity", "definition", "digit", "digital media", "display")),
        MaterialSymbolInfo(name = "4mp", codePoint = 59754, tags = listOf("4", "4mp", "aspect ratio", "camera", "clarity", "data", "detail", "digit")),
        MaterialSymbolInfo(name = "5mp", codePoint = 59757, tags = listOf("5", "5mp", "camera", "capture", "clarity", "detail", "digit", "digital")),
        MaterialSymbolInfo(name = "60fps_select", codePoint = 61397, tags = listOf("60", "60fps", "camera", "choice", "circle", "circular", "configuration", "control")),
        MaterialSymbolInfo(name = "6mp", codePoint = 59760, tags = listOf("6", "camera", "camera info", "camera mode", "camera settings", "detail level", "digit", "digital photography")),
        MaterialSymbolInfo(name = "7mp", codePoint = 59763, tags = listOf("7", "action", "active", "animation", "buffering", "busy", "camera", "circle")),
        MaterialSymbolInfo(name = "8mp", codePoint = 59766, tags = listOf("8", "8mp", "camera", "capture", "detail", "device", "digit", "digital")),
        MaterialSymbolInfo(name = "9mp", codePoint = 59769, tags = listOf("9", "9 megapixel", "9 mp", "9mp", "camera", "camera icon", "camera resolution", "camera settings")),
        MaterialSymbolInfo(name = "add_a_photo", codePoint = 58425, tags = listOf("+", "a photo", "add", "album", "button", "camera", "capture", "create")),
        MaterialSymbolInfo(name = "add_photo_alternate", codePoint = 58430, tags = listOf("+", "add", "addition", "album", "alternate", "art", "capture", "choose")),
        MaterialSymbolInfo(name = "add_to_photos", codePoint = 58269, tags = listOf("add", "album", "append", "camera", "capture", "cloud", "collection", "create")),
        MaterialSymbolInfo(name = "adjust", codePoint = 58270, tags = listOf("adjust", "alter", "auto click", "bar", "bars", "calibration", "center", "change")),
        MaterialSymbolInfo(name = "animation", codePoint = 59164, tags = listOf("active", "activity", "activity indicator", "animation", "busy", "circle", "circles", "concentric")),
        MaterialSymbolInfo(name = "assistant", codePoint = 58271, tags = listOf("ai", "answer", "artificial", "artificial intelligence", "assistant", "assistant bubble", "automatic", "automation")),
        MaterialSymbolInfo(name = "assistant_photo", codePoint = 58272, tags = listOf("achievement", "assistant", "banner", "bookmark", "border", "country", "empty", "flag")),
        MaterialSymbolInfo(name = "audiotrack", codePoint = 58273, tags = listOf("audio", "audio file", "audio icon", "audiotrack", "clef", "composition", "eighth note", "key")),
        MaterialSymbolInfo(name = "auto_awesome", codePoint = 58975, tags = listOf("adjust", "ai", "artificial", "artificial intelligence", "auto", "automatic", "automation", "awesome")),
        MaterialSymbolInfo(name = "auto_awesome_mosaic", codePoint = 58976, tags = listOf("adjust", "album", "arrange", "art", "auto", "automatic", "awesome", "blocks")),
        MaterialSymbolInfo(name = "auto_awesome_motion", codePoint = 58977, tags = listOf("AI", "adjust", "animate", "animation", "auto", "automatic", "automation", "awesome")),
        MaterialSymbolInfo(name = "auto_fix_high", codePoint = 58979, tags = listOf("adjust", "ai", "artificial", "auto", "automated", "automatic", "automatically", "automation")),
        MaterialSymbolInfo(name = "auto_fix_normal", codePoint = 58980, tags = listOf("adjust", "ai", "apply", "artificial", "auto", "auto fix", "automated", "automatic")),
        MaterialSymbolInfo(name = "auto_fix_off", codePoint = 58981, tags = listOf("adjustments off", "ai", "artificial", "auto", "auto enhance off", "auto fix off", "automatic", "automation")),
        MaterialSymbolInfo(name = "auto_stories", codePoint = 58982, tags = listOf("archive", "articles", "auto", "bibliography", "book", "books", "chapter", "collection")),
        MaterialSymbolInfo(name = "autofps_select", codePoint = 61404, tags = listOf("A", "adjust", "alphabet", "animation", "auto", "automatic", "character", "chart")),
        MaterialSymbolInfo(name = "bedtime", codePoint = 61252, tags = listOf("astronomy", "bedtime", "calm", "celestial", "celestial bodies", "clear", "clear night", "clear sky")),
        MaterialSymbolInfo(name = "bedtime_off", codePoint = 60278, tags = listOf("active", "bedtime", "button", "clear", "climate", "crescent", "disabled", "dream")),
        MaterialSymbolInfo(name = "blur_circular", codePoint = 58274, tags = listOf("aesthetic", "art", "blur", "circle", "circular", "design", "diffused", "dots")),
        MaterialSymbolInfo(name = "blur_linear", codePoint = 58275, tags = listOf("adjust", "art", "blend", "blur", "dots", "edit", "editing", "editor")),
        MaterialSymbolInfo(name = "blur_off", codePoint = 58276, tags = listOf("adjust", "blur", "blur off", "clarity", "clear", "crisp", "deactivate", "definition")),
        MaterialSymbolInfo(name = "blur_on", codePoint = 58277, tags = listOf("activate", "active", "blur", "blur on", "circle", "diffuse", "disabled", "dots")),
        MaterialSymbolInfo(name = "brightness_1", codePoint = 58278, tags = listOf("1", "active", "badge", "basic", "brightness", "centralized", "circle", "complete")),
        MaterialSymbolInfo(name = "brightness_2", codePoint = 58279, tags = listOf("2", "adjust", "adjustment", "brightness", "circle", "contrast", "control", "crescent")),
        MaterialSymbolInfo(name = "brightness_3", codePoint = 58280, tags = listOf("3", "adjust", "astronomy", "atmosphere", "brightness", "celestial", "celestial body", "circle")),
        MaterialSymbolInfo(name = "brightness_4", codePoint = 58281, tags = listOf("4", "adjustment", "bar", "brightness", "circle", "contrast", "control", "crescent")),
        MaterialSymbolInfo(name = "brightness_5", codePoint = 58282, tags = listOf("5", "adjust", "brightness", "button", "circle", "control", "crescent", "display")),
        MaterialSymbolInfo(name = "brightness_6", codePoint = 58283, tags = listOf("6", "adjust", "brightness", "circle", "contrast", "control", "crescent", "dark")),
        MaterialSymbolInfo(name = "brightness_7", codePoint = 58284, tags = listOf("7", "adjust", "appearance", "bright", "bright light", "brightness", "circle", "clear")),
        MaterialSymbolInfo(name = "broken_image", codePoint = 58285, tags = listOf("alert", "broken", "content", "corrupt", "damaged", "data", "default", "display error")),
        MaterialSymbolInfo(name = "brush", codePoint = 58286, tags = listOf("art", "artist", "artistic", "bristle", "brush", "color", "creative", "design")),
        MaterialSymbolInfo(name = "burst_mode", codePoint = 58428, tags = listOf("action", "burst", "burst mode", "camera", "capture", "continuous", "fast", "frames")),
        MaterialSymbolInfo(name = "camera", codePoint = 58287, tags = listOf("aperture", "button", "camera", "capture", "capture device", "device", "digital", "electronic")),
        MaterialSymbolInfo(name = "camera_alt", codePoint = 58288, tags = listOf("alt", "analog", "button", "camera", "capture", "circle", "device", "digital")),
        MaterialSymbolInfo(name = "camera_front", codePoint = 58289, tags = listOf("body", "camera", "capture", "circle", "device", "flip camera", "front", "front facing camera"))
    )
}

internal val materialSymbols_image_chunk2: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "camera_rear", codePoint = 58290, tags = listOf("aperture", "back camera", "camera", "camera mode", "camera toggle", "capture", "capture image", "circle")),
        MaterialSymbolInfo(name = "camera_roll", codePoint = 58291, tags = listOf("album", "browse photos", "camera", "camera roll", "collection", "digital photos", "film", "gallery")),
        MaterialSymbolInfo(name = "cases", codePoint = 59794, tags = listOf("administration", "archive", "bag", "baggage", "briefcase", "briefcases", "bureaucracy", "business")),
        MaterialSymbolInfo(name = "center_focus_strong", codePoint = 58292, tags = listOf("accuracy", "adjust", "aiming", "alignment", "area", "boundaries", "box", "camera")),
        MaterialSymbolInfo(name = "center_focus_weak", codePoint = 58293, tags = listOf("aim", "alignment", "area", "boundaries", "camera", "capture", "center", "center focus weak")),
        MaterialSymbolInfo(name = "circle", codePoint = 61258, tags = listOf("active", "angle", "bullet", "button", "circle", "circular", "complete", "disc")),
        MaterialSymbolInfo(name = "collections", codePoint = 58294, tags = listOf("adjustments", "album", "categorization", "categorize", "choices", "collection", "collections", "control")),
        MaterialSymbolInfo(name = "collections_bookmark", codePoint = 58417, tags = listOf("album", "archive", "bookmark", "books", "categorized", "collection", "collections", "documents")),
        MaterialSymbolInfo(name = "color_lens", codePoint = 58295, tags = listOf("appearance", "art", "artist", "artistic", "brush", "color", "colors", "creative")),
        MaterialSymbolInfo(name = "colorize", codePoint = 58296, tags = listOf("adjustments", "appearance", "art", "brush", "color", "color fill", "color options", "color palette")),
        MaterialSymbolInfo(name = "compare", codePoint = 58297, tags = listOf("adjust", "adjustment", "analysis", "analyze", "chart", "compare", "comparison", "comparison tool")),
        MaterialSymbolInfo(name = "contrast", codePoint = 60215, tags = listOf("adjust", "adjustment", "balance", "black", "bright", "brightness", "contrast", "control")),
        MaterialSymbolInfo(name = "control_point", codePoint = 58298, tags = listOf("+", "action", "add", "append", "button", "circle", "circular", "content")),
        MaterialSymbolInfo(name = "control_point_duplicate", codePoint = 58299, tags = listOf("+", "add", "addmultiple", "circle", "circles", "clone", "control", "copy")),
        MaterialSymbolInfo(name = "crop", codePoint = 58302, tags = listOf("adjust", "adjustments", "area", "boundary", "clip", "corners", "crop", "cropping")),
        MaterialSymbolInfo(name = "crop_16_9", codePoint = 58300, tags = listOf("16:9", "adjust", "adjustments", "area", "aspect ratio", "by", "canvas", "cinema")),
        MaterialSymbolInfo(name = "crop_3_2", codePoint = 58301, tags = listOf("3 by 2", "3:2", "3x2", "adjust", "adjustments", "area", "aspect ratio", "by")),
        MaterialSymbolInfo(name = "crop_5_4", codePoint = 58303, tags = listOf("5:4", "adjust", "adjustments", "area", "aspect ratio", "border", "boundary", "by")),
        MaterialSymbolInfo(name = "crop_7_5", codePoint = 58304, tags = listOf("7:5 ratio", "adjust", "adjustments", "area", "art", "aspect ratio", "bounding box", "by")),
        MaterialSymbolInfo(name = "crop_din", codePoint = 58305, tags = listOf("adjust", "adjustments", "area", "area selection", "aspect ratio", "border", "boundary", "contract")),
        MaterialSymbolInfo(name = "crop_free", codePoint = 58306, tags = listOf("adjust", "adjustments", "area", "bounding box", "box", "corners", "crop", "crop free")),
        MaterialSymbolInfo(name = "crop_landscape", codePoint = 58307, tags = listOf("adjust", "adjustments", "area", "aspect ratio", "border", "crop", "crop landscape", "dimensions")),
        MaterialSymbolInfo(name = "crop_original", codePoint = 58308, tags = listOf("add", "adjust", "adjustments", "album", "area", "asset", "camera", "collection")),
        MaterialSymbolInfo(name = "crop_portrait", codePoint = 58309, tags = listOf("adjust", "adjustments", "area", "aspect ratio", "crop", "dimensions", "edit", "editing")),
        MaterialSymbolInfo(name = "crop_rotate", codePoint = 58423, tags = listOf("adjust", "adjustments", "area", "arrow", "arrows", "aspect ratio", "canvas", "circle")),
        MaterialSymbolInfo(name = "crop_square", codePoint = 58310, tags = listOf("adjust", "adjustments", "app", "application", "area", "area selection", "aspect ratio", "border")),
        MaterialSymbolInfo(name = "currency_bitcoin", codePoint = 60357, tags = listOf("bill", "bitcoin", "blockchain", "card", "cash", "circle", "coin", "commerce")),
        MaterialSymbolInfo(name = "currency_franc", codePoint = 60154, tags = listOf("banking", "bill", "budget", "capital", "card", "cash", "coin", "commerce")),
        MaterialSymbolInfo(name = "currency_lira", codePoint = 60143, tags = listOf("bar", "bill", "buy", "capital letter", "card", "cash", "coin", "commerce")),
        MaterialSymbolInfo(name = "currency_pound", codePoint = 60145, tags = listOf("accounting", "alphabet", "banking", "bill", "british pound", "budget", "card", "cash")),
        MaterialSymbolInfo(name = "currency_ruble", codePoint = 60140, tags = listOf("banking", "bill", "billing", "budget", "business", "card", "cash", "character")),
        MaterialSymbolInfo(name = "currency_rupee", codePoint = 60151, tags = listOf("bank", "banking", "bill", "buy", "card", "cash", "coin", "commerce")),
        MaterialSymbolInfo(name = "currency_yen", codePoint = 60155, tags = listOf("bank", "banking", "bill", "capital", "card", "cash", "coin", "commerce")),
        MaterialSymbolInfo(name = "currency_yuan", codePoint = 60153, tags = listOf("banking", "bill", "business", "buy", "card", "cash", "character", "china")),
        MaterialSymbolInfo(name = "deblur", codePoint = 60279, tags = listOf("adjust", "adjustment", "application", "button", "clarity", "contrast", "control", "correction")),
        MaterialSymbolInfo(name = "dehaze", codePoint = 58311, tags = listOf("adjust", "adjustments", "air", "atmospheric", "clarity", "clear", "dehaze", "edit")),
        MaterialSymbolInfo(name = "details", codePoint = 58312, tags = listOf("additional", "data", "data icon", "detail", "details", "dots", "edit", "editing")),
        MaterialSymbolInfo(name = "dirty_lens", codePoint = 61259, tags = listOf("alert", "blurred", "camera", "capture", "circle", "cleaning", "dirt", "dirty")),
        MaterialSymbolInfo(name = "edit", codePoint = 58313, tags = listOf("action", "alter", "author", "change", "compose", "control", "create", "document")),
        MaterialSymbolInfo(name = "euro", codePoint = 59925, tags = listOf("banking", "bill", "card", "cash", "coin", "commerce", "cost", "credit")),
        MaterialSymbolInfo(name = "exposure", codePoint = 58314, tags = listOf("add", "adjustment", "bar", "brightness", "camera", "contrast", "controls", "edit")),
        MaterialSymbolInfo(name = "exposure_neg_1", codePoint = 58315, tags = listOf("1", "adjust", "brightness", "brightness adjustment", "camera control", "contrast", "controls", "dark")),
        MaterialSymbolInfo(name = "exposure_neg_2", codePoint = 58316, tags = listOf("2", "adjust", "brightness", "camera", "contrast", "control", "correction", "dark")),
        MaterialSymbolInfo(name = "exposure_plus_1", codePoint = 58317, tags = listOf("1", "add", "adjustment", "arithmetic", "brightness", "button", "camera setting", "contrast")),
        MaterialSymbolInfo(name = "exposure_plus_2", codePoint = 58318, tags = listOf("2", "add", "adjust", "adjustment", "brightness", "contrast", "darkroom", "digit")),
        MaterialSymbolInfo(name = "exposure_zero", codePoint = 58319, tags = listOf("0", "adjust", "balance", "brightness", "camera", "centered", "contrast", "control")),
        MaterialSymbolInfo(name = "face_retouching_natural", codePoint = 61262, tags = listOf("adjust", "ai", "artificial", "automatic", "automation", "avatar", "beauty", "camera")),
        MaterialSymbolInfo(name = "face_retouching_off", codePoint = 61447, tags = listOf("avatar", "beauty", "blemish", "block", "cancel", "circle", "disable", "disabled")),
        MaterialSymbolInfo(name = "filter", codePoint = 58323, tags = listOf("adjustments", "categorization", "categorize", "choices", "collection", "collections", "control", "criteria")),
        MaterialSymbolInfo(name = "filter_1", codePoint = 58320, tags = listOf("1", "adjust", "amount", "choice", "control", "count", "criteria", "customization")),
        MaterialSymbolInfo(name = "filter_2", codePoint = 58321, tags = listOf("2", "array", "categorize", "count", "customize", "data", "digit", "display")),
        MaterialSymbolInfo(name = "filter_3", codePoint = 58322, tags = listOf("3", "adjust", "adjustment", "bars", "control", "controls", "count", "counting")),
        MaterialSymbolInfo(name = "filter_4", codePoint = 58324, tags = listOf("4", "adjust", "choose", "control", "count", "criteria", "data", "digit")),
        MaterialSymbolInfo(name = "filter_5", codePoint = 58325, tags = listOf("5", "adjust", "configure", "constraints", "count", "criteria", "data", "digit")),
        MaterialSymbolInfo(name = "filter_6", codePoint = 58326, tags = listOf("6", "apply filter", "count", "count filter", "data filter", "data refinement", "digit", "edit")),
        MaterialSymbolInfo(name = "filter_7", codePoint = 58327, tags = listOf("7", "adjust", "analysis", "category", "choose", "count", "customize", "data")),
        MaterialSymbolInfo(name = "filter_8", codePoint = 58328, tags = listOf("8", "adjust", "categorize", "constrain", "control", "criteria", "criterion", "customize")),
        MaterialSymbolInfo(name = "filter_9", codePoint = 58329, tags = listOf("9", "adjust", "categories", "control", "counter", "criteria", "data", "digit")),
        MaterialSymbolInfo(name = "filter_9_plus", codePoint = 58330, tags = listOf("+", "9", "9 plus", "9+", "amount", "criteria", "data", "digit")),
        MaterialSymbolInfo(name = "filter_b_and_w", codePoint = 58331, tags = listOf("and", "apply", "b", "b&w", "black", "black and white", "camera", "classic"))
    )
}

internal val materialSymbols_image_chunk3: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "filter_center_focus", codePoint = 58332, tags = listOf("adjust", "aiming", "alignment", "box", "calibration", "camera", "camera settings", "center")),
        MaterialSymbolInfo(name = "filter_drama", codePoint = 58333, tags = listOf("atmosphere", "cinematic", "cloud", "dark", "drama", "edit", "editing", "effect")),
        MaterialSymbolInfo(name = "filter_frames", codePoint = 58334, tags = listOf("albums", "arrangement", "boarders", "border", "camera", "center", "depth", "display")),
        MaterialSymbolInfo(name = "filter_hdr", codePoint = 58335, tags = listOf("button", "camera", "control", "earth", "edit", "editing", "effect", "effects")),
        MaterialSymbolInfo(name = "filter_none", codePoint = 58336, tags = listOf("basic", "blank", "clean", "clear", "default", "empty", "filter", "multiple")),
        MaterialSymbolInfo(name = "filter_tilt_shift", codePoint = 58338, tags = listOf("adjustment", "aperture", "blur", "camera", "center", "circle", "circular", "control")),
        MaterialSymbolInfo(name = "filter_vintage", codePoint = 58339, tags = listOf("abstract", "adjust", "bloom", "blossom", "camera", "decorative", "edit", "editing")),
        MaterialSymbolInfo(name = "flare", codePoint = 58340, tags = listOf("blast", "bright", "burst", "burst of light", "camera", "edit", "editing", "effect")),
        MaterialSymbolInfo(name = "flash_auto", codePoint = 58341, tags = listOf("a", "auto", "auto mode", "automatic", "bolt", "bright", "burst", "camera")),
        MaterialSymbolInfo(name = "flash_off", codePoint = 58342, tags = listOf("bolt", "camera control", "camera flash", "camera option", "camera setting", "dark", "deactivate", "disable flash")),
        MaterialSymbolInfo(name = "flash_on", codePoint = 58343, tags = listOf("activate", "alert", "bolt", "bright", "camera", "camera flash", "danger", "disabled")),
        MaterialSymbolInfo(name = "flip", codePoint = 58344, tags = listOf("actions", "adjust", "arrow", "change", "change direction", "commands", "dash", "dashed")),
        MaterialSymbolInfo(name = "flip_camera_android", codePoint = 59959, tags = listOf("android", "arrows", "back camera", "camera", "camera direction", "camera icon", "camera perspective", "camera switch")),
        MaterialSymbolInfo(name = "flip_camera_ios", codePoint = 59960, tags = listOf("DISABLE_IOS", "android", "arrows", "camera", "camera toggle", "capture", "change", "circle")),
        MaterialSymbolInfo(name = "gradient", codePoint = 58345, tags = listOf("appearance", "art", "background", "blend", "color", "contrast", "dark", "design")),
        MaterialSymbolInfo(name = "grain", codePoint = 58346, tags = listOf("adjust", "analog", "art", "detail", "digital art", "dots", "edit", "editing")),
        MaterialSymbolInfo(name = "grid_off", codePoint = 58347, tags = listOf("arrangement", "blocked", "collage", "cross out", "diagonal line", "disable", "disabled", "display")),
        MaterialSymbolInfo(name = "grid_on", codePoint = 58348, tags = listOf("alignment", "arrange", "array", "background", "blocks", "bounding box", "cells", "chart")),
        MaterialSymbolInfo(name = "hdr_enhanced_select", codePoint = 61265, tags = listOf("add", "adjustment", "alphabet", "brightness", "camera", "character", "color", "contrast")),
        MaterialSymbolInfo(name = "hdr_off", codePoint = 58349, tags = listOf("alphabet", "button", "camera settings", "cancel", "character", "control", "diagonal line", "disabled")),
        MaterialSymbolInfo(name = "hdr_on", codePoint = 58350, tags = listOf("activate", "add", "alphabet", "button", "camera", "capture", "character", "control")),
        MaterialSymbolInfo(name = "hdr_plus", codePoint = 61470, tags = listOf("+", "activate", "add", "alphabet", "button", "camera", "character", "circle")),
        MaterialSymbolInfo(name = "hdr_strong", codePoint = 58353, tags = listOf("adjust", "adjust image", "brightness", "camera", "camera settings", "circles", "contrast", "dots")),
        MaterialSymbolInfo(name = "hdr_weak", codePoint = 58354, tags = listOf("camera", "circle", "circles", "contrast", "control", "correction", "dark", "disabled")),
        MaterialSymbolInfo(name = "healing", codePoint = 58355, tags = listOf("aid", "band-aid", "bandage", "clinic", "cross", "cure", "doctor", "edit")),
        MaterialSymbolInfo(name = "hevc", codePoint = 61473, tags = listOf("abbreviation", "acronym", "alphabet", "character", "codec", "coding", "compression", "digital")),
        MaterialSymbolInfo(name = "hide_image", codePoint = 61474, tags = listOf("absence", "artwork", "blocked", "broken", "conceal", "content", "disabled", "display")),
        MaterialSymbolInfo(name = "image", codePoint = 58356, tags = listOf("add", "adjust", "album", "asset", "camera", "collection", "crop", "display")),
        MaterialSymbolInfo(name = "image_aspect_ratio", codePoint = 58357, tags = listOf("adjust", "aspect", "aspect ratio", "crop", "dimensions", "display", "format", "height")),
        MaterialSymbolInfo(name = "image_not_supported", codePoint = 61718, tags = listOf("alert", "broken", "cancel", "content", "disabled", "disallowed", "enabled", "error")),
        MaterialSymbolInfo(name = "image_search", codePoint = 58431, tags = listOf("analyze", "bing visual search", "camera search", "content search", "database search", "digital eye", "discover image", "discovery")),
        MaterialSymbolInfo(name = "incomplete_circle", codePoint = 59291, tags = listOf("active", "activity indicator", "animation", "arc", "broken circle", "busy", "chart", "circle")),
        MaterialSymbolInfo(name = "iso", codePoint = 58358, tags = listOf("add", "adjustment", "bar", "brightness", "camera", "controls", "edit", "editing")),
        MaterialSymbolInfo(name = "landscape", codePoint = 58359, tags = listOf("chart", "contour", "data", "diagram", "elevation", "environment", "geography", "graphic")),
        MaterialSymbolInfo(name = "leak_add", codePoint = 58360, tags = listOf("add", "assembly", "attach", "build", "connect", "connection", "construct", "construction")),
        MaterialSymbolInfo(name = "leak_remove", codePoint = 58361, tags = listOf("anti leak", "blocked", "cancel", "connection", "data", "delete", "disabled", "drop")),
        MaterialSymbolInfo(name = "lens", codePoint = 58362, tags = listOf("active", "angle", "badge", "basic", "centralized", "circle", "complete", "disc")),
        MaterialSymbolInfo(name = "linked_camera", codePoint = 58424, tags = listOf("attached", "camera", "capture", "chain", "connect", "connected", "connection", "device")),
        MaterialSymbolInfo(name = "logo_dev", codePoint = 60118, tags = listOf("app", "application", "brand", "build", "building", "business", "code", "coding")),
        MaterialSymbolInfo(name = "looks", codePoint = 58364, tags = listOf("accessory", "circle", "clarity", "enhancement", "eyeglasses", "eyes", "eyewear", "fashion")),
        MaterialSymbolInfo(name = "looks_3", codePoint = 58363, tags = listOf("3", "arrangement", "controls", "count", "customization", "data", "digit", "filter")),
        MaterialSymbolInfo(name = "looks_4", codePoint = 58365, tags = listOf("4", "block", "block four", "count", "design", "digit", "digit four", "element")),
        MaterialSymbolInfo(name = "looks_5", codePoint = 58366, tags = listOf("5", "browse", "digit", "discover", "enlarge", "examine", "explore", "find")),
        MaterialSymbolInfo(name = "looks_6", codePoint = 58367, tags = listOf("6", "achievement", "approval", "badge", "bookmark", "choice", "digit", "endorse")),
        MaterialSymbolInfo(name = "looks_one", codePoint = 58368, tags = listOf("1", "beginning", "competition", "count", "counting", "digit", "exclusive", "first")),
        MaterialSymbolInfo(name = "looks_two", codePoint = 58369, tags = listOf("2", "digit", "double", "eye", "eyes", "glasses", "lenses", "look")),
        MaterialSymbolInfo(name = "loupe", codePoint = 58370, tags = listOf("+", "add", "analyze", "circle", "details", "discover", "enlarge", "explore")),
        MaterialSymbolInfo(name = "mic_external_off", codePoint = 61273, tags = listOf("audio", "audio device", "audio input", "broken", "circle", "communication", "diagonal line", "disabled")),
        MaterialSymbolInfo(name = "mic_external_on", codePoint = 61274, tags = listOf("active", "audio", "broadcast", "circle", "communication", "conference", "connected", "connected mic")),
        MaterialSymbolInfo(name = "monochrome_photos", codePoint = 58371, tags = listOf("album", "black", "black and white", "camera", "collection", "digital media", "editing", "effect")),
        MaterialSymbolInfo(name = "motion_photos_auto", codePoint = 61498, tags = listOf("A", "advanced photo", "alphabet", "animation", "auto", "auto play", "automatic", "camera")),
        MaterialSymbolInfo(name = "motion_photos_off", codePoint = 59840, tags = listOf("animated", "animation", "block", "camera", "cancel", "capture", "circle", "circle with line")),
        MaterialSymbolInfo(name = "motion_photos_on", codePoint = 59841, tags = listOf("active", "animation", "camera", "capture", "circle", "content", "digital", "disabled")),
        MaterialSymbolInfo(name = "motion_photos_pause", codePoint = 61991, tags = listOf("action", "animation", "button", "camera", "capture", "circle", "control", "frame")),
        MaterialSymbolInfo(name = "motion_photos_paused", codePoint = 59842, tags = listOf("action", "animation", "button", "camera", "capture", "circle", "control", "frame")),
        MaterialSymbolInfo(name = "movie_creation", codePoint = 58372, tags = listOf("capture", "cinema", "clapperboard", "creation", "digital", "drive", "edit", "entertainment")),
        MaterialSymbolInfo(name = "movie_filter", codePoint = 58426, tags = listOf("adjust", "adjust video", "ai", "artificial", "automatic", "automation", "camera", "cinema")),
        MaterialSymbolInfo(name = "mp", codePoint = 59843, tags = listOf("adjustment", "alphabet", "audio", "audio output", "button", "character", "control", "dashboard")),
        MaterialSymbolInfo(name = "music_note", codePoint = 58373, tags = listOf("audio", "audio file", "audio icon", "audiotrack", "clef", "composition", "eighth note", "key")),
        MaterialSymbolInfo(name = "music_off", codePoint = 58432, tags = listOf("audio", "audio off", "audiotrack", "block", "blocked music", "cross out", "disable", "disabled"))
    )
}

internal val materialSymbols_image_chunk4: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "nature", codePoint = 58374, tags = listOf("biology", "bloom", "botanical", "botany", "branch", "eco", "ecology", "environment")),
        MaterialSymbolInfo(name = "nature_people", codePoint = 58375, tags = listOf("activity", "adventure", "body", "camping", "community", "environment", "exploring", "figures")),
        MaterialSymbolInfo(name = "navigate_before", codePoint = 58376, tags = listOf("angle", "arrow", "arrows", "back", "backward", "before", "caret", "carousel")),
        MaterialSymbolInfo(name = "navigate_next", codePoint = 58377, tags = listOf("advance", "angle", "arrow", "arrows", "bracket", "caret", "carousel", "chevron")),
        MaterialSymbolInfo(name = "palette", codePoint = 58378, tags = listOf("appearance", "art", "artist", "artistic", "brush", "color", "colors", "creative")),
        MaterialSymbolInfo(name = "panorama", codePoint = 58379, tags = listOf("ad", "advertisement", "advertising", "angle", "banner", "display", "elongated", "graphic")),
        MaterialSymbolInfo(name = "panorama_fish_eye", codePoint = 58380, tags = listOf("angle", "basic", "basic shape", "button", "circle", "circular", "design element", "donut")),
        MaterialSymbolInfo(name = "panorama_horizontal", codePoint = 58381, tags = listOf("angle", "aspect ratio", "camera", "composition", "display", "expand", "format", "fullscreen")),
        MaterialSymbolInfo(name = "panorama_horizontal_select", codePoint = 61280, tags = listOf("angle", "horizontal", "image", "panorama", "photo", "photography", "picture", "select")),
        MaterialSymbolInfo(name = "panorama_photosphere", codePoint = 59849, tags = listOf("360", "angle", "ar", "augmented reality", "camera", "environment", "experience", "explore")),
        MaterialSymbolInfo(name = "panorama_photosphere_select", codePoint = 59850, tags = listOf("angle", "horizontal", "image", "panorama", "photo", "photography", "photosphere", "picture")),
        MaterialSymbolInfo(name = "panorama_vertical", codePoint = 58382, tags = listOf("angle", "aspect ratio", "building", "camera", "capture", "compose", "field of view", "framing")),
        MaterialSymbolInfo(name = "panorama_vertical_select", codePoint = 61281, tags = listOf("angle", "image", "panorama", "photo", "photography", "picture", "select", "vertical")),
        MaterialSymbolInfo(name = "panorama_wide_angle", codePoint = 58383, tags = listOf("adjust", "album", "angle", "aperture", "broad", "camera", "capture", "crop")),
        MaterialSymbolInfo(name = "panorama_wide_angle_select", codePoint = 61282, tags = listOf("angle", "image", "panorama", "photo", "photography", "picture", "select", "wide")),
        MaterialSymbolInfo(name = "photo", codePoint = 58384, tags = listOf("album", "basic", "camera roll", "digital", "file", "gallery", "geometric", "graphic")),
        MaterialSymbolInfo(name = "photo_album", codePoint = 58385, tags = listOf("album", "archive", "bookmark", "browsing", "collection", "collection of photos", "digital album", "gallery")),
        MaterialSymbolInfo(name = "photo_camera", codePoint = 58386, tags = listOf("analog", "button", "camera", "capture", "circle", "device", "digital", "film")),
        MaterialSymbolInfo(name = "photo_camera_back", codePoint = 61288, tags = listOf("back", "back camera", "camera", "capture", "circle", "device", "flash", "focus")),
        MaterialSymbolInfo(name = "photo_camera_front", codePoint = 61289, tags = listOf("account", "border", "camera", "capture", "circle", "create", "create media", "face")),
        MaterialSymbolInfo(name = "photo_filter", codePoint = 58427, tags = listOf("adjust", "adjust image", "adjust photo", "ai", "artificial", "automatic", "automation", "brightness")),
        MaterialSymbolInfo(name = "photo_library", codePoint = 58387, tags = listOf("album", "archive", "assets", "browse", "catalog", "collection", "compilation", "data.")),
        MaterialSymbolInfo(name = "photo_size_select_actual", codePoint = 58418, tags = listOf("actual", "album", "basic", "camera roll", "dash", "dashed", "digital", "file")),
        MaterialSymbolInfo(name = "photo_size_select_large", codePoint = 58419, tags = listOf("adjust", "adjustments", "album", "bigger", "dash", "dashed", "edit", "editing")),
        MaterialSymbolInfo(name = "photo_size_select_small", codePoint = 58420, tags = listOf("adjust", "album", "arrangement", "compact", "condense", "dimensions", "display", "edit")),
        MaterialSymbolInfo(name = "picture_as_pdf", codePoint = 58389, tags = listOf("adobe", "adobe acrobat", "alphabet", "as", "character", "copy", "digital document", "digital file")),
        MaterialSymbolInfo(name = "portrait", codePoint = 58390, tags = listOf("account", "account icon", "accounts", "avatar", "bust", "contact", "contact icon", "face")),
        MaterialSymbolInfo(name = "raw_off", codePoint = 61519, tags = listOf("alphabet", "button", "camera", "cancel", "character", "close", "code", "data")),
        MaterialSymbolInfo(name = "raw_on", codePoint = 61520, tags = listOf("abstract", "activate", "active", "alphabet", "button", "character", "control", "device")),
        MaterialSymbolInfo(name = "receipt_long", codePoint = 61294, tags = listOf("accounting", "bill", "bill icon", "business", "check", "checkout", "details", "document")),
        MaterialSymbolInfo(name = "remove_red_eye", codePoint = 58391, tags = listOf("display", "eye", "glance", "hidden", "hidden text", "insight", "iris", "look")),
        MaterialSymbolInfo(name = "rotate_90_degrees_ccw", codePoint = 58392, tags = listOf("90", "90 degrees", "action", "adjustment", "angle", "arrow", "arrows", "ccw")),
        MaterialSymbolInfo(name = "rotate_90_degrees_cw", codePoint = 60075, tags = listOf("90", "90 degree turn", "90 degrees", "adjust", "angle", "arrow", "arrows", "ccw")),
        MaterialSymbolInfo(name = "rotate_left", codePoint = 58393, tags = listOf("action", "adjust", "around", "arrow", "back", "change", "circle", "circular arrow")),
        MaterialSymbolInfo(name = "rotate_right", codePoint = 58394, tags = listOf("action", "app", "around", "arrow", "button", "change direction", "circular", "circular arrow")),
        MaterialSymbolInfo(name = "shutter_speed", codePoint = 58429, tags = listOf("adjustment", "aperture", "aperture control", "blades", "camera", "camera controls", "capture", "circle")),
        MaterialSymbolInfo(name = "slideshow", codePoint = 58395, tags = listOf("begin", "demonstrate", "display", "entertainment", "exhibit", "film", "image sequence", "media")),
        MaterialSymbolInfo(name = "straighten", codePoint = 58396, tags = listOf("adjust", "align", "angle", "arrangement", "bend", "calibrate", "curve", "distribute")),
        MaterialSymbolInfo(name = "style", codePoint = 58397, tags = listOf("adjust", "alignment", "arrangement", "block", "booklet", "cards", "configure", "content")),
        MaterialSymbolInfo(name = "switch_camera", codePoint = 58398, tags = listOf("app", "application", "arrow", "arrows", "back camera", "camera", "camera direction", "capture")),
        MaterialSymbolInfo(name = "switch_video", codePoint = 58399, tags = listOf("arrow", "arrows", "back camera", "broadcasting", "call", "camera", "camera direction", "camera flip")),
        MaterialSymbolInfo(name = "tag_faces", codePoint = 58400, tags = listOf("add", "character", "chat", "cheerful", "circle", "communication", "emoji", "emoticon")),
        MaterialSymbolInfo(name = "texture", codePoint = 58401, tags = listOf("abstract", "appearance", "background", "bumpy", "crosshatch", "detail", "diagonal", "effect")),
        MaterialSymbolInfo(name = "thermostat_auto", codePoint = 61559, tags = listOf("A", "adjustment", "appliance", "auto", "automatic", "automation", "celsius", "circle")),
        MaterialSymbolInfo(name = "timelapse", codePoint = 58402, tags = listOf("accelerate", "adjustment", "arrow", "camera", "capture", "circle", "clock", "clockwise")),
        MaterialSymbolInfo(name = "timer", codePoint = 58405, tags = listOf("alarm", "alert", "appointment", "bell", "chronometer", "circular", "clock", "countdown")),
        MaterialSymbolInfo(name = "timer_10", codePoint = 58403, tags = listOf("10", "alarm", "alert", "bell", "camera", "circle", "circular", "clock")),
        MaterialSymbolInfo(name = "timer_3", codePoint = 58404, tags = listOf("3", "circle", "clock", "control", "countdown", "digit", "digits", "duration")),
        MaterialSymbolInfo(name = "timer_off", codePoint = 58406, tags = listOf("alarm", "alarm disabled", "alarm off", "alert", "bell", "cancel", "chronometer off", "circle")),
        MaterialSymbolInfo(name = "tonality", codePoint = 58407, tags = listOf("adjust", "audio", "audio icon", "audio settings", "circle", "control", "edit", "editing")),
        MaterialSymbolInfo(name = "transform", codePoint = 58408, tags = listOf("adjust", "alter", "anchors", "aspect ratio", "box", "change", "contract", "corners")),
        MaterialSymbolInfo(name = "tune", codePoint = 58409, tags = listOf("adjust", "adjustments", "audio", "balance", "bars", "bass", "configure", "control")),
        MaterialSymbolInfo(name = "video_camera_back", codePoint = 61567, tags = listOf("back", "camera", "capture", "electronic device", "entertainment", "film", "image", "landscape")),
        MaterialSymbolInfo(name = "video_camera_front", codePoint = 61568, tags = listOf("account", "broadcast", "camera", "capture", "communication", "face", "film", "film recording")),
        MaterialSymbolInfo(name = "video_stable", codePoint = 61569, tags = listOf("abstract", "alignment", "anti-shake", "balance", "camera", "capture", "digital", "film")),
        MaterialSymbolInfo(name = "view_comfy", codePoint = 58410, tags = listOf("arrange", "blocks", "boxes", "cells", "collection", "comfy", "content", "dashboard")),
        MaterialSymbolInfo(name = "view_compact", codePoint = 58411, tags = listOf("alignment", "arrange", "array", "blocks", "boxes", "columns", "compact", "dashboard")),
        MaterialSymbolInfo(name = "vignette", codePoint = 58421, tags = listOf("adjustment", "border", "button", "camera", "circle", "corner", "dark", "edge")),
        MaterialSymbolInfo(name = "vrpano", codePoint = 61570, tags = listOf("360", "angle", "camera", "circle", "digital", "experience", "globe", "image")),
        MaterialSymbolInfo(name = "wb_auto", codePoint = 58412, tags = listOf("A", "W", "adjust", "alphabet", "ambient light", "auto", "auto brightness", "auto light"))
    )
}

internal val materialSymbols_image_chunk5: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "wb_cloudy", codePoint = 58413, tags = listOf("air", "atmosphere", "balance", "climate", "cloud", "cloudy", "edit", "editing")),
        MaterialSymbolInfo(name = "wb_incandescent", codePoint = 58414, tags = listOf("balance", "base", "bright", "bulb", "edit", "editing", "electric", "electricity")),
        MaterialSymbolInfo(name = "wb_iridescent", codePoint = 58422, tags = listOf("adjustments", "balance", "bright", "brightness", "camera", "edit", "editing", "effects")),
        MaterialSymbolInfo(name = "wb_shade", codePoint = 59905, tags = listOf("adjust", "area", "balance", "blind", "building", "control", "cover", "curtains")),
        MaterialSymbolInfo(name = "wb_sunny", codePoint = 58416, tags = listOf("balance", "beams", "bright", "celestial", "circle", "climate", "day", "daylight")),
        MaterialSymbolInfo(name = "wb_twilight", codePoint = 57798, tags = listOf("ambient", "ambient light", "astronomy", "atmosphere", "balance", "calm", "celestial", "darkness"))
    )
}

internal val materialSymbols_image_category: MaterialSymbolCategory by lazy(LazyThreadSafetyMode.NONE) {
    MaterialSymbolCategory(
        key = "image",
        icons = buildList {
            addAll(materialSymbols_image_chunk1)
            addAll(materialSymbols_image_chunk2)
            addAll(materialSymbols_image_chunk3)
            addAll(materialSymbols_image_chunk4)
            addAll(materialSymbols_image_chunk5)
        }
    )
}
