package com.example.itemmanagement.ui.components

import kotlin.LazyThreadSafetyMode

internal val materialSymbols_action_chunk1: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "123", codePoint = 60301, tags = listOf("1", "123", "2", "3", "arrange", "arrow", "ascending", "ascending sort")),
        MaterialSymbolInfo(name = "3d_rotation", codePoint = 59469, tags = listOf("3", "3d", "D", "alphabet", "angle", "application", "arrow", "arrows")),
        MaterialSymbolInfo(name = "abc", codePoint = 60308, tags = listOf("absent", "alphabet", "bare", "blank", "character", "clean", "clear", "empty")),
        MaterialSymbolInfo(name = "accessibility", codePoint = 59470, tags = listOf("access", "accessibility", "accessible", "aid", "assistance", "barrier-free", "body", "disability")),
        MaterialSymbolInfo(name = "accessibility_new", codePoint = 59692, tags = listOf("access", "accessibility", "accessibility icon", "accessibility statement", "accessible", "assistance", "barrier-free", "body")),
        MaterialSymbolInfo(name = "accessible", codePoint = 59668, tags = listOf("accessibility", "accessible", "assistance", "body", "disability", "disabled", "easy access", "facilities")),
        MaterialSymbolInfo(name = "accessible_forward", codePoint = 59700, tags = listOf("accessibility", "accessible", "arrow", "arrow right", "body", "continue", "direction", "figure")),
        MaterialSymbolInfo(name = "account_balance", codePoint = 59471, tags = listOf("account", "accounting", "balance", "bank", "banking", "bill", "building", "business")),
        MaterialSymbolInfo(name = "account_balance_wallet", codePoint = 59472, tags = listOf("account", "assets", "balance", "bank", "banking", "bill", "budget", "card")),
        MaterialSymbolInfo(name = "account_box", codePoint = 59473, tags = listOf("account", "account icon", "accounts", "avatar", "box", "bust", "contact", "contact icon")),
        MaterialSymbolInfo(name = "account_circle", codePoint = 59475, tags = listOf("account", "account circle", "account details", "account icon", "account management", "account settings", "avatar", "bust")),
        MaterialSymbolInfo(name = "add_card", codePoint = 60294, tags = listOf("+", "account", "add", "add card", "add credit card", "add debit card", "add payment", "banking")),
        MaterialSymbolInfo(name = "add_home", codePoint = 63723, tags = listOf("accommodation", "add", "append", "architecture", "attach", "building", "button", "construction")),
        MaterialSymbolInfo(name = "add_shopping_cart", codePoint = 59476, tags = listOf("acquisition", "add", "add to cart", "basket", "buy", "card", "cart", "cash")),
        MaterialSymbolInfo(name = "add_task", codePoint = 62010, tags = listOf("+", "action", "add", "approve", "arc", "assignment", "check", "checkmark")),
        MaterialSymbolInfo(name = "add_to_drive", codePoint = 58972, tags = listOf("account", "add", "app", "application", "archive", "backup", "cloud", "cloud computing")),
        MaterialSymbolInfo(name = "addchart", codePoint = 61244, tags = listOf("+", "add", "addchart", "analysis", "analytics", "bar", "bar chart", "bars")),
        MaterialSymbolInfo(name = "admin_panel_settings", codePoint = 61245, tags = listOf("access", "account", "adjust", "admin", "administrator", "avatar", "certified", "cog")),
        MaterialSymbolInfo(name = "ads_click", codePoint = 59234, tags = listOf("ads", "ads click", "advertisement", "analytics", "arrow", "browser", "button", "call to action")),
        MaterialSymbolInfo(name = "alarm", codePoint = 59477, tags = listOf("access", "adjust", "alarm", "alert", "appointment", "bell", "calendar", "circle")),
        MaterialSymbolInfo(name = "alarm_add", codePoint = 59478, tags = listOf("+", "add", "add alarm", "alarm", "alert", "app", "appointment", "audio")),
        MaterialSymbolInfo(name = "alarm_off", codePoint = 59479, tags = listOf("alarm", "alarm off", "alert", "bell", "bell disabled", "bell muted", "bell off", "check")),
        MaterialSymbolInfo(name = "alarm_on", codePoint = 59480, tags = listOf("activated", "active", "alarm", "alert", "audible", "awake", "bell", "buzzing")),
        MaterialSymbolInfo(name = "all_inbox", codePoint = 59775, tags = listOf("Inbox", "all", "all mail", "archive", "box", "bundle", "collection", "communication")),
        MaterialSymbolInfo(name = "all_out", codePoint = 59659, tags = listOf("abstract", "all", "arrows", "aspect ratio", "bounding box", "box", "circle", "corners")),
        MaterialSymbolInfo(name = "analytics", codePoint = 61246, tags = listOf("analysis", "analytics", "assessment", "bar", "bar chart", "bars", "business", "chart")),
        MaterialSymbolInfo(name = "anchor", codePoint = 61901, tags = listOf("anchor", "attachment", "base", "boat", "chain", "connection", "fishing", "fixed")),
        MaterialSymbolInfo(name = "android", codePoint = 59481, tags = listOf("ai", "android", "app development", "artificial intelligence", "automation", "bugdroid", "character", "code")),
        MaterialSymbolInfo(name = "announcement", codePoint = 59482, tags = listOf("!", "alert", "announcement", "attention", "broadcast", "bubble", "caution", "chat")),
        MaterialSymbolInfo(name = "api", codePoint = 61879, tags = listOf("access", "api", "application", "backend", "bridge", "cloud", "code", "coding")),
        MaterialSymbolInfo(name = "app_blocking", codePoint = 61247, tags = listOf("Android", "OS", "access denied", "app", "app blocking", "application", "ban", "barrier")),
        MaterialSymbolInfo(name = "app_shortcut", codePoint = 60132, tags = listOf("Android", "OS", "access", "app", "application", "broadcast", "cast", "casting")),
        MaterialSymbolInfo(name = "arrow_circle_down", codePoint = 61825, tags = listOf("arrow", "button", "circle", "collapse", "contained", "control", "cursor", "direction")),
        MaterialSymbolInfo(name = "arrow_circle_left", codePoint = 60071, tags = listOf("arrow", "back", "button", "circle", "circle arrow", "circular", "circular arrow", "contained")),
        MaterialSymbolInfo(name = "arrow_circle_right", codePoint = 60074, tags = listOf("app", "arrow", "arrow in circle", "button", "circle", "circular arrow", "continue", "control")),
        MaterialSymbolInfo(name = "arrow_circle_up", codePoint = 61826, tags = listOf("action", "arrow", "button", "circle", "circular arrow", "control", "data transfer", "direction")),
        MaterialSymbolInfo(name = "arrow_outward", codePoint = 63694, tags = listOf("access", "app", "application", "arrow", "arrows", "components", "connection", "diagonal")),
        MaterialSymbolInfo(name = "arrow_right_alt", codePoint = 59713, tags = listOf("access", "alt", "arrow", "arrow symbol", "arrows", "button", "carat", "caret")),
        MaterialSymbolInfo(name = "article", codePoint = 61250, tags = listOf("archive", "article", "cloud", "content", "contract", "create", "data", "doc")),
        MaterialSymbolInfo(name = "aspect_ratio", codePoint = 59483, tags = listOf("adjust", "aspect", "aspect ratio", "crop", "custom", "dash", "dashed", "dimensions")),
        MaterialSymbolInfo(name = "assessment", codePoint = 59484, tags = listOf("add", "analysis", "analytics", "assessment", "bar", "bar chart", "bars", "business")),
        MaterialSymbolInfo(name = "assignment", codePoint = 59485, tags = listOf("agenda", "assignment", "checklist", "class", "clipboard", "course", "deliverable", "doc")),
        MaterialSymbolInfo(name = "assignment_ind", codePoint = 59486, tags = listOf("account", "apply", "assignment", "badge", "card", "clipboard", "data", "details")),
        MaterialSymbolInfo(name = "assignment_late", codePoint = 59487, tags = listOf("!", "alert", "assignment", "assignment late", "attention", "calendar", "caution", "clipboard")),
        MaterialSymbolInfo(name = "assignment_return", codePoint = 59488, tags = listOf("approval", "arrow", "assignment", "back", "checklist", "checkmark", "clipboard", "completed")),
        MaterialSymbolInfo(name = "assignment_returned", codePoint = 59489, tags = listOf("arrow", "assignment", "assignment returned", "business", "checking", "clipboard", "complete", "contract")),
        MaterialSymbolInfo(name = "assignment_turned_in", codePoint = 59490, tags = listOf("accepted", "approve", "approved", "assignment", "box", "check", "checklist", "checkmark")),
        MaterialSymbolInfo(name = "assured_workload", codePoint = 60271, tags = listOf("account", "activity", "approved", "assignment", "assurance", "assured", "authenticated", "authorized")),
        MaterialSymbolInfo(name = "autorenew", codePoint = 59491, tags = listOf("action", "around", "arrow", "arrows", "autorenew", "cache", "cached", "circle")),
        MaterialSymbolInfo(name = "backup", codePoint = 59492, tags = listOf("archive", "arrow", "backup", "cloud", "computing", "copy", "data", "database")),
        MaterialSymbolInfo(name = "backup_table", codePoint = 61251, tags = listOf("archive", "backup", "cloud", "columns", "copy", "data", "database", "document")),
        MaterialSymbolInfo(name = "balance", codePoint = 60150, tags = listOf("balance", "compare", "compare and contrast", "court", "courthouse", "decision", "equal", "equality")),
        MaterialSymbolInfo(name = "batch_prediction", codePoint = 61685, tags = listOf("ai", "algorithms", "analysis", "artificial intelligence", "automated", "batch", "bulb", "bulk")),
        MaterialSymbolInfo(name = "book", codePoint = 59493, tags = listOf("academic", "academy", "book", "book icon", "bookmark", "class", "class icon", "course")),
        MaterialSymbolInfo(name = "book_online", codePoint = 61975, tags = listOf("Android", "OS", "access", "admission", "app", "appointment", "barcode", "book")),
        MaterialSymbolInfo(name = "bookmark", codePoint = 59494, tags = listOf("app", "archive", "article", "book", "bookmark", "browser", "collection", "content")),
        MaterialSymbolInfo(name = "bookmark_add", codePoint = 58776, tags = listOf("+", "add", "archive", "bookmark", "button", "collection", "document", "favorite")),
        MaterialSymbolInfo(name = "bookmark_added", codePoint = 58777, tags = listOf("add", "added", "approve", "bookmark", "check", "complete", "document", "done")),
        MaterialSymbolInfo(name = "bookmark_border", codePoint = 59495, tags = listOf("app", "archive", "article", "book", "bookmark", "border", "browser", "collection")),
        MaterialSymbolInfo(name = "bookmark_remove", codePoint = 58778, tags = listOf("action", "bookmark", "button", "clear", "control", "delete", "document", "erase"))
    )
}

internal val materialSymbols_action_chunk2: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "bookmarks", codePoint = 59787, tags = listOf("bookmark", "bookmarks", "browser", "collection", "document", "favorite", "favorites", "file")),
        MaterialSymbolInfo(name = "browse_gallery", codePoint = 60369, tags = listOf("album", "artwork", "assets", "browse", "browse gallery", "catalog", "clock", "collection")),
        MaterialSymbolInfo(name = "bug_report", codePoint = 59496, tags = listOf("alert", "animal", "application", "bug", "case", "circle", "communicate", "complaint")),
        MaterialSymbolInfo(name = "build", codePoint = 59497, tags = listOf("adjust", "adjustment", "build", "building", "configuration", "construction", "control", "engineering")),
        MaterialSymbolInfo(name = "build_circle", codePoint = 61256, tags = listOf("adjust", "build", "circle", "cog", "configuration", "construct", "contained", "create")),
        MaterialSymbolInfo(name = "cached", codePoint = 59498, tags = listOf("access", "around", "arrows", "cache", "cached", "circle", "cloud", "connection")),
        MaterialSymbolInfo(name = "calendar_month", codePoint = 60364, tags = listOf("agenda", "appointment", "button", "calendar", "clock", "date", "day", "duration")),
        MaterialSymbolInfo(name = "calendar_today", codePoint = 59701, tags = listOf("agenda", "appointment", "booking", "calendar", "calendaricon", "calendartoday", "daily", "date")),
        MaterialSymbolInfo(name = "calendar_view_day", codePoint = 59702, tags = listOf("activity", "agenda", "appointment", "appointments", "calendar", "column", "date", "day")),
        MaterialSymbolInfo(name = "calendar_view_month", codePoint = 61415, tags = listOf("agenda", "appointments", "arrangement", "block", "booking", "box", "calendar", "date")),
        MaterialSymbolInfo(name = "calendar_view_week", codePoint = 61416, tags = listOf("appointments", "arrangement", "calendar", "columns", "date", "dates", "day", "days")),
        MaterialSymbolInfo(name = "camera_enhance", codePoint = 59644, tags = listOf("adjustment", "ai", "aperture", "artificial", "automatic", "automation", "bright", "button")),
        MaterialSymbolInfo(name = "cancel_schedule_send", codePoint = 59961, tags = listOf("abort", "action", "button", "cancel", "clear", "command", "communication", "delete")),
        MaterialSymbolInfo(name = "card_giftcard", codePoint = 59638, tags = listOf("account", "balance", "bill", "bonus", "bonus points", "bow", "buy", "card")),
        MaterialSymbolInfo(name = "card_membership", codePoint = 59639, tags = listOf("access", "account", "bill", "bookmark", "card", "cash", "certificate", "club")),
        MaterialSymbolInfo(name = "card_travel", codePoint = 59640, tags = listOf("accessory", "bag", "baggage", "bill", "briefcase", "business", "card", "carry")),
        MaterialSymbolInfo(name = "change_history", codePoint = 59499, tags = listOf("audit trail", "change", "change history", "chronology", "development", "edits", "events", "evolution")),
        MaterialSymbolInfo(name = "check_circle", codePoint = 59500, tags = listOf("accept", "approval", "approve", "check", "checkmark", "circle", "complete", "completion")),
        MaterialSymbolInfo(name = "check_circle_outline", codePoint = 59693, tags = listOf("accept", "approval", "approve", "check", "checkmark", "circle", "complete", "completion")),
        MaterialSymbolInfo(name = "chrome_reader_mode", codePoint = 59501, tags = listOf("article", "book", "bookmark", "browser", "chrome", "content", "document", "layout")),
        MaterialSymbolInfo(name = "circle_notifications", codePoint = 59796, tags = listOf("active", "activity", "alarm", "alert", "alert bell", "alert sound", "announcements", "attention")),
        MaterialSymbolInfo(name = "class", codePoint = 59502, tags = listOf("academic", "academy", "archive", "book", "book icon", "bookmark", "class", "class icon")),
        MaterialSymbolInfo(name = "close_fullscreen", codePoint = 61903, tags = listOf("action", "arrow", "arrows", "arrows inward", "box", "button", "close", "collapse")),
        MaterialSymbolInfo(name = "code", codePoint = 59503, tags = listOf("algorithm", "application", "backend", "brackets", "build", "code", "coding", "commands")),
        MaterialSymbolInfo(name = "code_off", codePoint = 58611, tags = listOf("angle brackets", "block", "brackets", "cancel", "code", "coding", "css", "deactivate")),
        MaterialSymbolInfo(name = "comment_bank", codePoint = 59982, tags = listOf("archive", "bank", "bookmark", "bubble", "cchat", "chat", "collection", "comment")),
        MaterialSymbolInfo(name = "commit", codePoint = 60149, tags = listOf("accomplish", "bind", "branch", "changes", "circle", "code", "commit", "confirm")),
        MaterialSymbolInfo(name = "commute", codePoint = 59712, tags = listOf("automobile", "car", "commute", "destination", "direction", "directions", "driving", "guidance")),
        MaterialSymbolInfo(name = "compare_arrows", codePoint = 59669, tags = listOf("alternative", "arrow", "arrows", "balance", "bidirectional", "change", "choices", "collide")),
        MaterialSymbolInfo(name = "compress", codePoint = 59725, tags = listOf("adjust size", "arrow", "arrows", "collide", "compact", "compress", "compress file", "corners")),
        MaterialSymbolInfo(name = "contact_page", codePoint = 61998, tags = listOf("account", "address book", "avatar", "book", "business", "circle", "contact", "data")),
        MaterialSymbolInfo(name = "contact_support", codePoint = 59724, tags = listOf("?", "ask", "assistance", "bubble", "bubble icon", "chat", "chat bubble", "chatbot")),
        MaterialSymbolInfo(name = "contactless", codePoint = 60017, tags = listOf("banking", "bluetooth", "card reader", "cash", "commerce", "connect", "connection", "connectivity")),
        MaterialSymbolInfo(name = "copyright", codePoint = 59660, tags = listOf("agreement", "alphabet", "attribution", "brand", "c", "character", "circle", "copyright")),
        MaterialSymbolInfo(name = "credit_card", codePoint = 59504, tags = listOf("account", "account information", "amex", "balance", "bank", "banking", "bill", "buy")),
        MaterialSymbolInfo(name = "credit_card_off", codePoint = 58612, tags = listOf("banking", "bill", "blocked", "broken", "cancelled", "card", "cash", "coin")),
        MaterialSymbolInfo(name = "css", codePoint = 60307, tags = listOf("alphabet", "brackets", "browser", "cascading stylesheets", "character", "code", "coding", "computer language")),
        MaterialSymbolInfo(name = "currency_exchange", codePoint = 60272, tags = listOf("360", "around", "arrow", "arrows", "banking", "buy", "cash", "coin")),
        MaterialSymbolInfo(name = "dangerous", codePoint = 59802, tags = listOf("alarming", "alert", "attention", "be careful", "broken", "caution", "critical", "danger")),
        MaterialSymbolInfo(name = "dashboard", codePoint = 59505, tags = listOf("add", "administration", "analytics", "cards", "chart", "circle", "control", "dashboard")),
        MaterialSymbolInfo(name = "dashboard_customize", codePoint = 59803, tags = listOf("adjust", "arrange", "blocks", "boxes", "cards", "change", "configure", "control")),
        MaterialSymbolInfo(name = "data_exploration", codePoint = 59247, tags = listOf("analysis", "analytics", "arrow", "bi", "business intelligence", "chart", "curve", "dashboard")),
        MaterialSymbolInfo(name = "data_thresholding", codePoint = 60319, tags = listOf("analysis", "chart", "configuration", "controls", "criteria", "data", "data analysis", "data control")),
        MaterialSymbolInfo(name = "date_range", codePoint = 59670, tags = listOf("agenda", "appointment", "booking", "calendar", "calendar grid", "calendar picker", "calendar view", "choose date")),
        MaterialSymbolInfo(name = "delete", codePoint = 59506, tags = listOf("action", "basket", "bin", "can", "cancel", "clean up", "clear", "control")),
        MaterialSymbolInfo(name = "delete_forever", codePoint = 59691, tags = listOf("action", "archive", "bin", "button", "can", "cancel", "clean", "clear")),
        MaterialSymbolInfo(name = "delete_outline", codePoint = 59694, tags = listOf("action", "basket", "bin", "can", "cancel", "clean up", "clear", "control")),
        MaterialSymbolInfo(name = "density_large", codePoint = 60329, tags = listOf("bars", "block", "collapse", "density", "density large", "display", "expand", "horizontal")),
        MaterialSymbolInfo(name = "density_medium", codePoint = 60318, tags = listOf("adjust", "arrangement", "bars", "compact", "content density", "default", "density", "density medium")),
        MaterialSymbolInfo(name = "density_small", codePoint = 60328, tags = listOf("compact", "condensed", "dense", "density", "horizontal", "horizontal lines", "layout", "less")),
        MaterialSymbolInfo(name = "description", codePoint = 59507, tags = listOf("article", "attributes", "content", "data", "description", "details", "doc", "document")),
        MaterialSymbolInfo(name = "disabled_by_default", codePoint = 62000, tags = listOf("access denied", "alert", "blocked", "box", "by", "cancel", "caution", "clear")),
        MaterialSymbolInfo(name = "disabled_visible", codePoint = 59246, tags = listOf("accessibility", "block view", "cancel", "close", "control", "disabled", "excluded", "exit")),
        MaterialSymbolInfo(name = "display_settings", codePoint = 60311, tags = listOf("Android", "OS", "adjustments", "application", "brightness", "change", "chrome", "cog")),
        MaterialSymbolInfo(name = "dns", codePoint = 59509, tags = listOf("abstract", "address", "administration", "bars", "circles", "communication", "configuration", "connection")),
        MaterialSymbolInfo(name = "done", codePoint = 59510, tags = listOf("DISABLE_IOS", "accepted", "accomplished", "acknowledgement", "agree", "approval", "approve", "approved")),
        MaterialSymbolInfo(name = "done_all", codePoint = 59511, tags = listOf("achievement", "all", "all done", "approval", "approve", "approved", "check", "checked")),
        MaterialSymbolInfo(name = "done_outline", codePoint = 59695, tags = listOf("accepted", "achievement", "agreement", "all", "approval", "approve", "approved", "check")),
        MaterialSymbolInfo(name = "donut_large", codePoint = 59671, tags = listOf("activity", "activity indicator", "analytics", "chart", "circle", "complete", "completed", "data")),
        MaterialSymbolInfo(name = "donut_small", codePoint = 59672, tags = listOf("analytics", "chart", "circle", "circular", "dashboard", "data", "diagram", "donut"))
    )
}

internal val materialSymbols_action_chunk3: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "drag_indicator", codePoint = 59717, tags = listOf("action", "app", "application", "circles", "column", "components", "control", "design")),
        MaterialSymbolInfo(name = "dynamic_form", codePoint = 61887, tags = listOf("adaptable", "application", "bolt", "changing", "choices", "code", "configurations", "content")),
        MaterialSymbolInfo(name = "edit_calendar", codePoint = 59202, tags = listOf("agenda", "annotate", "appointment", "booking", "calendar", "change", "compose", "create")),
        MaterialSymbolInfo(name = "edit_off", codePoint = 59728, tags = listOf("blocked", "can't edit", "compose", "create", "diagonal line", "disabled", "disabled edit", "disallowed")),
        MaterialSymbolInfo(name = "eject", codePoint = 59643, tags = listOf("action", "arrow", "audio", "bar", "button", "command", "control", "device")),
        MaterialSymbolInfo(name = "euro_symbol", codePoint = 59686, tags = listOf("banking", "bill", "business", "buy", "card", "cash", "coin", "commerce")),
        MaterialSymbolInfo(name = "event", codePoint = 59512, tags = listOf("add", "add event", "add invitation", "add to calendar", "agenda", "appointment", "booking", "calendar")),
        MaterialSymbolInfo(name = "event_repeat", codePoint = 60283, tags = listOf("agenda", "always", "appointment", "around", "calendar", "constant", "continuous", "cycle")),
        MaterialSymbolInfo(name = "event_seat", codePoint = 59651, tags = listOf("allocation", "arrangement", "assign", "assigned", "available", "booking", "chair", "choice")),
        MaterialSymbolInfo(name = "exit_to_app", codePoint = 59513, tags = listOf("abandon", "access", "account", "app", "application", "arrow", "block", "box")),
        MaterialSymbolInfo(name = "expand", codePoint = 59727, tags = listOf("arrow", "arrows", "aspect ratio", "bigger", "compress", "content", "corner", "diagonal")),
        MaterialSymbolInfo(name = "explore", codePoint = 59514, tags = listOf("adventure", "browse", "compass", "curiosity", "destination", "direction", "discover", "discovery")),
        MaterialSymbolInfo(name = "explore_off", codePoint = 59816, tags = listOf("adventure off", "compass", "compass blocked", "compass off", "destination", "direction", "directions off", "disable exploration")),
        MaterialSymbolInfo(name = "extension", codePoint = 59515, tags = listOf("app", "area", "basic", "block", "border", "boundary", "box", "container")),
        MaterialSymbolInfo(name = "extension_off", codePoint = 58613, tags = listOf("add-on", "app", "blocked", "broken", "cross", "crossed out", "deactivate", "delete")),
        MaterialSymbolInfo(name = "face", codePoint = 59516, tags = listOf("access", "account", "authentication", "authorized", "biometric", "biometric scan", "emoji", "eyes")),
        MaterialSymbolInfo(name = "fact_check", codePoint = 61637, tags = listOf("accuracy", "accurate", "approval", "approve", "audit", "authentic", "authenticity", "certification")),
        MaterialSymbolInfo(name = "favorite", codePoint = 59517, tags = listOf("affection", "appreciate", "appreciation", "bookmark", "border", "button", "collection", "data")),
        MaterialSymbolInfo(name = "favorite_border", codePoint = 59518, tags = listOf("affection", "appreciation", "bookmark", "border", "button", "collection", "data", "empty")),
        MaterialSymbolInfo(name = "fax", codePoint = 60120, tags = listOf("apparatus", "appliance", "business", "communication", "data", "device", "document", "electronic")),
        MaterialSymbolInfo(name = "feedback", codePoint = 59519, tags = listOf("!", "alert", "announcement", "attention", "broadcast", "caution", "chat", "chat bubble")),
        MaterialSymbolInfo(name = "file_present", codePoint = 59918, tags = listOf("business", "clip", "collaboration", "communication", "conference", "content", "data", "display")),
        MaterialSymbolInfo(name = "filter_alt", codePoint = 61263, tags = listOf("adjust", "arrange", "choose", "control", "customize", "data", "edit", "filter")),
        MaterialSymbolInfo(name = "filter_alt_off", codePoint = 60210, tags = listOf("alt", "clear criteria", "clear filter", "clear selection", "data filter", "data options", "disable filter", "disabled")),
        MaterialSymbolInfo(name = "find_in_page", codePoint = 59520, tags = listOf("content search", "data", "doc", "document", "document icon", "document search", "drive", "file")),
        MaterialSymbolInfo(name = "find_replace", codePoint = 59521, tags = listOf("action", "application", "around", "arrows", "button", "command", "content", "control")),
        MaterialSymbolInfo(name = "fingerprint", codePoint = 59661, tags = listOf("access", "authentication", "authorized", "biometric", "circles", "confirm", "curves", "data")),
        MaterialSymbolInfo(name = "fit_screen", codePoint = 59920, tags = listOf("adjust", "arrows", "aspect ratio", "boundary", "box", "corners", "diagonal arrows", "display")),
        MaterialSymbolInfo(name = "flaky", codePoint = 61264, tags = listOf("actions", "app menu", "approve", "check", "close", "close menu", "collapse", "collapsed menu")),
        MaterialSymbolInfo(name = "flight_land", codePoint = 59652, tags = listOf("air", "aircraft", "airplane", "airplanes", "airport", "arrival", "arrivals", "arriving")),
        MaterialSymbolInfo(name = "flight_takeoff", codePoint = 59653, tags = listOf("air", "air transport", "air travel", "aircraft", "airplane", "airplanes", "airport", "arrival")),
        MaterialSymbolInfo(name = "flip_to_back", codePoint = 59522, tags = listOf("arrange", "arrangement", "back", "bring forward", "bring to front", "dash", "dashed", "depth")),
        MaterialSymbolInfo(name = "flip_to_front", codePoint = 59523, tags = listOf("arrange", "arrangement", "ascend", "back", "bring forward", "bring to top", "card", "dash")),
        MaterialSymbolInfo(name = "flutter_dash", codePoint = 57355, tags = listOf("abstract", "animal", "app", "app development", "application", "bird", "brand", "cartoon")),
        MaterialSymbolInfo(name = "free_cancellation", codePoint = 59208, tags = listOf("abort", "approve", "back out", "block", "calendar", "cancel", "cancellation", "check")),
        MaterialSymbolInfo(name = "g_translate", codePoint = 59687, tags = listOf("a icon", "alphabet", "babel", "communication", "convert language", "dictionary", "different languages", "emblem")),
        MaterialSymbolInfo(name = "gavel", codePoint = 59662, tags = listOf("agreement", "attorney", "auction", "authority", "command", "contract", "court", "courtroom")),
        MaterialSymbolInfo(name = "generating_tokens", codePoint = 59209, tags = listOf("access", "ai", "algorithm", "api", "artificial", "artificial intelligence", "automatic", "automation")),
        MaterialSymbolInfo(name = "get_app", codePoint = 59524, tags = listOf("acquire", "action", "app", "application", "archive", "arrow", "arrows", "bar")),
        MaterialSymbolInfo(name = "gif", codePoint = 59656, tags = listOf("abbreviation", "alphabet", "animated", "animation", "bitmap", "box", "character", "clip")),
        MaterialSymbolInfo(name = "gif_box", codePoint = 59299, tags = listOf("add", "alphabet", "animated", "animation", "bitmap", "box", "character", "chat")),
        MaterialSymbolInfo(name = "grade", codePoint = 59525, tags = listOf("add to favorite", "bookmark", "border", "empty", "empty star", "favorite", "five pointed star", "five points")),
        MaterialSymbolInfo(name = "grading", codePoint = 59983, tags = listOf("approved", "assess", "check", "checklist", "complete", "document", "done", "evaluation")),
        MaterialSymbolInfo(name = "group_work", codePoint = 59526, tags = listOf("alliance", "assembly", "association", "avatars", "business", "circular", "collaboration", "collective")),
        MaterialSymbolInfo(name = "help", codePoint = 59527, tags = listOf("?", "about", "answer", "assistance", "button", "circle", "circular", "documentation")),
        MaterialSymbolInfo(name = "help_center", codePoint = 61888, tags = listOf("?", "advice", "aid", "ask", "assistance", "center", "circle", "customer service")),
        MaterialSymbolInfo(name = "help_outline", codePoint = 59645, tags = listOf("?", "about", "answer", "assistance", "button", "circle", "circular", "documentation")),
        MaterialSymbolInfo(name = "hide_source", codePoint = 61475, tags = listOf("access", "circle", "concealment", "confidential", "control", "disabled", "enabled", "eye")),
        MaterialSymbolInfo(name = "highlight_alt", codePoint = 61266, tags = listOf("alt", "angle", "area selection", "arrow", "bounding box", "box", "choose", "click")),
        MaterialSymbolInfo(name = "highlight_off", codePoint = 59528, tags = listOf("abort", "action", "block", "button", "cancel", "circle", "clear", "close")),
        MaterialSymbolInfo(name = "history", codePoint = 59529, tags = listOf("activity", "arrow", "back", "backup", "backwards", "circular", "clear", "clock")),
        MaterialSymbolInfo(name = "history_toggle_off", codePoint = 61821, tags = listOf("activity", "clock", "control", "dash", "dashed", "date", "deactivate", "disable")),
        MaterialSymbolInfo(name = "hls", codePoint = 60298, tags = listOf("alphabet", "broadcast", "broadcasting", "character", "communication", "connectivity", "content", "data")),
        MaterialSymbolInfo(name = "hls_off", codePoint = 60300, tags = listOf("alphabet", "character", "connection", "cross", "develop", "developer", "diagonal", "disable")),
        MaterialSymbolInfo(name = "home", codePoint = 59530, tags = listOf("abode", "address", "app", "application--house", "architecture", "beginning", "building", "button")),
        MaterialSymbolInfo(name = "horizontal_split", codePoint = 59719, tags = listOf("arrangement", "bars", "content organization", "display", "display options", "divide", "double panel", "dual view")),
        MaterialSymbolInfo(name = "hotel_class", codePoint = 59203, tags = listOf("accommodation", "achievement", "bed", "booking", "bookmark", "building", "class", "comfort")),
        MaterialSymbolInfo(name = "hourglass_disabled", codePoint = 61267, tags = listOf("angled line", "circle", "clock", "complete", "countdown", "cross out", "delay", "diagonal line")),
        MaterialSymbolInfo(name = "hourglass_empty", codePoint = 59531, tags = listOf("abstract", "clock", "countdown", "delay", "duration", "empty", "full", "future")),
        MaterialSymbolInfo(name = "hourglass_full", codePoint = 59532, tags = listOf("antique", "classic", "countdown", "delay", "duration", "elapsed", "empty", "flow"))
    )
}

internal val materialSymbols_action_chunk4: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "html", codePoint = 60286, tags = listOf("alphabet", "angle brackets", "brackets", "character", "code", "coding", "computer", "computing")),
        MaterialSymbolInfo(name = "http", codePoint = 59650, tags = listOf("access", "address", "address bar", "alphabet", "browser", "character", "client", "communication")),
        MaterialSymbolInfo(name = "https", codePoint = 59533, tags = listOf("access", "authentication", "authorization", "browser", "closed", "confidential", "connection", "data")),
        MaterialSymbolInfo(name = "important_devices", codePoint = 59666, tags = listOf("Android", "OS", "access", "communication", "computer", "connected", "connection", "critical")),
        MaterialSymbolInfo(name = "info", codePoint = 59534, tags = listOf("about", "alert", "announcement", "assistance", "circle", "content", "data", "details")),
        MaterialSymbolInfo(name = "input", codePoint = 59536, tags = listOf("accept", "apply", "approve", "arrow", "box", "button", "check", "circle")),
        MaterialSymbolInfo(name = "install_desktop", codePoint = 60273, tags = listOf("Android", "OS", "add", "app", "application", "chrome", "computer", "computing")),
        MaterialSymbolInfo(name = "install_mobile", codePoint = 60274, tags = listOf("Android", "OS", "app", "app install", "app promo", "arrow", "arrows", "cell")),
        MaterialSymbolInfo(name = "integration_instructions", codePoint = 61268, tags = listOf("automation", "brackets", "build", "clipboard", "code", "coding", "combine", "connect")),
        MaterialSymbolInfo(name = "invert_colors", codePoint = 59537, tags = listOf("accessibility", "accessibility settings", "adjust", "adjust colors", "appearance", "button", "change", "color inversion")),
        MaterialSymbolInfo(name = "javascript", codePoint = 60284, tags = listOf("alphabet", "back end", "brackets", "character", "code", "coding", "computer", "css")),
        MaterialSymbolInfo(name = "join_full", codePoint = 60139, tags = listOf("attend", "broadcast", "call", "circle", "collaboration", "combine", "command", "conference")),
        MaterialSymbolInfo(name = "join_inner", codePoint = 60148, tags = listOf("circle", "combine", "combine data", "combine icon", "command", "connect", "connect data", "connection icon")),
        MaterialSymbolInfo(name = "join_left", codePoint = 60146, tags = listOf("access", "arrow", "branch", "circle", "combine", "command", "connect", "connection")),
        MaterialSymbolInfo(name = "join_right", codePoint = 60138, tags = listOf("align right", "alignment", "arrow", "association", "chain link", "circle", "combining", "command")),
        MaterialSymbolInfo(name = "label", codePoint = 59538, tags = listOf("angled shape", "badge", "bookmark", "category", "classification", "corner", "designation", "detail")),
        MaterialSymbolInfo(name = "label_important", codePoint = 59703, tags = listOf("angled", "bookmark", "categorization", "categorize", "chevron", "corner", "data", "favorite")),
        MaterialSymbolInfo(name = "label_off", codePoint = 59830, tags = listOf("angles", "badge off", "deactivate label", "disable", "disable label", "disabled", "enabled", "favorite")),
        MaterialSymbolInfo(name = "language", codePoint = 59540, tags = listOf("announcement", "bubble", "caption", "chat", "communicate", "communication", "dialogue", "discussion")),
        MaterialSymbolInfo(name = "launch", codePoint = 59541, tags = listOf("access", "action", "app", "application", "arrow", "box", "button", "components")),
        MaterialSymbolInfo(name = "leaderboard", codePoint = 61964, tags = listOf("achievement", "achievements", "analytics", "bar", "bar chart", "bars", "best", "chart")),
        MaterialSymbolInfo(name = "lightbulb", codePoint = 57584, tags = listOf("alert", "announcement", "bright", "bulb", "concept", "creativity", "disabled", "education")),
        MaterialSymbolInfo(name = "lightbulb_circle", codePoint = 60414, tags = listOf("alert", "announcement", "bright", "bulb", "button", "circle", "circular", "contained")),
        MaterialSymbolInfo(name = "line_style", codePoint = 59673, tags = listOf("adjust", "alignment", "bullet points", "content", "customize", "dash", "document", "document editing")),
        MaterialSymbolInfo(name = "line_weight", codePoint = 59674, tags = listOf("adjust", "bars", "content", "different sizes", "document", "editing", "editor", "file")),
        MaterialSymbolInfo(name = "list", codePoint = 59542, tags = listOf("agenda", "bullet points", "bulleted list", "catalog", "checklist", "content list", "directory", "enumeration")),
        MaterialSymbolInfo(name = "lock", codePoint = 59543, tags = listOf("access", "authentication", "authorization", "browser", "closed", "confidential", "connection", "data")),
        MaterialSymbolInfo(name = "lock_clock", codePoint = 61271, tags = listOf("access", "access control", "access time", "clock", "control", "controlled access", "date", "delay")),
        MaterialSymbolInfo(name = "lock_open", codePoint = 59544, tags = listOf("access", "action open", "authorized", "button open", "control open", "freedom", "grant access", "keyhole")),
        MaterialSymbolInfo(name = "lock_person", codePoint = 63731, tags = listOf("access", "access control", "account", "authentication", "authorization", "confidential", "entry.", "figure")),
        MaterialSymbolInfo(name = "lock_reset", codePoint = 60126, tags = listOf("access", "around", "arrow", "authentication", "authorization", "circle", "clockwise", "closed")),
        MaterialSymbolInfo(name = "login", codePoint = 60023, tags = listOf("access", "account", "app", "application", "arrow", "authentication", "authorization", "avatar")),
        MaterialSymbolInfo(name = "logout", codePoint = 59834, tags = listOf("access", "account", "app", "application", "arrow", "arrow pointing right", "arrow right", "authentication")),
        MaterialSymbolInfo(name = "loyalty", codePoint = 59546, tags = listOf("achievement", "award", "benefit", "benefits", "best", "bonus", "card", "client")),
        MaterialSymbolInfo(name = "manage_accounts", codePoint = 61486, tags = listOf("access", "accounts", "administration", "avatar", "bust", "change", "circle", "control")),
        MaterialSymbolInfo(name = "manage_history", codePoint = 60391, tags = listOf("administration", "application", "arrangement", "arrow", "back", "backwards", "change", "chronology")),
        MaterialSymbolInfo(name = "mark_as_unread", codePoint = 59836, tags = listOf("alert", "as", "attention", "badge", "bookmark", "chat", "circle", "circular")),
        MaterialSymbolInfo(name = "markunread_mailbox", codePoint = 59547, tags = listOf("alert", "box", "communication", "deliver", "delivery", "envelop", "envelope", "flag")),
        MaterialSymbolInfo(name = "maximize", codePoint = 59696, tags = listOf("action", "app", "application", "arrows", "box", "components", "computer", "control")),
        MaterialSymbolInfo(name = "mediation", codePoint = 61351, tags = listOf("agreement", "alliance", "arrow", "arrows", "binding", "binding agreement", "chain", "circle")),
        MaterialSymbolInfo(name = "minimize", codePoint = 59697, tags = listOf("action", "app", "application", "bar", "basic", "bottom", "button", "close")),
        MaterialSymbolInfo(name = "model_training", codePoint = 61647, tags = listOf("ai", "algorithm", "analysis", "arrow", "artificial intelligence", "brain", "bulb", "computation")),
        MaterialSymbolInfo(name = "network_ping", codePoint = 60362, tags = listOf("alert", "antenna", "available", "bars", "cellular", "communication", "connection", "data")),
        MaterialSymbolInfo(name = "new_label", codePoint = 58889, tags = listOf("+", "add", "archive", "badge", "banner", "bookmark", "category", "classification")),
        MaterialSymbolInfo(name = "next_plan", codePoint = 61277, tags = listOf("agenda", "arrow", "blueprint", "business", "calendar", "circle", "direction", "document")),
        MaterialSymbolInfo(name = "nightlight_round", codePoint = 61278, tags = listOf("astronomy", "bedtime", "brightness", "celestial", "circle", "crescent", "dark", "display")),
        MaterialSymbolInfo(name = "no_accounts", codePoint = 61502, tags = listOf("access", "access denied", "account", "accounts", "authentication", "avatar", "banned", "blocked")),
        MaterialSymbolInfo(name = "noise_aware", codePoint = 60396, tags = listOf("access", "accessibility", "acoustic", "alert", "ambient", "arc", "audio", "aware")),
        MaterialSymbolInfo(name = "noise_control_off", codePoint = 60403, tags = listOf("ambient sound off", "audio", "audio off", "aware", "blocked", "cancel", "cancellation", "circle")),
        MaterialSymbolInfo(name = "not_accessible", codePoint = 61694, tags = listOf("access denied", "accessibility", "accessible", "alert", "blocked", "body", "circle", "closed")),
        MaterialSymbolInfo(name = "not_started", codePoint = 61649, tags = listOf("0", "beginning", "circle", "circular", "empty", "geometric", "incomplete", "initial")),
        MaterialSymbolInfo(name = "note_add", codePoint = 59548, tags = listOf("+", "add", "add document", "add note", "create", "create document", "data", "doc")),
        MaterialSymbolInfo(name = "offline_bolt", codePoint = 59698, tags = listOf("adapter", "alert", "batteries", "bolt", "charger", "circle", "device", "disconnected")),
        MaterialSymbolInfo(name = "offline_pin", codePoint = 59658, tags = listOf("approve", "available offline", "cache", "check", "checkmark", "circle", "complete", "destination")),
        MaterialSymbolInfo(name = "on_device_training", codePoint = 60413, tags = listOf("ai", "analytics", "arrow", "artificial intelligence", "bar", "brain", "bulb", "call")),
        MaterialSymbolInfo(name = "online_prediction", codePoint = 61675, tags = listOf("ai", "analysis", "analytics", "artificial intelligence", "bulb", "business", "chart", "computer")),
        MaterialSymbolInfo(name = "opacity", codePoint = 59676, tags = listOf("adjustment", "appearance", "blend", "box", "color", "control", "dark", "design")),
        MaterialSymbolInfo(name = "open_in_browser", codePoint = 59549, tags = listOf("access", "arrow", "box", "browser", "browser window", "diagonal arrow", "direct link", "expand")),
        MaterialSymbolInfo(name = "open_in_full", codePoint = 61902, tags = listOf("action", "arrow", "arrows", "box", "corners", "dimensions", "display", "document")),
        MaterialSymbolInfo(name = "open_in_new", codePoint = 59550, tags = listOf("access", "action", "app", "application", "arrow", "box", "button", "components"))
    )
}

internal val materialSymbols_action_chunk5: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "open_in_new_off", codePoint = 58614, tags = listOf("arrow", "blocked", "blocked link", "box", "broken arrow", "browser", "diagonal arrow", "direction")),
        MaterialSymbolInfo(name = "open_with", codePoint = 59551, tags = listOf("application", "arrow", "arrows", "arrows pointing out", "box", "corners", "dimensions", "direction")),
        MaterialSymbolInfo(name = "outbound", codePoint = 57802, tags = listOf("arrow", "away", "basic", "box", "circle", "diagonal arrow", "directional", "element")),
        MaterialSymbolInfo(name = "outbox", codePoint = 61279, tags = listOf("arrow", "box", "compartment", "container", "deliver", "delivery", "drafts", "email")),
        MaterialSymbolInfo(name = "outlet", codePoint = 61908, tags = listOf("adapter", "charge", "charging point", "connect", "connecter", "connection", "current", "disconnect")),
        MaterialSymbolInfo(name = "output", codePoint = 60350, tags = listOf("action", "area", "arrows", "box", "control", "corners", "diagonal", "display")),
        MaterialSymbolInfo(name = "pageview", codePoint = 59552, tags = listOf("add", "book", "browse", "circle", "content", "create", "data", "details")),
        MaterialSymbolInfo(name = "paid", codePoint = 61505, tags = listOf("amount", "balance", "banknote", "bill", "business", "buy", "card", "cash")),
        MaterialSymbolInfo(name = "pan_tool", codePoint = 59685, tags = listOf("application", "control", "cursor", "drag", "editor", "fingers", "gesture", "glove")),
        MaterialSymbolInfo(name = "pan_tool_alt", codePoint = 60345, tags = listOf("action", "control", "cursor", "digital hand", "drag", "fingers", "gesture", "grab")),
        MaterialSymbolInfo(name = "payment", codePoint = 59553, tags = listOf("account", "account information", "amex", "balance", "bank", "banking", "bill", "buy")),
        MaterialSymbolInfo(name = "pending", codePoint = 61284, tags = listOf("accordion", "arrow down", "bottom", "choose", "circle", "close", "collapse", "details")),
        MaterialSymbolInfo(name = "pending_actions", codePoint = 61883, tags = listOf("actions", "agenda", "alert", "backlog", "calendar", "clipboard", "clock", "date")),
        MaterialSymbolInfo(name = "percent", codePoint = 60248, tags = listOf("analysis", "arithmetic", "calculation", "chart", "circle", "completion", "data", "diagonal line")),
        MaterialSymbolInfo(name = "perm_camera_mic", codePoint = 59554, tags = listOf("access", "audio", "button", "camera", "capture", "communication", "controls", "device")),
        MaterialSymbolInfo(name = "perm_contact_calendar", codePoint = 59555, tags = listOf("account", "address book", "appointment", "button", "calendar", "contact", "date", "day")),
        MaterialSymbolInfo(name = "perm_data_setting", codePoint = 59556, tags = listOf("access", "adjustments", "administration", "cloud", "cog", "configuration", "connection", "control")),
        MaterialSymbolInfo(name = "perm_device_information", codePoint = 59557, tags = listOf("Android", "OS", "about", "alert", "announcement", "build", "cell", "cellular")),
        MaterialSymbolInfo(name = "perm_identity", codePoint = 59558, tags = listOf("account", "avatar", "avatar filled", "avatar outline", "body", "circle", "contact", "face")),
        MaterialSymbolInfo(name = "perm_media", codePoint = 59559, tags = listOf("archive", "arrangement", "collection", "content", "copy", "data", "digital library", "doc")),
        MaterialSymbolInfo(name = "perm_phone_msg", codePoint = 59560, tags = listOf("always", "avatar", "bubble", "business", "call", "cell", "chat", "chat support")),
        MaterialSymbolInfo(name = "perm_scan_wifi", codePoint = 59561, tags = listOf("access", "alert", "always on", "announcement", "antenna", "broadcast", "communication", "configuration")),
        MaterialSymbolInfo(name = "pets", codePoint = 59677, tags = listOf("adoption", "animal", "animal foot", "animal icon", "animal print", "animal shelter", "animal symbol", "animal tracks")),
        MaterialSymbolInfo(name = "php", codePoint = 60303, tags = listOf("abstract", "alphabet", "backend", "badge", "brackets", "character", "code", "coding")),
        MaterialSymbolInfo(name = "picture_in_picture", codePoint = 59562, tags = listOf("chat", "crop", "cropped", "display", "display within display", "displays", "dual view", "embedded video")),
        MaterialSymbolInfo(name = "picture_in_picture_alt", codePoint = 59665, tags = listOf("alternate", "box", "chat", "crop", "cropped", "display", "displays", "floating window")),
        MaterialSymbolInfo(name = "pin_end", codePoint = 59239, tags = listOf("action", "arrow", "destination", "direction", "dot", "end", "end point", "find")),
        MaterialSymbolInfo(name = "pin_invoke", codePoint = 59235, tags = listOf("action", "add location", "arrow", "destination", "direction", "dot", "drop", "geotag")),
        MaterialSymbolInfo(name = "pinch", codePoint = 60216, tags = listOf("adjust", "arrow", "arrows", "compress", "control", "direction", "document", "enlarge")),
        MaterialSymbolInfo(name = "plagiarism", codePoint = 59994, tags = listOf("academic", "alert", "caution", "check", "content", "copy", "detection", "dishonest")),
        MaterialSymbolInfo(name = "play_for_work", codePoint = 59654, tags = listOf("arrow", "audio", "bag", "briefcase", "business", "career", "circle", "corporate")),
        MaterialSymbolInfo(name = "polymer", codePoint = 59563, tags = listOf("abstract", "arrangement", "atoms", "branching", "chain", "chemistry", "connection", "data structure")),
        MaterialSymbolInfo(name = "power_settings_new", codePoint = 59564, tags = listOf("action", "button", "circle", "command", "control", "device", "electrical", "electronics")),
        MaterialSymbolInfo(name = "pregnant_woman", codePoint = 59678, tags = listOf("abdomen", "baby", "birth", "body", "child", "curved lines", "expecting", "family")),
        MaterialSymbolInfo(name = "preview", codePoint = 61893, tags = listOf("check", "design", "discern", "disclosed", "discover", "display", "examine", "explore")),
        MaterialSymbolInfo(name = "print", codePoint = 59565, tags = listOf("copier", "copy", "device", "document", "draft", "fax", "hardware", "ink")),
        MaterialSymbolInfo(name = "privacy_tip", codePoint = 61660, tags = listOf("account", "advice", "alert", "announcement", "assist", "assistance", "certified", "confidentiality")),
        MaterialSymbolInfo(name = "private_connectivity", codePoint = 59204, tags = listOf("access", "anonymize", "connection", "connectivity", "data", "digital privacy", "encrypted", "internet")),
        MaterialSymbolInfo(name = "production_quantity_limits", codePoint = 57809, tags = listOf("!", "alert", "amount", "attention", "bill", "boundary", "box", "capacity")),
        MaterialSymbolInfo(name = "published_with_changes", codePoint = 62002, tags = listOf("approve", "approved", "arrow", "arrows", "article", "blog", "changes", "check")),
        MaterialSymbolInfo(name = "query_builder", codePoint = 59566, tags = listOf("alarm", "appointment", "builder", "calendar", "chronometer", "clock", "countdown", "date")),
        MaterialSymbolInfo(name = "question_answer", codePoint = 59567, tags = listOf("answer", "answers", "bubble", "chat", "comment", "comments", "communicate", "communication")),
        MaterialSymbolInfo(name = "question_mark", codePoint = 60299, tags = listOf("?", "ask", "assistance", "circle", "clue", "curious", "curve", "dot")),
        MaterialSymbolInfo(name = "quickreply", codePoint = 61292, tags = listOf("bolt", "bubble", "chat", "comment", "comment bubble", "communicate", "communication", "communication bubble")),
        MaterialSymbolInfo(name = "receipt", codePoint = 59568, tags = listOf("accounting", "bill", "cash", "check", "checkout", "commerce", "cost", "document")),
        MaterialSymbolInfo(name = "record_voice_over", codePoint = 59679, tags = listOf("account", "announce", "audio", "avatar", "broadcast", "character", "circle", "commentary")),
        MaterialSymbolInfo(name = "redeem", codePoint = 59569, tags = listOf("bill", "bonus", "bonus points", "bow", "buy", "card", "cart", "cash")),
        MaterialSymbolInfo(name = "remove_done", codePoint = 59859, tags = listOf("abolish", "accept", "approval", "approve", "bin", "cancel", "check", "checkmark")),
        MaterialSymbolInfo(name = "remove_shopping_cart", codePoint = 59688, tags = listOf("basket", "card", "cart", "cash", "checkout", "clear", "clear cart", "coin")),
        MaterialSymbolInfo(name = "reorder", codePoint = 59646, tags = listOf("adjust", "arrows", "bars", "burger", "dots", "down", "drag", "drag and drop")),
        MaterialSymbolInfo(name = "repartition", codePoint = 63720, tags = listOf("allocation", "analysis", "area", "arrow", "arrows", "breakdown", "categories", "chart")),
        MaterialSymbolInfo(name = "report_problem", codePoint = 59570, tags = listOf("!", "alert", "app", "attention", "caution", "danger", "error", "exclamation")),
        MaterialSymbolInfo(name = "request_page", codePoint = 61996, tags = listOf("add", "add document", "add file", "application", "ask", "content", "create", "data")),
        MaterialSymbolInfo(name = "restore", codePoint = 59571, tags = listOf("activity", "arrow", "back", "backup", "backwards", "circular", "clear", "clock")),
        MaterialSymbolInfo(name = "restore_from_trash", codePoint = 59704, tags = listOf("action", "archive", "archive management", "arrow", "back", "backwards", "bin", "bring back")),
        MaterialSymbolInfo(name = "restore_page", codePoint = 59689, tags = listOf("arrow", "arrows", "back", "browser", "button", "circular arrow", "control", "data")),
        MaterialSymbolInfo(name = "rocket", codePoint = 60325, tags = listOf("adventure", "ascent", "astronaut", "astronomy", "boost", "cosmos", "discovery", "engine")),
        MaterialSymbolInfo(name = "rocket_launch", codePoint = 60315, tags = listOf("accelerate", "ascent", "astronaut", "boost", "cosmic", "exploration", "fast", "flight")),
        MaterialSymbolInfo(name = "room", codePoint = 59572, tags = listOf("address", "area", "current location", "destination", "direction", "drop", "find", "geography")),
        MaterialSymbolInfo(name = "rounded_corner", codePoint = 59680, tags = listOf("adjust", "border", "boundary", "box", "chamfer", "corner", "curve", "customization"))
    )
}

internal val materialSymbols_action_chunk6: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "rowing", codePoint = 59681, tags = listOf("activity", "athlete", "boat", "body", "canoe", "competitive", "exercise", "figure")),
        MaterialSymbolInfo(name = "rule", codePoint = 61890, tags = listOf("approve", "automation", "check", "command", "commands", "complete", "condition", "conditions")),
        MaterialSymbolInfo(name = "satellite_alt", codePoint = 60218, tags = listOf("alternative", "antenna", "artificial", "astronomy", "broadcast", "celestial", "communication", "connection")),
        MaterialSymbolInfo(name = "saved_search", codePoint = 59921, tags = listOf("archive", "bookmark", "collection", "criteria", "data", "discover", "explore", "favorite")),
        MaterialSymbolInfo(name = "savings", codePoint = 58091, tags = listOf("account", "bank", "banking", "banking icon", "bill", "budget", "card", "cash")),
        MaterialSymbolInfo(name = "schedule", codePoint = 59573, tags = listOf("alarm", "appointment", "calendar", "chronometer", "clock", "countdown", "date", "deadline")),
        MaterialSymbolInfo(name = "schedule_send", codePoint = 59914, tags = listOf("agenda", "appointment", "arrow", "calendar", "circle", "clock", "date", "delivery")),
        MaterialSymbolInfo(name = "search", codePoint = 59574, tags = listOf("browse", "circle", "discover", "discover icon", "explore", "explore icon", "filter", "find")),
        MaterialSymbolInfo(name = "search_off", codePoint = 60022, tags = listOf("access denied", "blocked", "blocked access", "cancel", "cancel search", "circle", "clear", "clear search")),
        MaterialSymbolInfo(name = "segment", codePoint = 59723, tags = listOf("alignment", "analytics", "analyze", "breakdown", "categorize", "chart", "chunk", "classify")),
        MaterialSymbolInfo(name = "send_and_archive", codePoint = 59916, tags = listOf("archive", "arrow", "box", "chat", "chat message", "communication", "compose", "deliver")),
        MaterialSymbolInfo(name = "sensors", codePoint = 58654, tags = listOf("antenna", "bar graph", "bars", "communication", "connection", "connection status", "connectivity", "data")),
        MaterialSymbolInfo(name = "sensors_off", codePoint = 58655, tags = listOf("block", "cancel", "connection", "crossed out", "detection off", "diagonal line", "disable", "disabled")),
        MaterialSymbolInfo(name = "settings", codePoint = 59576, tags = listOf("adjustments", "administration", "administration panel", "application", "change", "cog", "cogwheel", "configuration")),
        MaterialSymbolInfo(name = "settings_accessibility", codePoint = 61533, tags = listOf("access", "accessibility", "adaptation", "adjustments", "aids", "body", "cog", "configuration")),
        MaterialSymbolInfo(name = "settings_applications", codePoint = 59577, tags = listOf("adjust", "administration", "app", "application", "applications", "change", "circle", "cog")),
        MaterialSymbolInfo(name = "settings_backup_restore", codePoint = 59578, tags = listOf("archive", "arrow", "back", "backup", "backwards", "circle", "cloud", "cycle")),
        MaterialSymbolInfo(name = "settings_bluetooth", codePoint = 59579, tags = listOf("accessories", "adjustments", "audio", "bluetooth", "configuration", "connect", "connection", "connectivity")),
        MaterialSymbolInfo(name = "settings_brightness", codePoint = 59581, tags = listOf("adjust", "adjustment", "appearance", "brightness", "configuration", "contrast", "control", "customize")),
        MaterialSymbolInfo(name = "settings_cell", codePoint = 59580, tags = listOf("Android", "OS", "adjustment", "administration", "administration panel", "cell", "cell phone", "cellular")),
        MaterialSymbolInfo(name = "settings_ethernet", codePoint = 59582, tags = listOf("arrows", "cable", "communication", "component", "computer", "computer network", "connect", "connection")),
        MaterialSymbolInfo(name = "settings_input_antenna", codePoint = 59583, tags = listOf("airplay", "antenna", "arrows", "broadcast", "cast", "communication", "computer", "connect")),
        MaterialSymbolInfo(name = "settings_input_component", codePoint = 59584, tags = listOf("audio", "av", "cable", "cables", "component", "composite", "configure", "connect")),
        MaterialSymbolInfo(name = "settings_input_composite", codePoint = 59585, tags = listOf("audio", "av", "cables", "component", "composite", "configure", "connection", "connectivity")),
        MaterialSymbolInfo(name = "settings_input_hdmi", codePoint = 59586, tags = listOf("audio", "av", "cable", "configuration", "connection", "connectivity", "connector", "definition")),
        MaterialSymbolInfo(name = "settings_input_svideo", codePoint = 59587, tags = listOf("adapter", "audio video", "audio visual", "av", "cable", "cable connection", "circle", "component video")),
        MaterialSymbolInfo(name = "settings_overscan", codePoint = 59588, tags = listOf("adjustment", "arrows", "aspect ratio", "border", "box", "calibration", "corners", "display")),
        MaterialSymbolInfo(name = "settings_phone", codePoint = 59589, tags = listOf("adjust", "administration", "call", "cell", "cellular", "cog", "communication", "configuration")),
        MaterialSymbolInfo(name = "settings_power", codePoint = 59590, tags = listOf("access", "action", "button", "circle", "component", "control", "device", "electrical")),
        MaterialSymbolInfo(name = "settings_remote", codePoint = 59591, tags = listOf("access", "access settings", "adjustment", "appliance", "bluetooth", "configuration", "configure", "connection")),
        MaterialSymbolInfo(name = "settings_voice", codePoint = 59592, tags = listOf("adjustments", "audio", "circle", "circular", "cog", "configuration", "control", "controls")),
        MaterialSymbolInfo(name = "shop", codePoint = 59593, tags = listOf("architecture", "bag", "bill", "building", "business", "buy", "buying", "card")),
        MaterialSymbolInfo(name = "shop_2", codePoint = 57758, tags = listOf("2", "add", "arrow", "basket", "business", "buy", "cart", "checkout")),
        MaterialSymbolInfo(name = "shop_two", codePoint = 59594, tags = listOf("2", "add", "arrow", "basket", "business", "buy", "cart", "checkout")),
        MaterialSymbolInfo(name = "shopping_bag", codePoint = 61900, tags = listOf("acquire", "bag", "basket", "bill", "business", "buy", "card", "carry bag")),
        MaterialSymbolInfo(name = "shopping_basket", codePoint = 59595, tags = listOf("add", "add to cart", "bag", "basket", "bill", "buy", "card", "cart")),
        MaterialSymbolInfo(name = "shopping_cart", codePoint = 59596, tags = listOf("add", "add to cart", "basket", "bill", "buy", "buying", "card", "carriage")),
        MaterialSymbolInfo(name = "shopping_cart_checkout", codePoint = 60296, tags = listOf("add", "add to cart", "arrow", "bag", "basket", "buy", "buying", "cart")),
        MaterialSymbolInfo(name = "smart_button", codePoint = 61889, tags = listOf("action", "ai", "appliance", "artificial", "automated", "automatic", "automation", "button")),
        MaterialSymbolInfo(name = "source", codePoint = 61892, tags = listOf("area", "basis", "category", "code", "composer", "concern", "content", "context")),
        MaterialSymbolInfo(name = "space_dashboard", codePoint = 58987, tags = listOf("analytics", "arrangement", "blocks", "cards", "composition", "dashboard", "dashboard view", "data")),
        MaterialSymbolInfo(name = "spatial_audio", codePoint = 60395, tags = listOf("3d audio", "acoustic", "audio", "audio effects", "audio processing", "audio rendering", "audio settings", "direction")),
        MaterialSymbolInfo(name = "spatial_audio_off", codePoint = 60392, tags = listOf("3d audio off", "audio", "audio control", "audio icon", "audio off", "audio off icon", "audio options", "audio setting off")),
        MaterialSymbolInfo(name = "spatial_tracking", codePoint = 60394, tags = listOf("3d", "ar", "arrow", "audio", "augmented reality", "data", "direction", "disabled")),
        MaterialSymbolInfo(name = "speaker_notes", codePoint = 59597, tags = listOf("annotation", "audio", "bubble", "bullet points", "chat", "comment", "communicate", "detail")),
        MaterialSymbolInfo(name = "speaker_notes_off", codePoint = 59690, tags = listOf("bubble", "cancel", "chat", "comment", "communicate", "confidential notes", "control", "crossed out")),
        MaterialSymbolInfo(name = "spellcheck", codePoint = 59598, tags = listOf("a", "accuracy", "action", "alphabet", "approve", "button", "character", "check")),
        MaterialSymbolInfo(name = "star_rate", codePoint = 61676, tags = listOf("achievement", "assessment", "award", "bookmark", "celestial", "evaluation", "excellence", "favorite")),
        MaterialSymbolInfo(name = "stars", codePoint = 59600, tags = listOf("achievement", "alert", "badge", "bookmark", "bright", "circle", "favorite", "feature")),
        MaterialSymbolInfo(name = "sticky_note_2", codePoint = 61948, tags = listOf("2", "angle", "bookmark", "communication", "corner", "data", "document", "fold")),
        MaterialSymbolInfo(name = "store", codePoint = 59601, tags = listOf("address", "aisle", "bill", "building", "business", "buying", "card", "cash")),
        MaterialSymbolInfo(name = "subject", codePoint = 59602, tags = listOf("alignment", "answer", "assistance", "balloon", "bubble", "chat", "comment", "communication")),
        MaterialSymbolInfo(name = "subtitles_off", codePoint = 61298, tags = listOf("accessibility", "accessibility feature", "accessible", "audio", "caption", "captions disabled", "captions off", "cc")),
        MaterialSymbolInfo(name = "supervised_user_circle", codePoint = 59705, tags = listOf("account", "account settings", "avatar", "child", "circle", "control", "face", "family")),
        MaterialSymbolInfo(name = "supervisor_account", codePoint = 59603, tags = listOf("access", "account", "account settings", "admin", "administrator", "avatar", "block", "configuration")),
        MaterialSymbolInfo(name = "support", codePoint = 61299, tags = listOf("advice", "agent", "assist", "assistance", "avatar", "basic", "buoy", "call")),
        MaterialSymbolInfo(name = "swap_horiz", codePoint = 59604, tags = listOf("alternate", "arrow", "arrows", "back", "change", "data transfer", "direction", "double-ended arrow")),
        MaterialSymbolInfo(name = "swap_horizontal_circle", codePoint = 59699, tags = listOf("alternate", "arrow", "arrows", "back", "back and forth", "button", "change", "circle")),
        MaterialSymbolInfo(name = "swap_vert", codePoint = 59605, tags = listOf("arrow", "arrows", "bidirectional", "connection", "data", "direction", "direction change", "document")),
        MaterialSymbolInfo(name = "swap_vertical_circle", codePoint = 59606, tags = listOf("arrow", "arrows", "bidirectional", "change", "circle", "circular", "communication", "content"))
    )
}

internal val materialSymbols_action_chunk7: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "swipe", codePoint = 59884, tags = listOf("action", "animation", "arrow", "arrows", "control", "cursor", "direction", "drag")),
        MaterialSymbolInfo(name = "swipe_down", codePoint = 60243, tags = listOf("action", "arrows", "content loading", "control", "direction", "disable", "down", "down arrow")),
        MaterialSymbolInfo(name = "swipe_down_alt", codePoint = 60208, tags = listOf("action", "alt", "alternate", "arrows", "direction", "disable", "down", "downwards")),
        MaterialSymbolInfo(name = "swipe_left", codePoint = 60249, tags = listOf("action", "app", "arrow", "arrows", "back", "button", "command", "control")),
        MaterialSymbolInfo(name = "swipe_left_alt", codePoint = 60211, tags = listOf("alt", "archive", "arrow", "arrows", "control", "delete", "direction", "dismiss")),
        MaterialSymbolInfo(name = "swipe_right", codePoint = 60242, tags = listOf("accept", "action", "advance", "app", "arrow", "arrows", "command", "digital")),
        MaterialSymbolInfo(name = "swipe_right_alt", codePoint = 60246, tags = listOf("accept", "action", "alt", "arrow", "arrows", "control", "cursor", "direction")),
        MaterialSymbolInfo(name = "swipe_up", codePoint = 60206, tags = listOf("arc", "arrow", "arrows", "caret", "clean", "curve", "direction", "disable")),
        MaterialSymbolInfo(name = "swipe_up_alt", codePoint = 60213, tags = listOf("action", "alt", "alternative", "alternative swipe", "arrow", "arrow up", "arrows", "control")),
        MaterialSymbolInfo(name = "swipe_vertical", codePoint = 60241, tags = listOf("action", "arrows", "control", "digital", "direction", "down", "drag", "drag down")),
        MaterialSymbolInfo(name = "switch_access_shortcut", codePoint = 59361, tags = listOf("access", "access point", "accessibility", "activation", "alternative input", "arrow", "arrows", "assistance")),
        MaterialSymbolInfo(name = "switch_access_shortcut_add", codePoint = 59362, tags = listOf("+", "access", "accessibility", "add", "arrow", "arrows", "button", "control")),
        MaterialSymbolInfo(name = "sync_alt", codePoint = 59928, tags = listOf("alt", "arrow", "arrows", "back and forth", "change", "circle", "circular", "connecting")),
        MaterialSymbolInfo(name = "system_update_alt", codePoint = 59607, tags = listOf("application", "arrow", "backup", "cloud", "computer", "data transfer", "device", "down")),
        MaterialSymbolInfo(name = "tab", codePoint = 59608, tags = listOf("add button", "add document", "add tab", "add window", "application management", "application window", "browser", "browser control")),
        MaterialSymbolInfo(name = "tab_unselected", codePoint = 59609, tags = listOf("application", "background", "blank", "border", "browser", "computer", "content", "dash")),
        MaterialSymbolInfo(name = "table_view", codePoint = 61886, tags = listOf("arrangement", "cell", "chart", "columns", "data", "data visualization", "display", "format")),
        MaterialSymbolInfo(name = "task_alt", codePoint = 58086, tags = listOf("achievement", "approval", "approve", "approved", "assignment", "check", "checkbox", "checklist")),
        MaterialSymbolInfo(name = "terminal", codePoint = 60302, tags = listOf("IT", "administration", "angle brackets", "application", "code", "coding", "command line", "command prompt")),
        MaterialSymbolInfo(name = "text_rotate_up", codePoint = 59706, tags = listOf("A", "adjustment", "alphabet", "arrange", "arrow", "character", "characters", "clockwise")),
        MaterialSymbolInfo(name = "text_rotate_vertical", codePoint = 59707, tags = listOf("A", "alignment", "alphabet", "arrange", "arrow", "arrows", "change direction", "change orientation")),
        MaterialSymbolInfo(name = "text_rotation_angledown", codePoint = 59708, tags = listOf("A", "adjust text", "align", "alignment", "alphabet", "angle", "angledown", "arrow")),
        MaterialSymbolInfo(name = "text_rotation_angleup", codePoint = 59709, tags = listOf("A", "adjustment", "alphabet", "angle", "angleup", "arrange", "arrow", "character")),
        MaterialSymbolInfo(name = "text_rotation_down", codePoint = 59710, tags = listOf("A", "adjust", "alphabet", "arrow", "character", "direction", "document", "dow")),
        MaterialSymbolInfo(name = "text_rotation_none", codePoint = 59711, tags = listOf("A", "alignment", "alphabet", "arrow", "box", "character", "content", "document")),
        MaterialSymbolInfo(name = "theaters", codePoint = 59610, tags = listOf("box office", "cinema", "clip", "documentary", "entertainment", "feature", "film", "independent")),
        MaterialSymbolInfo(name = "thumb_down", codePoint = 59611, tags = listOf("ate", "cancel", "disagree", "disapproval", "dislike", "down", "favorite", "feedback")),
        MaterialSymbolInfo(name = "thumb_down_off_alt", codePoint = 59890, tags = listOf("cancel", "disabled", "disagree", "disapproval", "dislike", "down", "enabled", "favorite")),
        MaterialSymbolInfo(name = "thumb_up", codePoint = 59612, tags = listOf("acknowledgement", "agree", "approve", "button", "choice", "confirmation", "content interaction", "control")),
        MaterialSymbolInfo(name = "thumb_up_off_alt", codePoint = 59891, tags = listOf("acknowledgement", "agree", "alt", "approve", "button", "choice", "confirmation", "content interaction")),
        MaterialSymbolInfo(name = "thumbs_up_down", codePoint = 59613, tags = listOf("agree", "approval", "comparison", "contrast", "decision", "direction", "disagree", "dislike")),
        MaterialSymbolInfo(name = "timeline", codePoint = 59682, tags = listOf("chart", "chronological", "data", "dates", "diagram", "dots", "duration", "events")),
        MaterialSymbolInfo(name = "tips_and_updates", codePoint = 59290, tags = listOf("advice", "ai", "alert", "and", "announcement", "artificial", "automatic", "automation")),
        MaterialSymbolInfo(name = "toc", codePoint = 59614, tags = listOf("bullet points", "chapter list", "chapters", "content", "document", "document navigation", "document sections", "file")),
        MaterialSymbolInfo(name = "today", codePoint = 59615, tags = listOf("agenda", "appointment", "calendar", "circle", "circle with dot", "clock", "contemporary", "current")),
        MaterialSymbolInfo(name = "token", codePoint = 59941, tags = listOf("access", "access token", "account", "approval", "authentication", "authentication token", "authorization", "badge")),
        MaterialSymbolInfo(name = "toll", codePoint = 59616, tags = listOf("assets", "bill", "booth", "budget", "car", "card", "cash", "charge")),
        MaterialSymbolInfo(name = "touch_app", codePoint = 59667, tags = listOf("action", "app", "application", "button", "click", "command", "control", "cursor")),
        MaterialSymbolInfo(name = "tour", codePoint = 61301, tags = listOf("assist", "assistance", "circle", "destination", "dot", "explanation", "feature", "first time")),
        MaterialSymbolInfo(name = "track_changes", codePoint = 59617, tags = listOf("bullseye", "changes", "circle", "collaboration", "compare", "comparison", "content", "differences")),
        MaterialSymbolInfo(name = "transcribe", codePoint = 63724, tags = listOf("ai", "analysis", "assistant", "audio", "automatic", "caption", "communication", "conversion")),
        MaterialSymbolInfo(name = "translate", codePoint = 59618, tags = listOf("arrow", "bidirectional", "bubble", "change", "chat", "communication", "conversion", "dictionary")),
        MaterialSymbolInfo(name = "trending_down", codePoint = 59619, tags = listOf("analysis", "analytics", "arrow", "arrow down", "arrow icon", "business", "chart", "data")),
        MaterialSymbolInfo(name = "trending_flat", codePoint = 59620, tags = listOf("arrow", "average", "change", "chart", "constant", "data", "direction", "equal")),
        MaterialSymbolInfo(name = "trending_up", codePoint = 59621, tags = listOf("analysis", "analytics", "arrow", "ascending", "business", "chart", "data", "diagram")),
        MaterialSymbolInfo(name = "troubleshoot", codePoint = 57810, tags = listOf("adjust", "analytics", "chart", "cogs", "configure", "data", "diagnose", "diagram")),
        MaterialSymbolInfo(name = "try", codePoint = 61564, tags = listOf("approve", "attempt", "best", "bookmark", "bubble", "chat", "comment", "communicate")),
        MaterialSymbolInfo(name = "turned_in", codePoint = 59622, tags = listOf("app", "archive", "article", "book", "bookmark", "browser", "collection", "content")),
        MaterialSymbolInfo(name = "turned_in_not", codePoint = 59623, tags = listOf("app", "archive", "article", "book", "bookmark", "browser", "collection", "content")),
        MaterialSymbolInfo(name = "unfold_less_double", codePoint = 63695, tags = listOf("arrow", "arrows", "arrows down", "arrows inward", "arrows pointing in", "chevron", "chevrons", "close")),
        MaterialSymbolInfo(name = "unfold_more_double", codePoint = 63696, tags = listOf("action", "additional", "arrow", "arrows", "button", "chevron", "collapse", "control")),
        MaterialSymbolInfo(name = "unpublished", codePoint = 62006, tags = listOf("analysis", "analytics", "approve", "bar chart", "bar graph", "business", "chart", "check")),
        MaterialSymbolInfo(name = "update", codePoint = 59683, tags = listOf("app", "arrow", "arrow circle", "back", "backwards", "circle", "circular", "clock")),
        MaterialSymbolInfo(name = "update_disabled", codePoint = 57461, tags = listOf("arrow", "back", "backwards", "blocked", "cancelled", "circle", "clock", "date")),
        MaterialSymbolInfo(name = "upgrade", codePoint = 61691, tags = listOf("above", "advance", "arrow", "ascent", "better", "direction", "elevation", "enhance")),
        MaterialSymbolInfo(name = "verified", codePoint = 61302, tags = listOf("accepted", "accreditation", "approval", "approval icon", "approve", "authentic", "authorized", "badge")),
        MaterialSymbolInfo(name = "verified_user", codePoint = 59624, tags = listOf("approve", "badge", "certified", "check", "complete", "confirmation", "data", "done")),
        MaterialSymbolInfo(name = "vertical_split", codePoint = 59721, tags = listOf("arrangement", "columns", "content layout", "design", "display", "divide", "document layout", "dual view")),
        MaterialSymbolInfo(name = "view_agenda", codePoint = 59625, tags = listOf("agenda", "agenda view", "arrange", "blocks", "calendar", "cards", "checklist", "data")),
        MaterialSymbolInfo(name = "view_array", codePoint = 59626, tags = listOf("arrange", "arrangement", "array", "blocks", "columns", "content", "data", "design"))
    )
}

internal val materialSymbols_action_chunk8: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "view_carousel", codePoint = 59627, tags = listOf("cards", "carousel", "collection", "content", "design", "display", "elements", "exhibition")),
        MaterialSymbolInfo(name = "view_column", codePoint = 59628, tags = listOf("alignment", "arrangement", "column", "columns", "data", "data display", "design", "display")),
        MaterialSymbolInfo(name = "view_comfy_alt", codePoint = 60275, tags = listOf("alt", "area", "arrangement", "blocks", "boxes", "collection", "comfortable", "comfy")),
        MaterialSymbolInfo(name = "view_compact_alt", codePoint = 60276, tags = listOf("alt", "alternate", "arrange", "blocks", "box", "columns", "compact", "content")),
        MaterialSymbolInfo(name = "view_cozy", codePoint = 60277, tags = listOf("arrangement", "boxes", "close", "clustered", "comfy", "compact", "content", "cozy")),
        MaterialSymbolInfo(name = "view_day", codePoint = 59629, tags = listOf("appointment", "arrangement", "bar", "blocks", "calendar", "cards", "carousel", "columns")),
        MaterialSymbolInfo(name = "view_headline", codePoint = 59630, tags = listOf("area", "arrangement", "article", "bars", "block", "component", "content", "design")),
        MaterialSymbolInfo(name = "view_in_ar", codePoint = 59902, tags = listOf("3d", "3d model", "ar", "ar experience", "augmented", "augmented reality", "box", "cube")),
        MaterialSymbolInfo(name = "view_kanban", codePoint = 60287, tags = listOf("agile", "blocks", "board", "cards", "column", "grid", "kanban", "kanban board")),
        MaterialSymbolInfo(name = "view_list", codePoint = 59631, tags = listOf("arrangement", "bulleted", "catalog", "compact", "content", "data", "design", "directory")),
        MaterialSymbolInfo(name = "view_module", codePoint = 59632, tags = listOf("arrange", "arrangement", "blocks", "collection", "components", "content", "dashboard", "data")),
        MaterialSymbolInfo(name = "view_quilt", codePoint = 59633, tags = listOf("arrangement", "blocks", "columns", "composition", "dashboard", "design", "divisions", "format")),
        MaterialSymbolInfo(name = "view_sidebar", codePoint = 61716, tags = listOf("area", "bar", "collapse", "column", "content", "control", "data", "design")),
        MaterialSymbolInfo(name = "view_stream", codePoint = 59634, tags = listOf("arrangement", "block view", "blocks", "columns", "content", "content blocks", "data", "design")),
        MaterialSymbolInfo(name = "view_timeline", codePoint = 60293, tags = listOf("analytics", "chart", "chronological", "data", "diagram", "display", "event", "flow")),
        MaterialSymbolInfo(name = "view_week", codePoint = 59635, tags = listOf("agenda", "agenda view", "appointment", "appointments", "bars", "calendar", "calendar view", "chronicle")),
        MaterialSymbolInfo(name = "visibility", codePoint = 59636, tags = listOf("display", "eye", "glance", "hidden", "hidden text", "insight", "look", "observe")),
        MaterialSymbolInfo(name = "visibility_off", codePoint = 59637, tags = listOf("conceal", "crossed out eye", "diagonal line", "disabled", "disabled view", "enabled", "eye", "form")),
        MaterialSymbolInfo(name = "voice_over_off", codePoint = 59722, tags = listOf("accessibility", "accessibility feature", "accessibility off", "account", "assistance disabled", "audio disabled", "audio off", "blocked")),
        MaterialSymbolInfo(name = "watch_later", codePoint = 59684, tags = listOf("alarm", "appointment", "calendar", "chronometer", "clock", "countdown", "date", "deadline")),
        MaterialSymbolInfo(name = "webhook", codePoint = 60306, tags = listOf("alert", "api", "arrow", "automation", "backend", "box", "code", "communication")),
        MaterialSymbolInfo(name = "width_full", codePoint = 63733, tags = listOf("action", "arrows", "button", "columns", "content", "control", "display", "expand")),
        MaterialSymbolInfo(name = "width_normal", codePoint = 63734, tags = listOf("adjust size", "adjust width", "alignment", "boundaries", "canvas size", "content width", "contract", "controls")),
        MaterialSymbolInfo(name = "width_wide", codePoint = 63735, tags = listOf("adjust", "aspect ratio", "bar", "cinema", "dimension", "display", "enlarge", "expand")),
        MaterialSymbolInfo(name = "wifi_protected_setup", codePoint = 61692, tags = listOf("WPS", "access", "around", "arrow", "arrows", "authenticate", "broadcast", "configuration")),
        MaterialSymbolInfo(name = "work", codePoint = 59641, tags = listOf("achievement", "bag", "baggage", "briefcase", "business", "career", "case", "commerce")),
        MaterialSymbolInfo(name = "work_history", codePoint = 60425, tags = listOf("activity log", "archive", "back", "backwards", "bag", "baggage", "briefcase", "business")),
        MaterialSymbolInfo(name = "work_off", codePoint = 59714, tags = listOf("bag", "baggage", "blocked", "briefcase", "business", "business travel", "cancelled", "career")),
        MaterialSymbolInfo(name = "work_outline", codePoint = 59715, tags = listOf("achievement", "bag", "baggage", "briefcase", "business", "career", "case", "commerce")),
        MaterialSymbolInfo(name = "wysiwyg", codePoint = 61891, tags = listOf("Rich text editor", "basic editor", "composer", "composition", "content creation", "document", "document editing", "document editor")),
        MaterialSymbolInfo(name = "youtube_searched_for", codePoint = 59642, tags = listOf("analysis", "analytics", "arrow", "back", "backwards", "discover", "entertainment", "examine")),
        MaterialSymbolInfo(name = "zoom_in", codePoint = 59647, tags = listOf("action", "add", "big", "bigger", "button", "circle", "command", "control")),
        MaterialSymbolInfo(name = "zoom_out", codePoint = 59648, tags = listOf("action", "adjust", "button", "control", "decrease", "decrease size", "discover", "document view"))
    )
}

internal val materialSymbols_action_category: MaterialSymbolCategory by lazy(LazyThreadSafetyMode.NONE) {
    MaterialSymbolCategory(
        key = "action",
        icons = buildList {
            addAll(materialSymbols_action_chunk1)
            addAll(materialSymbols_action_chunk2)
            addAll(materialSymbols_action_chunk3)
            addAll(materialSymbols_action_chunk4)
            addAll(materialSymbols_action_chunk5)
            addAll(materialSymbols_action_chunk6)
            addAll(materialSymbols_action_chunk7)
            addAll(materialSymbols_action_chunk8)
        }
    )
}
