package com.example.itemmanagement.ui.components

import kotlin.LazyThreadSafetyMode

internal val materialSymbols_maps_chunk1: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "360", codePoint = 58743, tags = listOf("360", "360 degrees", "around", "arrow", "av", "camera", "circle", "circular")),
        MaterialSymbolInfo(name = "add_business", codePoint = 59177, tags = listOf("+", "add", "add building", "add business", "add business location", "add location", "bill", "building")),
        MaterialSymbolInfo(name = "add_location", codePoint = 58727, tags = listOf("+", "add", "address", "check in", "coordinate", "create", "destination", "direction")),
        MaterialSymbolInfo(name = "add_location_alt", codePoint = 61242, tags = listOf("+", "add", "address", "coordinate", "create", "destination", "direction", "directory")),
        MaterialSymbolInfo(name = "add_road", codePoint = 61243, tags = listOf("+", "add", "add new", "build", "create", "destination", "direction", "graphic")),
        MaterialSymbolInfo(name = "agriculture", codePoint = 60025, tags = listOf("agriculture", "automobile", "botanical", "car", "cars", "crop", "cultivate", "cultivation")),
        MaterialSymbolInfo(name = "airline_stops", codePoint = 59344, tags = listOf("airline", "airplane", "airport", "arrow", "aviation", "circles", "connection", "destination")),
        MaterialSymbolInfo(name = "airlines", codePoint = 59338, tags = listOf("air", "air travel", "aircraft", "airlines", "airlines icon", "airplane", "airplane mode", "airplanes")),
        MaterialSymbolInfo(name = "alt_route", codePoint = 61828, tags = listOf("alt", "alternate", "alternate routes", "alternative", "arrows", "bifurcate", "branching", "change")),
        MaterialSymbolInfo(name = "atm", codePoint = 58739, tags = listOf("alphabet", "atm", "automated", "automated teller machine", "banking", "bill", "building", "card")),
        MaterialSymbolInfo(name = "attractions", codePoint = 59986, tags = listOf("Ferris wheel", "activity", "amusement", "amusement park", "attractions", "circle", "destination", "entertainment")),
        MaterialSymbolInfo(name = "badge", codePoint = 60007, tags = listOf("accolade", "account", "achievement", "approval", "avatar", "award", "badge", "card")),
        MaterialSymbolInfo(name = "bakery_dining", codePoint = 59987, tags = listOf("baked goods", "bakery", "baking", "bread", "breakfast", "brunch", "cafe", "catering")),
        MaterialSymbolInfo(name = "beenhere", codePoint = 58669, tags = listOf("acknowledgement", "approve", "archive", "arrival", "been", "beenhere", "bookmark", "check")),
        MaterialSymbolInfo(name = "bike_scooter", codePoint = 61253, tags = listOf("agile", "automobile", "bicycle", "bike", "car", "cars", "city", "commute")),
        MaterialSymbolInfo(name = "breakfast_dining", codePoint = 59988, tags = listOf("bakery", "bread", "breakfast", "brunch", "butter", "catering", "circle", "cooking")),
        MaterialSymbolInfo(name = "brunch_dining", codePoint = 60019, tags = listOf("bistro", "breakfast", "brunch", "cafe", "champagne", "cuisine", "cutlery", "dining")),
        MaterialSymbolInfo(name = "bus_alert", codePoint = 59791, tags = listOf("!", "alarm", "alert", "attention", "automobile", "breakdown", "bus", "car")),
        MaterialSymbolInfo(name = "car_crash", codePoint = 60402, tags = listOf("accident", "alert", "auto", "automobile", "broken", "car", "cars", "collision")),
        MaterialSymbolInfo(name = "car_rental", codePoint = 59989, tags = listOf("access", "automobile", "booking", "booking service", "car", "car key", "cars", "drive")),
        MaterialSymbolInfo(name = "car_repair", codePoint = 59990, tags = listOf("adjustments", "assistance", "auto", "automobile", "automotive", "breakdown", "car", "car service")),
        MaterialSymbolInfo(name = "castle", codePoint = 60081, tags = listOf("abode", "ancient", "architecture", "battlement", "building", "castle", "domain", "dwelling")),
        MaterialSymbolInfo(name = "category", codePoint = 58740, tags = listOf("categories", "category", "chain", "chains", "chart", "charts", "circle", "circles")),
        MaterialSymbolInfo(name = "celebration", codePoint = 60005, tags = listOf("achievement", "activity", "award", "birthday", "burst", "celebration", "confetti", "congratulations")),
        MaterialSymbolInfo(name = "church", codePoint = 60078, tags = listOf("architecture", "building", "cathedral", "ceremony", "chapel", "christian", "christianity", "church")),
        MaterialSymbolInfo(name = "cleaning_services", codePoint = 61695, tags = listOf("broom", "care", "chore", "clean", "cleaning", "commercial", "domestic", "dust")),
        MaterialSymbolInfo(name = "compass_calibration", codePoint = 58748, tags = listOf("accuracy", "adjust", "alignment", "bearing", "calibrate", "calibration", "circle", "compass")),
        MaterialSymbolInfo(name = "connecting_airports", codePoint = 59337, tags = listOf("air", "aircraft", "airplane", "airplanes", "airport", "arrival", "aviation", "aviation route")),
        MaterialSymbolInfo(name = "crisis_alert", codePoint = 60393, tags = listOf("!", "alarm", "alert", "attention", "bullseye", "caution", "crisis", "critical")),
        MaterialSymbolInfo(name = "delivery_dining", codePoint = 60018, tags = listOf("buy", "commerce", "courier", "delivery", "dining", "dispatch", "driving", "drop off")),
        MaterialSymbolInfo(name = "departure_board", codePoint = 58742, tags = listOf("airport", "arrival board", "arrivals", "automobile", "board", "bus", "bus station", "car")),
        MaterialSymbolInfo(name = "design_services", codePoint = 61706, tags = listOf("architecture", "art", "build", "compose", "create", "design", "draft", "drafting")),
        MaterialSymbolInfo(name = "diamond", codePoint = 60117, tags = listOf("award", "brilliant", "clean", "crystal", "cut", "diamond", "exclusive", "expensive")),
        MaterialSymbolInfo(name = "dinner_dining", codePoint = 59991, tags = listOf("beverage", "breakfast", "cafe", "cooking", "cuisine", "culinary", "cutlery", "dining")),
        MaterialSymbolInfo(name = "directions", codePoint = 58670, tags = listOf("address", "arrow", "compass", "course", "destination", "directions", "exploring", "finding")),
        MaterialSymbolInfo(name = "directions_bike", codePoint = 58671, tags = listOf("activity", "bicycle", "bike", "cycling", "direction", "directions", "exercise", "fitness")),
        MaterialSymbolInfo(name = "directions_boat", codePoint = 58674, tags = listOf("automobile", "boat", "boating", "car", "cars", "cruise", "direction", "directions")),
        MaterialSymbolInfo(name = "directions_boat_filled", codePoint = 61429, tags = listOf("automobile", "boat", "boating", "car", "cars", "cruise", "direction", "directions")),
        MaterialSymbolInfo(name = "directions_bus", codePoint = 58672, tags = listOf("automobile", "bus", "car", "cars", "commute", "directions", "filled", "journey")),
        MaterialSymbolInfo(name = "directions_bus_filled", codePoint = 61430, tags = listOf("automobile", "bus", "car", "cars", "commute", "directions", "filled", "journey")),
        MaterialSymbolInfo(name = "directions_car", codePoint = 58673, tags = listOf("auto", "automobile", "automotive", "car", "car symbol", "cars", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_car_filled", codePoint = 61431, tags = listOf("auto", "automobile", "automotive", "car", "car symbol", "cars", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_railway", codePoint = 58676, tags = listOf("automobile", "car", "cars", "commuter", "commuting", "direction", "directions", "express")),
        MaterialSymbolInfo(name = "directions_railway_filled", codePoint = 61432, tags = listOf("automobile", "car", "cars", "commuter", "commuting", "direction", "directions", "express")),
        MaterialSymbolInfo(name = "directions_run", codePoint = 58726, tags = listOf("activity", "athlete", "beginning", "body", "destination", "directions", "exercise", "figure")),
        MaterialSymbolInfo(name = "directions_subway", codePoint = 58675, tags = listOf("automobile", "car", "cars", "city", "commute", "connection", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_subway_filled", codePoint = 61433, tags = listOf("automobile", "car", "cars", "city", "commute", "connection", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_transit", codePoint = 58677, tags = listOf("automobile", "car", "cars", "city", "commute", "connection", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_transit_filled", codePoint = 61434, tags = listOf("automobile", "car", "cars", "city", "commute", "connection", "destination", "direction")),
        MaterialSymbolInfo(name = "directions_walk", codePoint = 58678, tags = listOf("activity", "assist", "body", "direction", "directions", "exercise", "figure", "find")),
        MaterialSymbolInfo(name = "dry_cleaning", codePoint = 59992, tags = listOf("apparel", "bubble", "button", "care", "chore", "circle", "circular", "cleaning")),
        MaterialSymbolInfo(name = "edit_attributes", codePoint = 58744, tags = listOf("adjust", "approve", "attributes", "attribution", "change", "check", "complete", "configure")),
        MaterialSymbolInfo(name = "edit_location", codePoint = 58728, tags = listOf("address", "alter", "change", "configure", "correct", "customize", "destination", "direction")),
        MaterialSymbolInfo(name = "edit_location_alt", codePoint = 57797, tags = listOf("address", "adjust", "alt", "alter", "change", "coordinates", "customize", "destination")),
        MaterialSymbolInfo(name = "edit_road", codePoint = 61261, tags = listOf("adjust", "annotate", "change", "curve", "destination", "direction", "draw", "edit")),
        MaterialSymbolInfo(name = "egg", codePoint = 60108, tags = listOf("animal", "boiled", "breakfast", "broken", "brunch", "cooking", "cracked", "delicate")),
        MaterialSymbolInfo(name = "egg_alt", codePoint = 60104, tags = listOf("agriculture", "bake", "break", "breakfast", "brunch", "carton", "cook", "cooking")),
        MaterialSymbolInfo(name = "electric_bike", codePoint = 60187, tags = listOf("battery", "battery bicycle", "battery bike", "bicycle", "bike", "bolt", "commute", "cycling")),
        MaterialSymbolInfo(name = "electric_car", codePoint = 60188, tags = listOf("automobile", "battery", "bolt", "car", "cars", "charge", "charging", "commute")),
        MaterialSymbolInfo(name = "electric_moped", codePoint = 60189, tags = listOf("automobile", "battery", "bike", "bolt", "car", "cars", "charging", "city"))
    )
}

internal val materialSymbols_maps_chunk2: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "electric_rickshaw", codePoint = 60190, tags = listOf("asia", "auto rickshaw", "automobile", "bangkok", "bolt", "car", "cars", "driver")),
        MaterialSymbolInfo(name = "electric_scooter", codePoint = 60191, tags = listOf("battery", "bike", "bolt", "city", "commute", "commuter", "deck", "direction")),
        MaterialSymbolInfo(name = "electrical_services", codePoint = 61698, tags = listOf("bolt", "bright", "charge", "circuit", "cord", "current", "electric", "electrical")),
        MaterialSymbolInfo(name = "emergency", codePoint = 57835, tags = listOf("alarm", "alert", "assistance", "asterisk", "attention", "bell", "clinic", "critical")),
        MaterialSymbolInfo(name = "emergency_recording", codePoint = 60404, tags = listOf("action", "alert", "app", "application", "attention", "button", "camera", "capture")),
        MaterialSymbolInfo(name = "emergency_share", codePoint = 60406, tags = listOf("alert", "assist", "attention", "broadcast", "call for help", "caution", "communicate", "crisis")),
        MaterialSymbolInfo(name = "ev_station", codePoint = 58733, tags = listOf("automobile", "battery", "bolt", "car", "cars", "charger", "charging", "charging port")),
        MaterialSymbolInfo(name = "factory", codePoint = 60348, tags = listOf("architecture", "assembly", "automation", "building", "business", "chimney", "commerce", "construction")),
        MaterialSymbolInfo(name = "fastfood", codePoint = 58746, tags = listOf("american food", "bun", "burger", "burger icon", "cheeseburger", "circle", "circle with rectangle", "cuisine")),
        MaterialSymbolInfo(name = "festival", codePoint = 60008, tags = listOf("art", "calendar", "celebration", "circus", "community", "concert", "culture", "dance")),
        MaterialSymbolInfo(name = "fire_hydrant_alt", codePoint = 63729, tags = listOf()),
        MaterialSymbolInfo(name = "fire_truck", codePoint = 63730, tags = listOf("accident", "aid", "alarm", "alert", "automotive", "danger", "emergency", "emergency services")),
        MaterialSymbolInfo(name = "flight", codePoint = 58681, tags = listOf("ai", "air", "air travel", "aircraft", "airplane", "airplanes", "airport", "arrival")),
        MaterialSymbolInfo(name = "flight_class", codePoint = 59339, tags = listOf("aerial", "air", "air travel", "aircraft", "airline", "airplane", "airplanes", "airport")),
        MaterialSymbolInfo(name = "forest", codePoint = 60057, tags = listOf("abstract", "adventure", "destination", "discovery", "earth", "eco", "environment", "exploration")),
        MaterialSymbolInfo(name = "fork_left", codePoint = 60320, tags = listOf("alternative", "arrow", "arrows", "branch left", "branching path", "choice", "decision", "deviation")),
        MaterialSymbolInfo(name = "fork_right", codePoint = 60332, tags = listOf("arrow", "arrow right", "arrows", "branch right", "curve right", "direction", "direction right", "directions")),
        MaterialSymbolInfo(name = "fort", codePoint = 60077, tags = listOf("ancient", "architecture", "battlements", "building", "castle", "defense", "dwelling", "fort")),
        MaterialSymbolInfo(name = "hail", codePoint = 59825, tags = listOf("alert", "bad weather", "body", "circles", "climate", "cold", "dots", "environment")),
        MaterialSymbolInfo(name = "handyman", codePoint = 61707, tags = listOf("adjust", "build", "builder", "cog", "configuration", "construction", "craftsman", "customize")),
        MaterialSymbolInfo(name = "hardware", codePoint = 59993, tags = listOf("adjust", "administration", "break", "circle", "cog", "configuration", "construction", "control")),
        MaterialSymbolInfo(name = "home_repair_service", codePoint = 61696, tags = listOf("adjustable wrench", "box", "building", "construction", "equipment", "fix", "gear", "hammer")),
        MaterialSymbolInfo(name = "hotel", codePoint = 58682, tags = listOf("accommodation", "apartment", "bed", "body", "booking", "building", "guesthouse", "holiday")),
        MaterialSymbolInfo(name = "hvac", codePoint = 61710, tags = listOf("ac", "adjustment", "air", "air conditioning", "air flow", "air vent", "airflow", "airflow direction")),
        MaterialSymbolInfo(name = "icecream", codePoint = 60009, tags = listOf("cafe", "celebration", "circle", "cold", "cone", "cool", "cream", "delicious")),
        MaterialSymbolInfo(name = "kebab_dining", codePoint = 59458, tags = listOf("actions", "additional options", "chef", "choices", "context menu", "cooking", "cuisine", "cutlery")),
        MaterialSymbolInfo(name = "layers", codePoint = 58683, tags = listOf("arrange", "composition", "content", "depth", "disabled", "display", "document", "enabled")),
        MaterialSymbolInfo(name = "layers_clear", codePoint = 58684, tags = listOf("3d", "arrange", "cancel", "clear", "delete", "delete layers", "depth", "disabled")),
        MaterialSymbolInfo(name = "liquor", codePoint = 60000, tags = listOf("alcohol", "app", "bar", "beverage", "bottle", "celebration", "cheers", "club")),
        MaterialSymbolInfo(name = "local_activity", codePoint = 58687, tags = listOf("access", "activity", "admission", "attendance", "cinema", "coupon", "cutout", "entertainment")),
        MaterialSymbolInfo(name = "local_airport", codePoint = 58685, tags = listOf("active", "air", "air travel", "aircraft", "airplane", "airplane icon", "airplane mode", "airport")),
        MaterialSymbolInfo(name = "local_atm", codePoint = 58686, tags = listOf("atm", "automated teller machine", "bank", "banking", "bill", "brick and mortar", "building", "card")),
        MaterialSymbolInfo(name = "local_bar", codePoint = 58688, tags = listOf("alcohol", "bar", "beer", "beverage", "bottle", "celebrate", "cheers", "club")),
        MaterialSymbolInfo(name = "local_cafe", codePoint = 58689, tags = listOf("beverage", "bottle", "break", "breakfast", "cafe", "caffeine", "ceramic", "coffee")),
        MaterialSymbolInfo(name = "local_car_wash", codePoint = 58690, tags = listOf("auto", "automobile", "brush", "bubble", "business", "car", "car wash", "cars")),
        MaterialSymbolInfo(name = "local_convenience_store", codePoint = 58691, tags = listOf("--", "24", "awning", "bill", "building", "business", "buying", "card")),
        MaterialSymbolInfo(name = "local_dining", codePoint = 58710, tags = listOf("bistro", "breakfast", "cafe", "catering", "cuisine", "cutlery", "dining", "dining experience")),
        MaterialSymbolInfo(name = "local_drink", codePoint = 58692, tags = listOf("alcohol", "bar", "beverage", "cafe", "catering", "cheers", "coffee", "cold drink")),
        MaterialSymbolInfo(name = "local_fire_department", codePoint = 61269, tags = listOf("911", "alert", "blaze", "burning", "climate", "danger", "department", "discovery")),
        MaterialSymbolInfo(name = "local_florist", codePoint = 58693, tags = listOf("beauty", "bloom", "blooming", "blossom", "botany", "decorative", "ecological", "environment")),
        MaterialSymbolInfo(name = "local_gas_station", codePoint = 58694, tags = listOf("area", "auto", "automotive", "car", "diesel", "discover", "dispenser", "energy")),
        MaterialSymbolInfo(name = "local_grocery_store", codePoint = 58695, tags = listOf("add to cart", "basket", "buy", "buying", "carriage", "cart", "checkout", "commerce")),
        MaterialSymbolInfo(name = "local_hospital", codePoint = 58696, tags = listOf("911", "aid", "ambulance", "building", "care", "clinic", "cross", "doctor")),
        MaterialSymbolInfo(name = "local_hotel", codePoint = 58697, tags = listOf("accommodation", "apartment", "bed", "body", "booking", "building", "guesthouse", "holiday")),
        MaterialSymbolInfo(name = "local_laundry_service", codePoint = 58698, tags = listOf("amenity", "apparel", "bubble", "bubbles", "business", "chores", "cleaner", "cleaning")),
        MaterialSymbolInfo(name = "local_library", codePoint = 58699, tags = listOf("academy", "archive", "book", "book icon", "book stack", "book symbol", "books", "collection")),
        MaterialSymbolInfo(name = "local_mall", codePoint = 58700, tags = listOf("bag", "basket", "bill", "boutique", "building", "business", "buy", "buying")),
        MaterialSymbolInfo(name = "local_movies", codePoint = 58701, tags = listOf("box office", "cinema", "clip", "documentary", "entertainment", "feature", "film", "independent")),
        MaterialSymbolInfo(name = "local_offer", codePoint = 58702, tags = listOf("bargain", "commerce", "coupon", "deal", "discount", "label", "market", "offer")),
        MaterialSymbolInfo(name = "local_parking", codePoint = 58703, tags = listOf("alphabet", "auto", "block", "car", "character", "city", "destination", "driving")),
        MaterialSymbolInfo(name = "local_pharmacy", codePoint = 58704, tags = listOf("911", "aid", "building", "clinic", "cross", "cure", "drug", "drugstore")),
        MaterialSymbolInfo(name = "local_phone", codePoint = 58705, tags = listOf("audio", "booth", "business", "call", "communication", "connect", "connection", "contact")),
        MaterialSymbolInfo(name = "local_pizza", codePoint = 58706, tags = listOf("catering", "cheese", "circle", "circular", "cooking", "cuisine", "delivery", "dining")),
        MaterialSymbolInfo(name = "local_play", codePoint = 58707, tags = listOf("access", "activity", "admission", "attendance", "cinema", "coupon", "cutout", "entertainment")),
        MaterialSymbolInfo(name = "local_police", codePoint = 61270, tags = listOf("911", "authority", "authority symbol", "badge", "crime", "emblem", "government", "identification")),
        MaterialSymbolInfo(name = "local_post_office", codePoint = 58708, tags = listOf("address", "building", "building exterior", "business", "communication", "delivery", "destination", "email")),
        MaterialSymbolInfo(name = "local_printshop", codePoint = 58709, tags = listOf("copier", "copy", "device", "document", "draft", "fax", "hardware", "ink")),
        MaterialSymbolInfo(name = "local_see", codePoint = 58711, tags = listOf("camera", "capture", "cinema", "event", "film", "footage", "gallery", "lens")),
        MaterialSymbolInfo(name = "local_shipping", codePoint = 58712, tags = listOf("automobile", "box", "business", "car", "cargo", "cars", "commerce", "delivery")),
        MaterialSymbolInfo(name = "local_taxi", codePoint = 58713, tags = listOf("appointment", "auto", "automobile", "booking", "cab", "call", "car", "cars"))
    )
}

internal val materialSymbols_maps_chunk3: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "lunch_dining", codePoint = 60001, tags = listOf("bar", "breakfast", "breakfast time", "brunch", "cafe", "canteen", "cutlery", "dining")),
        MaterialSymbolInfo(name = "map", codePoint = 58715, tags = listOf("address", "atlas", "cartography", "city", "continent", "country", "destination", "direction")),
        MaterialSymbolInfo(name = "maps_ugc", codePoint = 61272, tags = listOf("+", "add", "add data", "bubble", "cartography", "comment", "communicate", "contribution")),
        MaterialSymbolInfo(name = "medical_information", codePoint = 60397, tags = listOf("badge", "card", "chart", "clinic", "cross", "data", "details", "document")),
        MaterialSymbolInfo(name = "medical_services", codePoint = 61705, tags = listOf("aid", "assistance", "bag", "briefcase", "care", "clinic", "cross", "doctor")),
        MaterialSymbolInfo(name = "menu_book", codePoint = 59929, tags = listOf("book", "catalog", "dictionary", "dining", "directory", "documentation", "education", "food")),
        MaterialSymbolInfo(name = "merge", codePoint = 60312, tags = listOf("arrow", "arrows", "branches", "bring together", "code", "combine", "confluence", "connect")),
        MaterialSymbolInfo(name = "minor_crash", codePoint = 60401, tags = listOf("accident", "alert", "attention", "auto", "automobile", "car", "cars", "caution")),
        MaterialSymbolInfo(name = "miscellaneous_services", codePoint = 61708, tags = listOf()),
        MaterialSymbolInfo(name = "mode_of_travel", codePoint = 59342, tags = listOf("adventure", "air", "arrow", "bicycle", "choice", "commute", "destination", "direction")),
        MaterialSymbolInfo(name = "money", codePoint = 58749, tags = listOf("100", "accounting", "banking", "bill", "budget", "card", "cash", "coin")),
        MaterialSymbolInfo(name = "moped", codePoint = 60200, tags = listOf("automobile", "bike", "buy", "car", "cars", "commerce", "courier", "delivery")),
        MaterialSymbolInfo(name = "mosque", codePoint = 60082, tags = listOf("architecture", "building", "dome", "faith", "holy place", "ideology", "islam", "islamic")),
        MaterialSymbolInfo(name = "moving", codePoint = 58625, tags = listOf("action", "active", "activity", "advancing", "alive", "animate", "arrow", "change")),
        MaterialSymbolInfo(name = "multiple_stop", codePoint = 61881, tags = listOf("action", "arrows", "audio", "button", "complete", "control", "controls", "dash")),
        MaterialSymbolInfo(name = "museum", codePoint = 59958, tags = listOf("ancient", "architecture", "art", "artifact", "attraction", "building", "collection", "columns")),
        MaterialSymbolInfo(name = "my_location", codePoint = 58716, tags = listOf("area", "center location", "circle", "compass", "coordinates", "current location", "destination", "detection")),
        MaterialSymbolInfo(name = "navigation", codePoint = 58717, tags = listOf("arrow", "compass", "course", "destination", "direction", "directions", "discovery", "explore")),
        MaterialSymbolInfo(name = "near_me", codePoint = 58729, tags = listOf("area", "arrow", "compass", "current location", "destination", "direction", "directions", "discover")),
        MaterialSymbolInfo(name = "near_me_disabled", codePoint = 61935, tags = listOf("blocked", "compass blocked", "compass disabled", "compass off", "destination", "direction", "direction blocked", "direction disabled")),
        MaterialSymbolInfo(name = "nightlife", codePoint = 60002, tags = listOf("activity", "alcohol", "bar", "beer", "beverage", "bottle", "celebrate", "cheers")),
        MaterialSymbolInfo(name = "no_crash", codePoint = 60400, tags = listOf("accident", "alert", "auto", "automobile", "avoid", "barrier", "blocked", "car")),
        MaterialSymbolInfo(name = "no_meals", codePoint = 61910, tags = listOf("ban", "catering", "circle", "crossed out", "diet", "dining", "disabled", "eat")),
        MaterialSymbolInfo(name = "no_transfer", codePoint = 61909, tags = listOf("alert", "automobile", "bus", "cancelled", "car", "cars", "circle", "cross out")),
        MaterialSymbolInfo(name = "not_listed_location", codePoint = 58741, tags = listOf("?", "address", "ask", "assistance", "clarity", "destination", "direction", "directory")),
        MaterialSymbolInfo(name = "park", codePoint = 60003, tags = listOf("area", "attraction", "destination", "environment", "fresh", "garden", "green space", "land")),
        MaterialSymbolInfo(name = "pedal_bike", codePoint = 60201, tags = listOf("active", "automobile", "bicycle", "bike", "car", "cars", "chain", "commute")),
        MaterialSymbolInfo(name = "person_pin", codePoint = 58714, tags = listOf("account", "address", "avatar", "circle", "colleague", "contact", "destination", "direction")),
        MaterialSymbolInfo(name = "person_pin_circle", codePoint = 58730, tags = listOf("account", "address", "avatar", "circle", "client", "contact", "current location", "customer")),
        MaterialSymbolInfo(name = "pest_control", codePoint = 61690, tags = listOf("alert", "animal", "block", "bug", "circle", "control", "cross", "diagonal line")),
        MaterialSymbolInfo(name = "pest_control_rodent", codePoint = 61693, tags = listOf("animal", "animal control", "control", "creature", "extermination", "exterminator", "health", "home")),
        MaterialSymbolInfo(name = "pin_drop", codePoint = 58718, tags = listOf("address", "area", "coordinate", "current location", "destination", "direction", "drop", "explore")),
        MaterialSymbolInfo(name = "place", codePoint = 58719, tags = listOf("address", "area", "current location", "destination", "direction", "drop", "find", "geography")),
        MaterialSymbolInfo(name = "plumbing", codePoint = 61703, tags = listOf("build", "commercial", "connections", "construction", "diagram", "domestic", "drainage", "engineering")),
        MaterialSymbolInfo(name = "railway_alert", codePoint = 59857, tags = listOf("!", "alert", "attention", "automobile", "bike", "car", "cars", "caution")),
        MaterialSymbolInfo(name = "ramen_dining", codePoint = 60004, tags = listOf("asian food", "bowl", "chinese food", "chopsticks", "chopsticks in bowl", "cuisine", "delivery", "dining")),
        MaterialSymbolInfo(name = "ramp_left", codePoint = 60316, tags = listOf("arrow", "arrows", "curve", "diagram", "direction", "directional", "directions", "exit")),
        MaterialSymbolInfo(name = "ramp_right", codePoint = 60310, tags = listOf("access", "advance", "angle", "arrow", "arrows", "curve", "diagonal", "direction")),
        MaterialSymbolInfo(name = "rate_review", codePoint = 58720, tags = listOf("assessment", "box", "bubble", "chat bubble", "comment", "comment box", "dialogue", "enter")),
        MaterialSymbolInfo(name = "remove_road", codePoint = 60412, tags = listOf("-", "cancel", "clear", "close", "delete", "destination", "diagonal line", "direction")),
        MaterialSymbolInfo(name = "restaurant", codePoint = 58732, tags = listOf("bar", "breakfast", "breakfast place", "building", "cafe", "cafeteria", "culinary", "cutlery")),
        MaterialSymbolInfo(name = "restaurant_menu", codePoint = 58721, tags = listOf("bistro", "breakfast", "cafe", "catering", "cuisine", "cutlery", "dining", "dining experience")),
        MaterialSymbolInfo(name = "roundabout_left", codePoint = 60313, tags = listOf("arrow", "arrows", "circle", "circular intersection", "curved arrow", "detour", "direction", "directions")),
        MaterialSymbolInfo(name = "roundabout_right", codePoint = 60323, tags = listOf("arrow", "arrows", "circular intersection", "crossroads", "curved arrow", "direction", "direction arrow", "directions")),
        MaterialSymbolInfo(name = "route", codePoint = 60109, tags = listOf("connection", "connection line", "course", "destination", "direction line", "directions", "endpoint", "itinerary")),
        MaterialSymbolInfo(name = "run_circle", codePoint = 61295, tags = listOf("action", "active", "activity", "athletics", "begin", "body", "button", "circle")),
        MaterialSymbolInfo(name = "safety_check", codePoint = 60399, tags = listOf("approved", "authentic", "authentication", "certified", "check", "clock", "confirmed", "confirmed status")),
        MaterialSymbolInfo(name = "sailing", codePoint = 58626, tags = listOf("adventure", "aquatic", "boat", "boating", "cruise", "entertainment", "explore", "fishing")),
        MaterialSymbolInfo(name = "satellite", codePoint = 58722, tags = listOf("antenna", "astronomy", "bluetooth", "broadcast", "communication", "connect", "connection", "connectivity")),
        MaterialSymbolInfo(name = "screen_rotation_alt", codePoint = 60398, tags = listOf("Android", "OS", "adjust", "alter", "alternate", "alternative", "arrow", "change")),
        MaterialSymbolInfo(name = "set_meal", codePoint = 61930, tags = listOf("chopsticks", "cutlery", "dining", "dining etiquette", "dining room", "dinner", "dish", "dishware")),
        MaterialSymbolInfo(name = "signpost", codePoint = 60305, tags = listOf("arrow", "bar", "destination", "direction", "guidance", "guidepost", "horizontal", "indicator")),
        MaterialSymbolInfo(name = "snowmobile", codePoint = 58627, tags = listOf("activity", "adventure", "automobile", "car", "cold", "direction", "driver", "engine")),
        MaterialSymbolInfo(name = "sos", codePoint = 60407, tags = listOf("alert", "box", "button", "communication", "danger", "distress", "element", "emergency")),
        MaterialSymbolInfo(name = "soup_kitchen", codePoint = 59347, tags = listOf("aid", "assistance", "bowl", "breakfast", "brunch", "care", "charity", "community")),
        MaterialSymbolInfo(name = "stadium", codePoint = 60304, tags = listOf("activity", "amphitheater", "architecture", "arena", "audience", "bleachers", "building", "coliseum")),
        MaterialSymbolInfo(name = "store_mall_directory", codePoint = 58723, tags = listOf("address", "aisle", "building", "business", "buying", "commerce", "commercial", "destination")),
        MaterialSymbolInfo(name = "straight", codePoint = 60309, tags = listOf("abstract", "abstract shape", "arrow", "arrows", "bar", "basic shape", "dash", "direction")),
        MaterialSymbolInfo(name = "streetview", codePoint = 58734, tags = listOf("360 degrees", "angle", "camera", "environment", "explore", "eye", "globe", "immersive")),
        MaterialSymbolInfo(name = "subway", codePoint = 58735, tags = listOf("automobile", "bike", "car", "cars", "city", "city transport", "commute", "line"))
    )
}

internal val materialSymbols_maps_chunk4: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "synagogue", codePoint = 60080, tags = listOf("architecture", "building", "church", "city", "community", "dome", "faith", "hebrew")),
        MaterialSymbolInfo(name = "takeout_dining", codePoint = 60020, tags = listOf("box", "catering", "container", "cutlery", "delivery", "dining", "dining out", "eating")),
        MaterialSymbolInfo(name = "taxi_alert", codePoint = 61300, tags = listOf("!", "alarm", "alert", "attention", "automobile", "cab", "car", "cars")),
        MaterialSymbolInfo(name = "temple_buddhist", codePoint = 60083, tags = listOf("architecture", "asia", "asian", "buddha", "buddhism", "buddhist", "building", "cultural")),
        MaterialSymbolInfo(name = "temple_hindu", codePoint = 60079, tags = listOf("ancient", "architecture", "asian", "building", "culture", "destination", "graphic", "hindu")),
        MaterialSymbolInfo(name = "terrain", codePoint = 58724, tags = listOf("chart", "contour", "data", "diagram", "elevation", "environment", "geography", "graphic")),
        MaterialSymbolInfo(name = "theater_comedy", codePoint = 60006, tags = listOf("acting", "art", "broadway", "comedian", "comedy", "culture", "drama", "emotion")),
        MaterialSymbolInfo(name = "tire_repair", codePoint = 60360, tags = listOf("alert", "assistance", "auto", "automobile", "automotive", "car", "cars", "circular")),
        MaterialSymbolInfo(name = "traffic", codePoint = 58725, tags = listOf("accident", "barrier", "block", "car", "caution", "cone", "construction", "detour")),
        MaterialSymbolInfo(name = "train", codePoint = 58736, tags = listOf("automobile", "car", "cargo", "cars", "commute", "destination", "diesel", "direction")),
        MaterialSymbolInfo(name = "tram", codePoint = 58737, tags = listOf("automobile", "cable car", "car", "cars", "city", "city icon", "city transport", "commute")),
        MaterialSymbolInfo(name = "transfer_within_a_station", codePoint = 58738, tags = listOf("a", "arrow", "arrows", "body", "bus", "commute", "connection", "destination")),
        MaterialSymbolInfo(name = "transit_enterexit", codePoint = 58745, tags = listOf("access", "arrival", "arrow", "bus", "commute", "departure", "direction", "directional")),
        MaterialSymbolInfo(name = "trip_origin", codePoint = 58747, tags = listOf("address", "beginning", "circle", "departure", "destination", "direction", "dot", "geo")),
        MaterialSymbolInfo(name = "turn_left", codePoint = 60326, tags = listOf("angle", "arrow", "arrows", "bend", "curve", "direction", "directions", "driving")),
        MaterialSymbolInfo(name = "turn_right", codePoint = 60331, tags = listOf("arrow", "arrows", "bend right", "changing direction", "curved arrow", "direction", "directions", "driving")),
        MaterialSymbolInfo(name = "turn_sharp_left", codePoint = 60327, tags = listOf("angle", "arrow", "arrows", "bend", "curve", "detour", "direction", "directions")),
        MaterialSymbolInfo(name = "turn_sharp_right", codePoint = 60330, tags = listOf("acute turn", "arrow", "arrows", "car", "curve", "detour", "direction", "directions")),
        MaterialSymbolInfo(name = "turn_slight_left", codePoint = 60324, tags = listOf("angle", "arrow", "arrows", "bend", "change direction", "corner", "curve", "direction")),
        MaterialSymbolInfo(name = "turn_slight_right", codePoint = 60314, tags = listOf("arrow", "arrows", "bend", "curve", "detour", "direction", "directions", "driving")),
        MaterialSymbolInfo(name = "two_wheeler", codePoint = 59897, tags = listOf("automobile", "bike", "car", "cars", "commuting", "delivery", "direction", "driver")),
        MaterialSymbolInfo(name = "u_turn_left", codePoint = 60321, tags = listOf("arrow", "arrows", "bend", "change direction", "circle", "curve", "direction", "directions")),
        MaterialSymbolInfo(name = "u_turn_right", codePoint = 60322, tags = listOf("arrow", "arrows", "bend", "car", "change direction", "curve", "curved arrow", "direction")),
        MaterialSymbolInfo(name = "volunteer_activism", codePoint = 60016, tags = listOf("activism", "aid", "assistance", "care", "cause", "charity", "community", "compassion")),
        MaterialSymbolInfo(name = "warehouse", codePoint = 60344, tags = listOf("architecture", "building", "business", "cargo", "commercial", "delivery", "depot", "distribution")),
        MaterialSymbolInfo(name = "wine_bar", codePoint = 61928, tags = listOf("alcohol", "alcohol consumption", "bar", "bar icon", "beverage", "cafe", "celebration", "cheers")),
        MaterialSymbolInfo(name = "wrong_location", codePoint = 61304, tags = listOf("address", "alert", "cancel", "caution", "clear", "close", "cross", "denied")),
        MaterialSymbolInfo(name = "zoom_in_map", codePoint = 60205, tags = listOf("add", "arrow", "arrows", "cartography", "center", "close up", "destination", "detail")),
        MaterialSymbolInfo(name = "zoom_out_map", codePoint = 58731, tags = listOf("area", "arrow", "arrows", "box", "button", "center", "compass", "contract"))
    )
}

internal val materialSymbols_maps_category: MaterialSymbolCategory by lazy(LazyThreadSafetyMode.NONE) {
    MaterialSymbolCategory(
        key = "maps",
        icons = buildList {
            addAll(materialSymbols_maps_chunk1)
            addAll(materialSymbols_maps_chunk2)
            addAll(materialSymbols_maps_chunk3)
            addAll(materialSymbols_maps_chunk4)
        }
    )
}
