package com.example.itemmanagement.ui.components

import kotlin.LazyThreadSafetyMode

internal val materialSymbols_device_chunk1: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "1x_mobiledata", codePoint = 61389, tags = listOf("1x", "1x signal", "alphabet", "cell signal", "cellular", "cellular data", "character", "connection status")),
        MaterialSymbolInfo(name = "30fps", codePoint = 61390, tags = listOf("30fps", "alphabet", "camera", "character", "digit", "film", "font", "fps")),
        MaterialSymbolInfo(name = "3g_mobiledata", codePoint = 61392, tags = listOf("3g", "alphabet", "bandwidth", "bars", "broadband", "cellular", "character", "communication")),
        MaterialSymbolInfo(name = "4g_mobiledata", codePoint = 61394, tags = listOf("4g", "alphabet", "bandwidth", "cellular", "cellular data", "character", "communication", "connection")),
        MaterialSymbolInfo(name = "4g_plus_mobiledata", codePoint = 61395, tags = listOf("4g", "4g plus", "4g+", "advanced data", "alphabet", "carrier", "cell phone", "cellular")),
        MaterialSymbolInfo(name = "60fps", codePoint = 61396, tags = listOf("60fps", "camera", "capture", "cinema", "control", "definition", "digit", "display")),
        MaterialSymbolInfo(name = "access_alarm", codePoint = 57744, tags = listOf("access", "adjust", "alarm", "alert", "appointment", "bell", "calendar", "circle")),
        MaterialSymbolInfo(name = "access_alarms", codePoint = 57745, tags = listOf("access", "adjust", "alarm", "alert", "appointment", "bell", "calendar", "circle")),
        MaterialSymbolInfo(name = "access_time", codePoint = 57746, tags = listOf("alarm", "appointment", "calendar", "chronometer", "clock", "countdown", "date", "deadline")),
        MaterialSymbolInfo(name = "access_time_filled", codePoint = 61398, tags = listOf("alarm", "appointment", "calendar", "chronometer", "clock", "countdown", "date", "deadline")),
        MaterialSymbolInfo(name = "ad_units", codePoint = 61241, tags = listOf("Android", "OS", "ad", "ad units", "advertising", "article", "banner", "block")),
        MaterialSymbolInfo(name = "add_alarm", codePoint = 57747, tags = listOf("add", "add alarm", "alarm", "alert", "app", "appointment", "audio", "bell")),
        MaterialSymbolInfo(name = "add_to_home_screen", codePoint = 57854, tags = listOf("Android", "OS", "add", "add to", "add to homescreen", "app", "application", "arrow")),
        MaterialSymbolInfo(name = "air", codePoint = 61400, tags = listOf("abstract", "air", "atmospheric", "blowing", "breath", "breeze", "climate", "cooling")),
        MaterialSymbolInfo(name = "airplane_ticket", codePoint = 61401, tags = listOf("admit", "air", "air ticket", "aircraft", "airplane", "airplane ticket", "airplanes", "airport")),
        MaterialSymbolInfo(name = "airplanemode_active", codePoint = 57749, tags = listOf("active", "air", "air travel", "aircraft", "airplane", "airplane icon", "airplane mode", "airplanes")),
        MaterialSymbolInfo(name = "airplanemode_inactive", codePoint = 57748, tags = listOf("air", "aircraft", "airplane", "airplane mode", "airplanes", "airport", "aviation", "communications")),
        MaterialSymbolInfo(name = "aod", codePoint = 61402, tags = listOf("Android", "OS", "abstract", "alert", "always", "always on display", "ambient display", "ambient mode")),
        MaterialSymbolInfo(name = "battery_0_bar", codePoint = 60380, tags = listOf("alert", "bar", "battery", "cell", "charge", "critical", "device", "electric")),
        MaterialSymbolInfo(name = "battery_1_bar", codePoint = 60377, tags = listOf("1 bar", "20 percent", "20%", "bar", "battery", "cell", "charge", "charging")),
        MaterialSymbolInfo(name = "battery_2_bar", codePoint = 60384, tags = listOf("2 bars", "30 percent", "bar", "battery", "battery indicator", "battery level", "cell", "charge")),
        MaterialSymbolInfo(name = "battery_3_bar", codePoint = 60381, tags = listOf("50%", "bar", "battery", "battery gauge", "battery icon", "battery indicator", "battery meter", "battery status")),
        MaterialSymbolInfo(name = "battery_4_bar", codePoint = 60386, tags = listOf("60", "almost full", "bar", "bars", "battery", "capacity", "cell", "charge")),
        MaterialSymbolInfo(name = "battery_5_bar", codePoint = 60372, tags = listOf("80%", "bars", "battery", "cell", "charge", "charging", "device", "electric")),
        MaterialSymbolInfo(name = "battery_6_bar", codePoint = 60370, tags = listOf("90", "almost full", "bar", "bars", "battery", "battery status", "cell", "charge")),
        MaterialSymbolInfo(name = "battery_alert", codePoint = 57756, tags = listOf("!", "alert", "attention", "battery", "caution", "cell", "charge", "critical")),
        MaterialSymbolInfo(name = "battery_charging_full", codePoint = 57763, tags = listOf("battery", "bolt", "capacity", "cell", "charge", "charged", "charging", "charging up")),
        MaterialSymbolInfo(name = "battery_full", codePoint = 57764, tags = listOf("bar", "battery", "battery icon", "battery level", "battery meter", "cell", "charge", "device")),
        MaterialSymbolInfo(name = "battery_saver", codePoint = 61406, tags = listOf("+", "add", "addition", "bar", "battery", "charge", "charging", "configuration")),
        MaterialSymbolInfo(name = "battery_std", codePoint = 57765, tags = listOf("bar", "battery", "battery icon", "battery level", "battery meter", "cell", "charge", "device")),
        MaterialSymbolInfo(name = "battery_unknown", codePoint = 57766, tags = listOf("?", "assistance", "battery", "cell", "charge", "device", "electricity", "element")),
        MaterialSymbolInfo(name = "bloodtype", codePoint = 61412, tags = listOf("abstract", "analysis", "blood", "blood type", "bloodtype", "donate", "donation", "droplet")),
        MaterialSymbolInfo(name = "bluetooth", codePoint = 57767, tags = listOf("audio", "bluetooth", "cast", "communication", "connect", "connection", "connectivity", "data")),
        MaterialSymbolInfo(name = "bluetooth_connected", codePoint = 57768, tags = listOf("audio", "bluetooth", "bluetooth icon", "cast", "communication", "communication technology", "connect", "connected")),
        MaterialSymbolInfo(name = "bluetooth_disabled", codePoint = 57769, tags = listOf("audio", "bluetooth", "cast", "communication", "connect", "connection", "connectivity", "cross")),
        MaterialSymbolInfo(name = "bluetooth_drive", codePoint = 61413, tags = listOf("automobile", "bluetooth", "car", "cars", "cast", "communication", "computer", "connect")),
        MaterialSymbolInfo(name = "bluetooth_searching", codePoint = 57770, tags = listOf("audio", "bluetooth", "communication", "connecting", "connection", "connectivity", "data", "device")),
        MaterialSymbolInfo(name = "brightness_auto", codePoint = 57771, tags = listOf("A", "adjust", "adjustment", "ambient light", "auto", "auto adjust", "automatic", "automatic brightness")),
        MaterialSymbolInfo(name = "brightness_high", codePoint = 57772, tags = listOf("adjust", "adjustment", "auto", "beam", "brightness", "circle", "control", "display")),
        MaterialSymbolInfo(name = "brightness_low", codePoint = 57773, tags = listOf("adjust", "auto", "battery", "brightness", "brightness low", "circle", "control", "dark")),
        MaterialSymbolInfo(name = "brightness_medium", codePoint = 57774, tags = listOf("adjustment", "auto", "brightness", "circle", "configuration", "control", "dial", "display")),
        MaterialSymbolInfo(name = "cable", codePoint = 61414, tags = listOf("analog", "cable", "communication", "component", "connect", "connection", "connector", "cord")),
        MaterialSymbolInfo(name = "cameraswitch", codePoint = 61419, tags = listOf("arrow", "arrows", "back camera", "camera", "camera switch", "camera toggle", "cameraswitch", "change camera")),
        MaterialSymbolInfo(name = "credit_score", codePoint = 61425, tags = listOf("analysis", "approve", "assessment", "banking", "bill", "card", "cash", "check")),
        MaterialSymbolInfo(name = "dark_mode", codePoint = 58652, tags = listOf("accessibility", "ambient", "app", "appearance", "application", "atmosphere", "bedtime", "circle")),
        MaterialSymbolInfo(name = "data_saver_off", codePoint = 61426, tags = listOf("analytics", "bar", "bars", "blocking", "canceled", "cellular", "chart", "configuration")),
        MaterialSymbolInfo(name = "data_saver_on", codePoint = 61427, tags = listOf("+", "active", "add", "analytics", "arrow", "bandwidth", "bandwidth saver", "chart")),
        MaterialSymbolInfo(name = "data_usage", codePoint = 57775, tags = listOf("analytics", "blocking", "canceled", "cellular", "chart", "configuration", "connectivity", "consumption")),
        MaterialSymbolInfo(name = "dataset", codePoint = 63726, tags = listOf("archive", "cloud", "collection", "columns", "data", "data entry", "data management", "database")),
        MaterialSymbolInfo(name = "dataset_linked", codePoint = 63727, tags = listOf("browser", "chain", "chain link", "connect", "connected", "connection", "data", "document")),
        MaterialSymbolInfo(name = "developer_mode", codePoint = 57776, tags = listOf("Android", "OS", "advanced settings", "angle bracket", "bracket", "cell", "code", "coding")),
        MaterialSymbolInfo(name = "device_thermostat", codePoint = 57855, tags = listOf("adjust", "automation", "celsius", "circle", "climate", "comfort", "control", "cooling")),
        MaterialSymbolInfo(name = "devices", codePoint = 57777, tags = listOf("Android", "OS", "cast", "communication", "computer", "connect", "connection", "connectivity")),
        MaterialSymbolInfo(name = "devices_fold", codePoint = 60382, tags = listOf("Android", "OS", "cell", "closed", "computer", "dash", "dashed", "device")),
        MaterialSymbolInfo(name = "discount", codePoint = 60361, tags = listOf()),
        MaterialSymbolInfo(name = "do_not_disturb_on_total_silence", codePoint = 61435, tags = listOf("alert", "ban", "bell", "blocked", "busy", "circle", "communication", "diagonal line")),
        MaterialSymbolInfo(name = "dvr", codePoint = 57778, tags = listOf("Android", "OS", "VCR", "archives", "audio", "box", "broadcast", "chrome")),
        MaterialSymbolInfo(name = "e_mobiledata", codePoint = 61442, tags = listOf("alphabet", "bars", "cell", "cell service", "cellular", "cellular data", "cellular network", "connection")),
        MaterialSymbolInfo(name = "edgesensor_high", codePoint = 61445, tags = listOf("Android", "OS", "bar", "bars", "cell", "cell signal", "connection", "data")),
        MaterialSymbolInfo(name = "edgesensor_low", codePoint = 61446, tags = listOf("Android", "OS", "alert", "antenna", "bars", "cell", "cellular", "connection"))
    )
}

internal val materialSymbols_device_chunk2: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "flashlight_off", codePoint = 61450, tags = listOf("beam off", "brightness.", "button", "control", "dark", "deactivate", "device", "disabled")),
        MaterialSymbolInfo(name = "flashlight_on", codePoint = 61451, tags = listOf("activated", "beam", "bright", "button", "camping", "circle", "cone of light", "conical")),
        MaterialSymbolInfo(name = "fluorescent", codePoint = 60465, tags = listOf("adjustments", "bright", "brightness", "camera", "effects", "electric", "electricity", "energy")),
        MaterialSymbolInfo(name = "fmd_bad", codePoint = 61454, tags = listOf("!", "address", "alert", "attention", "bad", "blocked", "caution", "cross")),
        MaterialSymbolInfo(name = "fmd_good", codePoint = 61455, tags = listOf("address", "area", "current location", "destination", "direction", "drop", "find", "fmd")),
        MaterialSymbolInfo(name = "g_mobiledata", codePoint = 61456, tags = listOf("alphabet", "bars", "cell service", "cellular", "character", "communication", "connection", "connectivity")),
        MaterialSymbolInfo(name = "gpp_bad", codePoint = 61458, tags = listOf("access denied", "alert", "bad", "blocked", "cancel", "certified", "close", "cross")),
        MaterialSymbolInfo(name = "gpp_good", codePoint = 61459, tags = listOf("badge", "certified", "check", "complete", "confirmation", "data", "endorsed", "excellent")),
        MaterialSymbolInfo(name = "gpp_maybe", codePoint = 61460, tags = listOf("!", "alert", "attention", "authenticate", "authentication", "caution", "certified", "check")),
        MaterialSymbolInfo(name = "gps_fixed", codePoint = 57779, tags = listOf("area", "center location", "circle", "compass", "coordinates", "current location", "destination", "detection")),
        MaterialSymbolInfo(name = "gps_not_fixed", codePoint = 57780, tags = listOf("acquire", "acquiring", "coordinates", "current location", "destination", "direction", "disabled", "enabled")),
        MaterialSymbolInfo(name = "gps_off", codePoint = 57781, tags = listOf("access denied", "alert", "blocked", "circle", "cross", "deny", "destination", "diagonal line")),
        MaterialSymbolInfo(name = "graphic_eq", codePoint = 57784, tags = listOf("audio", "audio analysis", "audio control", "audio customization", "audio effect", "audio icon", "audio mixer", "audio settings")),
        MaterialSymbolInfo(name = "grid_3x3", codePoint = 61461, tags = listOf("3", "3x3 grid", "album view", "area", "arrange", "blocks", "cells", "dashboard")),
        MaterialSymbolInfo(name = "grid_4x4", codePoint = 61462, tags = listOf("4", "4x4", "arrangement", "block", "by", "cells", "collection", "columns")),
        MaterialSymbolInfo(name = "grid_goldenratio", codePoint = 61463, tags = listOf("aesthetic", "alignment", "arrangement", "art", "balance", "composition", "composition guide", "design")),
        MaterialSymbolInfo(name = "h_mobiledata", codePoint = 61464, tags = listOf("4g", "alphabet", "alphanumeric", "cellular", "cellular connection", "cellular data", "character", "communication")),
        MaterialSymbolInfo(name = "h_plus_mobiledata", codePoint = 61465, tags = listOf("+", "3g", "4g", "access", "alphabet", "broadband", "cellular", "cellular data")),
        MaterialSymbolInfo(name = "hdr_auto", codePoint = 61466, tags = listOf("A", "adjustment", "alphabet", "auto", "automatic", "button", "camera", "character")),
        MaterialSymbolInfo(name = "hdr_auto_select", codePoint = 61467, tags = listOf("+", "A", "adjustment", "alphabet", "auto", "automatic", "button", "camera")),
        MaterialSymbolInfo(name = "hdr_off_select", codePoint = 61468, tags = listOf("alphabet", "border", "camera", "cancel", "character", "circle", "control", "disabled")),
        MaterialSymbolInfo(name = "hdr_on_select", codePoint = 61469, tags = listOf("+", "alphabet", "bright", "button", "camera", "character", "cinema", "circle")),
        MaterialSymbolInfo(name = "lan", codePoint = 60207, tags = listOf("access", "business", "communication", "communications", "computer", "computers", "connected", "connection")),
        MaterialSymbolInfo(name = "lens_blur", codePoint = 61481, tags = listOf("abstract", "aperture", "artistic effect", "blur", "bokeh", "camera", "camera lens", "circle")),
        MaterialSymbolInfo(name = "light_mode", codePoint = 58648, tags = listOf("adjustment", "appearance", "application", "bright", "brightness", "celestial body", "circle", "clear")),
        MaterialSymbolInfo(name = "location_disabled", codePoint = 57782, tags = listOf("access denied", "alert", "blocked", "circle", "cross", "deny", "destination", "diagonal line")),
        MaterialSymbolInfo(name = "location_searching", codePoint = 57783, tags = listOf("acquire", "acquiring", "coordinates", "current location", "destination", "direction", "finding", "gps")),
        MaterialSymbolInfo(name = "lte_mobiledata", codePoint = 61484, tags = listOf("access", "alphabet", "bar", "bars", "broadband", "cellular", "character", "communications")),
        MaterialSymbolInfo(name = "lte_plus_mobiledata", codePoint = 61485, tags = listOf("+", "alphabet", "cell", "character", "characters", "communication", "connection", "data")),
        MaterialSymbolInfo(name = "macro_off", codePoint = 63698, tags = listOf("camera", "camera off", "camera settings", "circle", "close-up off", "controls", "deactivate", "detailed view off")),
        MaterialSymbolInfo(name = "media_bluetooth_off", codePoint = 61489, tags = listOf("audio", "bluetooth", "communication", "connect", "connection", "connection off", "connectivity", "cross")),
        MaterialSymbolInfo(name = "media_bluetooth_on", codePoint = 61490, tags = listOf("active", "audio", "bluetooth", "communication", "computer", "connect", "connected", "connection")),
        MaterialSymbolInfo(name = "medication", codePoint = 61491, tags = listOf("capsule", "doctor", "drug", "drug icon", "emergency", "health", "healthcare", "healthcare icon")),
        MaterialSymbolInfo(name = "medication_liquid", codePoint = 60039, tags = listOf("+", "bottle", "container", "cough syrup", "cure", "doctor", "dosage", "drop")),
        MaterialSymbolInfo(name = "mobile_friendly", codePoint = 57856, tags = listOf("Android", "OS", "approve", "approved", "cell", "check", "checkmark", "complete")),
        MaterialSymbolInfo(name = "mobile_off", codePoint = 57857, tags = listOf("Android", "OS", "access", "airplane mode", "barred", "cell", "cell off", "communication")),
        MaterialSymbolInfo(name = "mobiledata_off", codePoint = 61492, tags = listOf("arrow", "cellular", "cellular connection off", "cellular data off", "cellular network off", "connection lost", "connectivity off", "cross")),
        MaterialSymbolInfo(name = "mode_night", codePoint = 61494, tags = listOf("adjust", "adjustment", "brightness", "contrast", "control", "crescent", "dark", "dim")),
        MaterialSymbolInfo(name = "mode_standby", codePoint = 61495, tags = listOf("button", "control", "control element", "device", "disturb", "electronics", "energy saver", "energy saving")),
        MaterialSymbolInfo(name = "monitor_heart", codePoint = 60066, tags = listOf("baseline", "cardiogram", "care", "computer", "device", "diagnostics", "digital health", "display")),
        MaterialSymbolInfo(name = "monitor_weight", codePoint = 61497, tags = listOf("accuracy", "analysis", "balance", "body", "body composition", "body weight", "calibration", "check")),
        MaterialSymbolInfo(name = "nearby_error", codePoint = 61499, tags = listOf("!", "alert", "attention", "caution", "communication", "connection", "danger", "detection")),
        MaterialSymbolInfo(name = "nearby_off", codePoint = 61500, tags = listOf("area", "circle", "close", "connected off", "connection", "cross out", "detection", "disabled")),
        MaterialSymbolInfo(name = "network_cell", codePoint = 57785, tags = listOf("bars", "cell", "cellular", "communications", "connection", "connectivity", "data", "full signal")),
        MaterialSymbolInfo(name = "network_wifi", codePoint = 57786, tags = listOf("access", "antenna", "arcs", "available", "bars", "broadcast", "cell", "cellular")),
        MaterialSymbolInfo(name = "network_wifi_1_bar", codePoint = 60388, tags = listOf("access point", "antenna", "bar", "cell", "cellular", "communication", "communication link", "connection")),
        MaterialSymbolInfo(name = "network_wifi_2_bar", codePoint = 60374, tags = listOf("access point", "antenna", "arc", "bars", "broadcast", "cell", "cellular", "communication")),
        MaterialSymbolInfo(name = "network_wifi_3_bar", codePoint = 60385, tags = listOf("access", "antenna", "arc", "bars", "cell", "cellular", "communication", "connected")),
        MaterialSymbolInfo(name = "nfc", codePoint = 57787, tags = listOf("access", "button", "communication", "connect", "contactless", "data", "device", "element")),
        MaterialSymbolInfo(name = "nightlight", codePoint = 61501, tags = listOf("astronomy", "bedtime", "brightness", "celestial", "circle", "crescent", "dark", "display")),
        MaterialSymbolInfo(name = "note_alt", codePoint = 61504, tags = listOf("alt", "article", "clipboard", "compose", "content", "copy", "create", "cut")),
        MaterialSymbolInfo(name = "password", codePoint = 61506, tags = listOf("access", "access code", "account", "authentication", "authorization", "code", "credentials", "data protection")),
        MaterialSymbolInfo(name = "pattern", codePoint = 61507, tags = listOf("abstract", "appearance", "arrangement", "background", "background design", "composition", "decoration", "decorative element")),
        MaterialSymbolInfo(name = "phishing", codePoint = 60119, tags = listOf("alert", "attack", "block", "caution", "crime", "cyber security", "cybercrime", "danger")),
        MaterialSymbolInfo(name = "pin", codePoint = 61509, tags = listOf("1", "2", "3", "address", "cartography", "destination", "digit", "directional")),
        MaterialSymbolInfo(name = "play_lesson", codePoint = 61511, tags = listOf("academic", "audio", "book", "bookmark", "button", "class", "continue", "course")),
        MaterialSymbolInfo(name = "price_change", codePoint = 61514, tags = listOf("analysis", "arrow", "arrows", "bill", "card", "cash", "change", "chart")),
        MaterialSymbolInfo(name = "price_check", codePoint = 61515, tags = listOf("approve", "barcode scanner", "bill", "card", "cash", "check", "check price", "coin")),
        MaterialSymbolInfo(name = "punch_clock", codePoint = 60072, tags = listOf("attendance", "attendance tracking", "business", "clock", "clock in", "clock out", "date", "employee tracking")),
        MaterialSymbolInfo(name = "quiz", codePoint = 61516, tags = listOf("?", "academic", "answer", "assessment", "assistance", "certification", "challenge", "clipboard"))
    )
}

internal val materialSymbols_device_chunk3: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "r_mobiledata", codePoint = 61517, tags = listOf("alphabet", "bars", "cell", "cellular", "cellular data", "character", "communication", "connection")),
        MaterialSymbolInfo(name = "radar", codePoint = 61518, tags = listOf("area", "broadcast", "circle", "cone", "detect", "detection", "discovery", "expanding")),
        MaterialSymbolInfo(name = "remember_me", codePoint = 61521, tags = listOf("Android", "OS", "account", "authentication", "avatar", "boolean", "checkbox", "checked")),
        MaterialSymbolInfo(name = "reset_tv", codePoint = 59865, tags = listOf("arrow", "arrows", "back", "button", "circle", "circular arrow", "control", "cycle")),
        MaterialSymbolInfo(name = "restart_alt", codePoint = 61523, tags = listOf("alt", "around", "arrow", "begin again", "circular", "curved", "cycle", "inprogress")),
        MaterialSymbolInfo(name = "reviews", codePoint = 61524, tags = listOf("approve", "attempt", "best", "bubble", "chat", "comment", "communicate", "evaluation")),
        MaterialSymbolInfo(name = "rsvp", codePoint = 61525, tags = listOf("accept", "accepted", "acknowledged", "affirmed", "agree", "alphabet", "attendance", "attended")),
        MaterialSymbolInfo(name = "screen_lock_landscape", codePoint = 57790, tags = listOf("Android", "OS", "access", "device", "device lock", "display", "hardware", "horizontal")),
        MaterialSymbolInfo(name = "screen_lock_portrait", codePoint = 57791, tags = listOf("Android", "OS", "access", "access control", "authentication", "cell", "cell phone", "connection")),
        MaterialSymbolInfo(name = "screen_lock_rotation", codePoint = 57792, tags = listOf("Android", "OS", "access", "accessibility", "arrow", "circle", "clockwise", "control")),
        MaterialSymbolInfo(name = "screen_rotation", codePoint = 57793, tags = listOf("Android", "OS", "adjust", "arrow", "arrows", "circle", "circular", "clockwise")),
        MaterialSymbolInfo(name = "screen_search_desktop", codePoint = 61296, tags = listOf("Android", "OS", "application", "arrow", "browser", "computer", "desktop", "device")),
        MaterialSymbolInfo(name = "screenshot", codePoint = 61526, tags = listOf("Android", "OS", "app", "application", "art", "camera", "capture", "cell")),
        MaterialSymbolInfo(name = "screenshot_monitor", codePoint = 60424, tags = listOf("Android", "OS", "application", "camera", "capture", "chrome", "computer", "desktop")),
        MaterialSymbolInfo(name = "sd_storage", codePoint = 57794, tags = listOf("angled corner", "camera", "card", "computer", "data", "data storage", "device", "digital")),
        MaterialSymbolInfo(name = "security_update", codePoint = 61528, tags = listOf("Android", "OS", "app", "app install", "app promo", "arrow", "device", "down")),
        MaterialSymbolInfo(name = "security_update_good", codePoint = 61529, tags = listOf("Android", "OS", "approve", "approved", "cell", "check", "checkmark", "complete")),
        MaterialSymbolInfo(name = "security_update_warning", codePoint = 61530, tags = listOf("!", "Android", "OS", "alert", "attention", "bug", "caution", "critical")),
        MaterialSymbolInfo(name = "sell", codePoint = 61531, tags = listOf("bargain", "bill", "card", "cart", "cash", "coin", "commerce", "coupon")),
        MaterialSymbolInfo(name = "send_to_mobile", codePoint = 61532, tags = listOf("Android", "OS", "abstract", "action", "arrow", "cellular", "communication", "connect")),
        MaterialSymbolInfo(name = "settings_suggest", codePoint = 61534, tags = listOf("adjust", "administration", "advise", "ai", "artificial", "assist", "asterisk", "automatic")),
        MaterialSymbolInfo(name = "settings_system_daydream", codePoint = 57795, tags = listOf("adjustment", "backup", "cloud", "configuration", "control", "daydream", "device", "digital")),
        MaterialSymbolInfo(name = "share_location", codePoint = 61535, tags = listOf("address", "area", "broadcast", "communicate", "connect", "coordinates", "dash", "dashed")),
        MaterialSymbolInfo(name = "shortcut", codePoint = 61536, tags = listOf("arrow", "communication", "content sharing", "direction", "forward", "forward icon", "google plus", "google plus share")),
        MaterialSymbolInfo(name = "signal_cellular_0_bar", codePoint = 61608, tags = listOf("0", "0 bars", "antenna", "bad signal", "bar", "bars", "bars indicator", "cell")),
        MaterialSymbolInfo(name = "signal_cellular_4_bar", codePoint = 57800, tags = listOf("0", "bar", "bars", "bars increasing", "cell", "cellular", "communication", "connection")),
        MaterialSymbolInfo(name = "signal_cellular_alt", codePoint = 57858, tags = listOf("alt", "analytics", "ascending bars", "bar", "bars", "cell", "cellular", "chart")),
        MaterialSymbolInfo(name = "signal_cellular_alt_1_bar", codePoint = 60383, tags = listOf("1 bar", "alt", "analytics", "antenna", "bar", "bars", "cell", "cell signal")),
        MaterialSymbolInfo(name = "signal_cellular_alt_2_bar", codePoint = 60387, tags = listOf("alt", "analytics", "bar", "bars", "bars up", "cell", "cellular", "chart")),
        MaterialSymbolInfo(name = "signal_cellular_connected_no_internet_0_bar", codePoint = 61612, tags = listOf("!", "0", "0 bars", "alert", "attention", "bar", "bars", "caution")),
        MaterialSymbolInfo(name = "signal_cellular_connected_no_internet_4_bar", codePoint = 57805, tags = listOf("!", "4", "4 bars", "alert", "attention", "bar", "bars", "caution")),
        MaterialSymbolInfo(name = "signal_cellular_no_sim", codePoint = 57806, tags = listOf("absent", "alert", "bar", "bars", "camera", "card", "cellular", "chip")),
        MaterialSymbolInfo(name = "signal_cellular_nodata", codePoint = 61538, tags = listOf("antenna", "ascending", "bars", "cell", "cellular", "clear", "communication", "connection")),
        MaterialSymbolInfo(name = "signal_cellular_null", codePoint = 57807, tags = listOf("alert", "bars", "cell", "cellular", "communication", "connection", "connectivity", "data")),
        MaterialSymbolInfo(name = "signal_cellular_off", codePoint = 57808, tags = listOf("antenna", "bars", "cell", "cellular", "communication", "communication status", "connection", "data")),
        MaterialSymbolInfo(name = "signal_wifi_0_bar", codePoint = 61616, tags = listOf("0", "access", "arc", "bar", "cell", "cellular", "communication", "connection")),
        MaterialSymbolInfo(name = "signal_wifi_4_bar", codePoint = 57816, tags = listOf("4", "available", "bar", "bars", "cell", "cellular", "communication", "connected")),
        MaterialSymbolInfo(name = "signal_wifi_4_bar_lock", codePoint = 57817, tags = listOf("4", "access", "authentication", "bar", "bars", "cell", "cellular", "connect")),
        MaterialSymbolInfo(name = "signal_wifi_bad", codePoint = 61539, tags = listOf("access", "arc", "bad", "bar", "bars", "cancel", "cell", "cellular")),
        MaterialSymbolInfo(name = "signal_wifi_connected_no_internet_4", codePoint = 61540, tags = listOf("4", "access", "arc", "bad", "bars", "cell", "cellular", "communication")),
        MaterialSymbolInfo(name = "signal_wifi_off", codePoint = 57818, tags = listOf("alert", "antenna", "arcs", "bars", "cell", "cellular", "communication", "connection off")),
        MaterialSymbolInfo(name = "signal_wifi_statusbar_4_bar", codePoint = 61541, tags = listOf("4", "available", "bar", "bars", "cell", "cellular", "communication", "connected")),
        MaterialSymbolInfo(name = "signal_wifi_statusbar_connected_no_internet_4", codePoint = 61542, tags = listOf("!", "4", "alert", "attention", "caution", "cell", "cellular", "connected")),
        MaterialSymbolInfo(name = "signal_wifi_statusbar_null", codePoint = 61543, tags = listOf("access", "arc", "bar", "cell", "cellular", "communication", "connection", "connectivity")),
        MaterialSymbolInfo(name = "sim_card_download", codePoint = 61544, tags = listOf("arrow", "button", "camera", "card", "cellular", "chip", "communication", "connection")),
        MaterialSymbolInfo(name = "splitscreen", codePoint = 61549, tags = listOf("arrangement", "arrangement of elements", "column", "display", "divide", "dual screen", "grid", "horizontal split")),
        MaterialSymbolInfo(name = "sports_score", codePoint = 61550, tags = listOf("athletics", "competition", "destination", "display", "final score", "flag", "game", "game score")),
        MaterialSymbolInfo(name = "ssid_chart", codePoint = 60262, tags = listOf("analysis", "analytics", "bars", "chart", "communication", "connection", "connectivity", "data")),
        MaterialSymbolInfo(name = "storage", codePoint = 57819, tags = listOf("archive", "backup", "boxes", "capacity", "cloud", "computer", "computing", "data")),
        MaterialSymbolInfo(name = "storm", codePoint = 61552, tags = listOf("abstract", "alert", "angular", "bad weather", "bolt", "climate", "crackle", "danger")),
        MaterialSymbolInfo(name = "summarize", codePoint = 61553, tags = listOf("arrows", "aspect ratio", "button", "control", "corners", "corners out", "display", "doc")),
        MaterialSymbolInfo(name = "system_security_update", codePoint = 61554, tags = listOf("Android", "OS", "app", "app install", "app promo", "arrow", "cell", "device")),
        MaterialSymbolInfo(name = "system_security_update_good", codePoint = 61555, tags = listOf("Android", "OS", "approve", "approved", "cell", "check", "checkmark", "complete")),
        MaterialSymbolInfo(name = "system_security_update_warning", codePoint = 61556, tags = listOf("!", "Android", "OS", "alert", "attention", "bug", "caution", "cell")),
        MaterialSymbolInfo(name = "task", codePoint = 61557, tags = listOf("accepted", "agenda", "approve", "assignment", "box", "check", "check box", "checklist")),
        MaterialSymbolInfo(name = "thermostat", codePoint = 61558, tags = listOf("adjustment", "automation", "climate", "control", "cool", "cooling", "device", "energy")),
        MaterialSymbolInfo(name = "timer_10_select", codePoint = 61562, tags = listOf("10", "adjustment", "alphabet", "analog", "camera", "character", "circle", "clock")),
        MaterialSymbolInfo(name = "timer_3_select", codePoint = 61563, tags = listOf("3", "alphabet", "camera", "character", "choose", "chronometer", "circle", "clock")),
        MaterialSymbolInfo(name = "tungsten", codePoint = 61565, tags = listOf("adjustments", "balance", "bright", "brightness", "camera", "edit", "editing", "effects")),
        MaterialSymbolInfo(name = "usb", codePoint = 57824, tags = listOf("accessory", "cable", "computer", "connection", "connector", "data", "data transfer", "device"))
    )
}

internal val materialSymbols_device_chunk4: List<MaterialSymbolInfo> by lazy(LazyThreadSafetyMode.NONE) {
    listOf(
        MaterialSymbolInfo(name = "usb_off", codePoint = 58618, tags = listOf("block", "cable", "computing", "connection", "cross out", "data transfer", "device", "diagonal line")),
        MaterialSymbolInfo(name = "wallpaper", codePoint = 57788, tags = listOf("abstract", "background", "clouds", "customize", "dash", "dashed", "display", "graphic")),
        MaterialSymbolInfo(name = "water", codePoint = 61572, tags = listOf("abstract", "aqua", "basic", "beach", "clean", "drip", "drop", "droplet")),
        MaterialSymbolInfo(name = "widgets", codePoint = 57789, tags = listOf("add", "app", "arrange", "blocks", "box", "boxes", "components", "customize")),
        MaterialSymbolInfo(name = "wifi_1_bar", codePoint = 58570, tags = listOf("1", "1 bar", "arc", "bar", "bars", "broadcast", "cell", "cellular")),
        MaterialSymbolInfo(name = "wifi_2_bar", codePoint = 58585, tags = listOf("2", "access", "bar", "bars", "bars indicator", "cell", "cellular", "communication")),
        MaterialSymbolInfo(name = "wifi_calling_3", codePoint = 61573, tags = listOf("3", "audio", "calling", "cell", "cellular", "communication", "connection", "connectivity")),
        MaterialSymbolInfo(name = "wifi_channel", codePoint = 60266, tags = listOf("adjust", "arc", "arcs", "broadcast", "cellular", "channel", "communication", "configure")),
        MaterialSymbolInfo(name = "wifi_find", codePoint = 60209, tags = listOf("access point", "antenna", "arc", "arch", "bars", "broadcast", "cellular", "communications")),
        MaterialSymbolInfo(name = "wifi_lock", codePoint = 57825, tags = listOf("access", "authentication", "bars", "cellular", "connect", "connection", "connectivity", "data")),
        MaterialSymbolInfo(name = "wifi_password", codePoint = 60267, tags = listOf("access", "access code", "authentication", "authorization", "cellular", "connect", "connection", "connectivity")),
        MaterialSymbolInfo(name = "wifi_tethering", codePoint = 57826, tags = listOf("access point", "cell", "cellular", "cellular data", "connection", "connectivity", "data", "data share")),
        MaterialSymbolInfo(name = "wifi_tethering_error", codePoint = 60121, tags = listOf("!", "alert", "attention", "broken", "caution", "cell", "cellular", "communication")),
        MaterialSymbolInfo(name = "wifi_tethering_off", codePoint = 61575, tags = listOf("cell", "cellular", "connection", "connection disabled", "connection off", "crossed out", "data", "data off"))
    )
}

internal val materialSymbols_device_category: MaterialSymbolCategory by lazy(LazyThreadSafetyMode.NONE) {
    MaterialSymbolCategory(
        key = "device",
        icons = buildList {
            addAll(materialSymbols_device_chunk1)
            addAll(materialSymbols_device_chunk2)
            addAll(materialSymbols_device_chunk3)
            addAll(materialSymbols_device_chunk4)
        }
    )
}
